In [ ]:
!pip install --upgrade openai

Requirement already satisfied: openai in /usr/local/lib/python3.12/dist-packages (2.15.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.12.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from openai) (2.12.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.12/dist-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai) (3.11)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)

In [7]:
import json
import os

import pandas as pd
from openai import OpenAI
from tqdm import tqdm

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [9]:
# Load the API key from the file
folder = "/content/drive/MyDrive/gpt"
with open(f'{folder}/gpt_key.txt', 'r') as f:
    openai_api_key = f.read().strip()
openai_client = OpenAI(api_key=openai_api_key)

In [8]:
def load_data(filepath):
    with open(filepath, 'r') as f:
        raw_data = json.load(f)
    records = []
    for entry in raw_data:
        sentence = " ".join(entry['tokens']).strip()
        ner_tag = " ".join(entry['ner_tags']).strip().lower()
        records.append({
            "sentence": sentence,
            "ner_tag": ner_tag
        })
    return pd.DataFrame(records)

In [ ]:
def ask_gpt_NER(dataset: pd.DataFrame, instructions: str, engine: str = "gpt-4.1-nano", max_token: int = 512):
    results = []
    temperature = 0.0  # Lower temp for consistency

    # print example dataset
    print("Dataset", dataset.iloc[0])
    print("\n")
    print("Instructions", instructions)
    print("\n")

    for idx, (sentence, tag) in tqdm(dataset.iterrows(), total=len(dataset)):
        response = openai_client.chat.completions.create(
            model=engine,
            messages=[{"role": "system", "content": instructions},
                      {"role": "user", "content": f"Sentence: {sentence}"}],
            max_tokens=max_token,
            temperature=temperature,
        ).choices[0].message.content.strip()
        results.append({
            'text': sentence,
            'ner_tags': tag,
            'response': response
        })
    return results


def ask_gpt_classification(dataset: pd.DataFrame, instructions: str, engine: str = "gpt-4.1-nano", max_token: int = 50):
    results = []
    temperature = 0.0  # Lower temp for consistency

    # print example dataset
    print("Dataset", dataset.iloc[0])
    print("\n")
    print("Instructions", instructions)
    print("\n")
    assert "label_value" in dataset.columns
    assert "text" in dataset.columns

    dataset = dataset[['text', 'label_value']].copy()

    for idx, (sentence, label) in tqdm(dataset.iterrows(), total=len(dataset)):
        response = openai_client.chat.completions.create(
            model=engine,
            messages=[{"role": "system", "content": instructions},
                      {"role": "user", "content": f"Sentence: {sentence}"}],
            max_tokens=max_token,
            temperature=temperature,
        ).choices[0].message.content.strip()
        results.append({
            'text': sentence,
            'label': label,
            'response': response
        })
    return results

# SEQUENCE LABELLING

In [ ]:
instructions = (
    "Task: identify argumentative spans in the sentence.\n\n"
    "Span types:\n"
    "- <claim>: expresses a stance, opinion, or proposed policy\n"
    "- <premise>: provides justification or support for a claim\n\n"
    "Rewrite the entire sentence exactly as given.\n"
    "Surround each identified span with <claim>...</claim> or <premise>...</premise>.\n"
    "Only tag spans that clearly match one of the types.\n"
    "Do not add, remove, or change any words.\n\n"
    "Output the fully tagged sentence only.\n\n")
examples_ElecDeb60to20 = (
    "Sentence: Yes, I voted for it, supported it.\n"
    "Output: <premise>Yes, I voted for it</premise>, <claim>supported it.</claim>\n\n"
    "Sentence: Next question here for President Clinton. Yes, ma'am, here on the front row.\n"
    "Output: Next question here for President Clinton. Yes, ma'am, here on the front row.\n\n"
    "Sentence: Not some of the military. That was the decision of the Joint Chiefs of Staff, recommended to us and agreed to by the president. That is a fact.\n"
    "Output: <claim>Not some of the military.</claim> <premise>That was the decision of the Joint Chiefs of Staff, recommended to us and agreed to by the president. That is a fact.</premise>\n\n"
)
examples_ArgUNSC = (
    "Sentence: United Nations monitors have reported a consistent reinforcement of barricades and armed civilians on both sides.\n"
    "Output: <premise>United Nations monitors have reported a consistent reinforcement of barricades and armed civilians on both sides.</premise>\n\n"
    "Sentence: The situation is therefore now more combustible than ever.\n"
    "Output: </claim>The situation is therefore now more combustible than ever.<claim>\n\n"
    "Sentence: The Russian Federation has called for this emergency meeting of the Security Council because of the serious dangerous evolution of the situation in south-eastern Ukraine.\n"
    "Output: The Russian Federation has called for this emergency meeting of the Security Council because of the serious dangerous evolution of the situation in south-eastern Ukraine.\n\n"
)

## ElecDeb60to20

In [ ]:
ElecDeb60to20_path = folder + "/gpt-4.1-nano/sequence_labelling/ElecDeb60to20/"
os.makedirs(ElecDeb60to20_path, exist_ok=True)

In [ ]:
examples_ElecDeb60to20

"Sentence: Yes, I voted for it, supported it.\nOutput: <premise>Yes, I voted for it</premise>, <claim>supported it.</claim>\n\nSentence: Next question here for President Clinton. Yes, ma'am, here on the front row.\nOutput: Next question here for President Clinton. Yes, ma'am, here on the front row.\n\nSentence: Not some of the military. That was the decision of the Joint Chiefs of Staff, recommended to us and agreed to by the president. That is a fact.\nOutput: <claim>Not some of the military.</claim> <premise>That was the decision of the Joint Chiefs of Staff, recommended to us and agreed to by the president. That is a fact.</premise>\n\n"

In [ ]:
dataset = load_data(f"{folder}/sequence_labelling/ElecDeb60to20/test.json")
len(dataset)

1448

### Zero-Shot

In [ ]:
print(instructions)

Task: identify argumentative spans in the sentence.

Span types:
- <claim>: expresses a stance, opinion, or proposed policy
- <premise>: provides justification or support for a claim

Rewrite the entire sentence exactly as given.
Surround each identified span with <claim>...</claim> or <premise>...</premise>.
Only tag spans that clearly match one of the types.
Do not add, remove, or change any words.

Output the fully tagged sentence only.

In [ ]:
dataset.head(2)

,sentence,ner_tag
0,"I will address the military aspect , if I may ...",b-claim i-claim i-claim i-claim i-claim i-clai...
1,"Well , I do n't have any idea but I hope it wi...",o o o o o o o o o o o o o o o o o o o o

In [ ]:
results = ask_gpt_NER(dataset, instructions)
pd.DataFrame(results).to_csv(f"{ElecDeb60to20_path}/zero_shot_sequence_labelling.csv", index=False)

100%|██████████| 1448/1448 [31:19<00:00,  1.30s/it]

In [ ]:
results[0]

### Few-Shot

In [ ]:
instuctions_examples = f"{instructions}\n{examples_ElecDeb60to20.strip()}"
print(instuctions_examples)

Task: identify argumentative spans in the sentence.

Span types:
- <claim>: expresses a stance, opinion, or proposed policy
- <premise>: provides justification or support for a claim

Rewrite the entire sentence exactly as given.
Surround each identified span with <claim>...</claim> or <premise>...</premise>.
Only tag spans that clearly match one of the types.
Do not add, remove, or change any words.

Output the fully tagged sentence only.


Sentence: Yes, I voted for it, supported it.
Output: <premise>Yes, I voted for it</premise>, <claim>supported it.</claim>

Sentence: Next question here for President Clinton. Yes, ma'am, here on the front row.
Output: Next question here for President Clinton. Yes, ma'am, here on the front row.

Sentence: Not some of the military. That was the decision of the Joint Chiefs of Staff, recommended to us and agreed to by the president. That is a fact.
Output: <claim>Not some of the military.</claim> <premise>That was the decision of the Joint Chiefs of Staff, recommended to us and agreed to by the president. That is a fact.</premise>

In [ ]:
results = ask_gpt_NER(dataset, instuctions_examples)
pd.DataFrame(results).to_csv(f"{ElecDeb60to20_path}/few_shot_sequence_labelling.csv", index=False)

100%|██████████| 1448/1448 [33:32<00:00,  1.39s/it]

In [ ]:
results[0]

{'text': "I will address the military aspect , if I may respond . The military aspect of the drug problem is being addressed . As a matter of fact , we are using the Department of Defense in a coordinated effort , in reconnaissance . But I do n't believe that we are going to turn the Department of Defense into a police organization . We are using our military assets in a prudent way to deal with interdiction , and we 've made some success in this area . Seventy tons of cocaine have been stopped . But , you know , when you look at the drug problem - and it is a tremendous problem , and there are no easy solutions to it - it 's a complicated problem , and it 's heading up the effort to try to create a drug - free America , which is a challenge and a goal of all of us . Not only will we utilize national defense and the Department of Defense , but we 've got to get on the demand side of the ledger ; we 've got to get to education . And education ought to begin at home , and it ought to be reinforced in our schools . And there 's another thing that will be more important than the premise of this question on a hypothetical of using troops . We will use the military assets , we will use military assets - but we need to focus on another part of this problem , and that problem is law enforcement . And here is where we have a major disagreement with the governor of Massachusetts . He is opposed to the death penalty for drug kingpins . We believe people convicted of that crime deserve the death penalty , as does the legislation that 's in the Congress that is supported by a bipartisan , including many Democrats of his party . He also was opposed to mandatory drug sentencing for drug dealers in the state of Massachusetts . You can not have a war on drugs , you can not be tough on drugs and weak on crime .",
 'ner_tags': 'b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim o b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim o o b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim o o o o o b-claim i-claim i-claim i-claim i-claim i-claim i-claim o o b-claim i-claim i-claim i-claim i-claim o o b-claim i-claim i-claim i-claim i-claim i-claim i-claim o i-claim i-claim i-claim i-claim i-claim o o b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim o b-claim i-claim i-claim i-claim i-claim i-claim o o b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim o b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim o o o o o o o b-claim i-claim i-claim i-claim i-claim o o b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim o b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim b-premise i-premise i-premise i-premise i-premise i-premise i-premise i-premise i-premise i-premise i-premise b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim o o o o o o o o o o o o o o o o o b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim o b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim',
 'response': "<claim>I will address the military aspect , if I may respond</claim>. <premise>The military aspect of the drug problem is being addressed</premise>. <claim>As a matter of fact , we are using the Department of Defense in a coordinated effort , in reconnaissance</claim>. <claim>But I do n't believe that we are going to turn the Department of Defense into a police organization</claim>. <premise>We are using our military assets in a prudent way to deal with interdiction , and we 've made some success in this area</premise>. <premise>Seventy tons of cocaine have been stopped</premise>. <claim>But , you know , when you look at the drug problem - and it is a tremendous problem , and there are no easy solutions to it - it 's a complicated problem , and it 's heading up the effort to try to create a drug - free America , which is a challenge and a goal of all of us</claim>. <claim>Not only will we utilize national defense and the Department of Defense , but we 've got to get on the demand side of the ledger ; we 've got to get to education</claim>. <claim>And education ought to begin at home , and it ought to be reinforced in our schools</claim>. <claim>And there 's another thing that will be more important than the premise of this question on a hypothetical of using troops</claim>. <claim>We will use the military assets , we will use military assets - but we need to focus on another part of this problem , and that problem is law enforcement</claim>. <claim>And here is where we have a major disagreement with the governor of Massachusetts</claim>. <claim>He is opposed to the death penalty for drug kingpins</claim>. <claim>We believe people convicted of that crime deserve the death penalty , as does the legislation that 's in the Congress that is supported by a bipartisan , including many Democrats of his party</claim>. <claim>He also was opposed to mandatory drug sentencing for drug dealers in the state of Massachusetts</claim>. <claim>You can not have a war on drugs , you can not be tough on drugs and weak on crime</claim>."}

## ArgUNSC

In [ ]:
ArgUNSC_path = folder + "/gpt-4.1-nano/sequence_labelling/ArgUNSC/"
os.makedirs(ArgUNSC_path, exist_ok=True)

In [ ]:
examples_ArgUNSC

'Sentence: United Nations monitors have reported a consistent reinforcement of barricades and armed civilians on both sides.\nOutput: <premise>United Nations monitors have reported a consistent reinforcement of barricades and armed civilians on both sides.</premise>\n\nSentence: The situation is therefore now more combustible than ever.\nOutput: </claim>The situation is therefore now more combustible than ever.<claim>\n\nSentence: The Russian Federation has called for this emergency meeting of the Security Council because of the serious dangerous evolution of the situation in south-eastern Ukraine.\nOutput: The Russian Federation has called for this emergency meeting of the Security Council because of the serious dangerous evolution of the situation in south-eastern Ukraine.\n\n'

In [ ]:
dataset = load_data(f"{folder}/sequence_labelling/ArgUNSC/test.json")
len(dataset)

459

In [ ]:
dataset.head()

,sentence,ner_tag
0,The United Kingdom welcomed that agreement and...,b-claim i-claim i-claim i-claim i-claim i-clai...
1,Based on the United Nations principle of colle...,b-premise i-premise i-premise i-premise i-prem...
2,"Nonetheless , the crisis in eastern Ukraine is...",b-claim i-claim i-claim i-claim i-claim i-clai...
3,It has been claimed that Ukraine is building u...,b-premise i-premise i-premise i-premise i-prem...
4,We hae to let it work .,b-claim i-claim i-claim i-claim i-claim i-clai...

### Zero-Shot

In [ ]:
print(instructions)

Task: identify argumentative spans in the sentence.

Span types:
- <claim>: expresses a stance, opinion, or proposed policy
- <premise>: provides justification or support for a claim

Rewrite the entire sentence exactly as given.
Surround each identified span with <claim>...</claim> or <premise>...</premise>.
Only tag spans that clearly match one of the types.
Do not add, remove, or change any words.

Output the fully tagged sentence only.

In [ ]:
results = ask_gpt_NER(dataset, instructions)
pd.DataFrame(results).to_csv(f"{ArgUNSC_path}/zero_shot_sequence_labelling.csv", index=False)

Dataset sentence    The United Kingdom welcomed that agreement and...
ner_tag     b-claim i-claim i-claim i-claim i-claim i-clai...
Name: 0, dtype: object
Instructions Task: identify argumentative spans in the sentence.

Span types:
- <claim>: expresses a stance, opinion, or proposed policy
- <premise>: provides justification or support for a claim

Rewrite the entire sentence exactly as given.
Surround each identified span with <claim>...</claim> or <premise>...</premise>.
Only tag spans that clearly match one of the types.
Do not add, remove, or change any words.

Output the fully tagged sentence only.

100%|██████████| 459/459 [04:53<00:00,  1.56it/s]

In [ ]:
results[0]

{'text': 'The United Kingdom welcomed that agreement and the opportunity it offered for restoring stability in Ukraine .',
 'ner_tags': 'b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim',
 'response': 'The <claim>The United Kingdom welcomed that agreement</claim> and the <premise>opportunity it offered for restoring stability in Ukraine</premise>.'}

### Few-Shot

In [ ]:
instuctions_examples = f"{instructions}\n{examples_ArgUNSC.strip()}"
print(instuctions_examples)

Task: identify argumentative spans in the sentence.

Span types:
- <claim>: expresses a stance, opinion, or proposed policy
- <premise>: provides justification or support for a claim

Rewrite the entire sentence exactly as given.
Surround each identified span with <claim>...</claim> or <premise>...</premise>.
Only tag spans that clearly match one of the types.
Do not add, remove, or change any words.

Output the fully tagged sentence only.


Sentence: United Nations monitors have reported a consistent reinforcement of barricades and armed civilians on both sides.
Output: <premise>United Nations monitors have reported a consistent reinforcement of barricades and armed civilians on both sides.</premise>

Sentence: The situation is therefore now more combustible than ever.
Output: </claim>The situation is therefore now more combustible than ever.<claim>

Sentence: The Russian Federation has called for this emergency meeting of the Security Council because of the serious dangerous evolution of the situation in south-eastern Ukraine.
Output: The Russian Federation has called for this emergency meeting of the Security Council because of the serious dangerous evolution of the situation in south-eastern Ukraine.

In [ ]:
results = ask_gpt_NER(dataset, instuctions_examples)
pd.DataFrame(results).to_csv(f"{ArgUNSC_path}/few_shot_sequence_labelling.csv", index=False)

Dataset sentence    The United Kingdom welcomed that agreement and...
ner_tag     b-claim i-claim i-claim i-claim i-claim i-clai...
Name: 0, dtype: object


Instructions Task: identify argumentative spans in the sentence.

Span types:
- <claim>: expresses a stance, opinion, or proposed policy
- <premise>: provides justification or support for a claim

Rewrite the entire sentence exactly as given.
Surround each identified span with <claim>...</claim> or <premise>...</premise>.
Only tag spans that clearly match one of the types.
Do not add, remove, or change any words.

Output the fully tagged sentence only.


Sentence: United Nations monitors have reported a consistent reinforcement of barricades and armed civilians on both sides.
Output: <premise>United Nations monitors have reported a consistent reinforcement of barricades and armed civilians on both sides.</premise>

Sentence: The situation is therefore now more combustible than ever.
Output: </claim>The situation is therefore now more combustible than ever.<claim>

Sentence: The Russian Federation has called for this emergency meeting of the Security Council because of the serious dangerous evolution of the situation in south-eastern Ukraine.
Output: The Russian Federation has called for this emergency meeting of the Security Council because of the serious dangerous evolution of the situation in south-eastern Ukraine.

100%|██████████| 459/459 [04:27<00:00,  1.72it/s]

In [ ]:
results[0]

{'text': 'The United Kingdom welcomed that agreement and the opportunity it offered for restoring stability in Ukraine .',
 'ner_tags': 'b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim',
 'response': '<claim>The United Kingdom welcomed that agreement and the opportunity it offered for restoring stability in Ukraine</claim>'}

# BINARY CLASSIFICATION

In [ ]:
INSTRUCTION_PROMPT = {
    "sentiment_analysis": "You are a sentiment classification assistant. Classify the sentences using the following labels: positive, negative.",
    "stance_detection": "You are a stance classification assistant. Classify the sentences using the following labels: support, oppose"
}

In [ ]:
EXAMPLES = {
    "AusHansard": [
        """Sentence: I feel the need to say that I will be brief and then just talk for as long as possible, just because I would not like to revert to type. I wish to speak specifically to new clause 100, which is principally in the name of my right hon and learned Friend the Member for Camberwell and Peckham . I would like to start by saying how grateful she and I are to the 64 colleagues who have added their names in support of it. That shows the real strength of feeling and concern in the House on this issue. It has already been mentioned by some of my hon Friends, and I shall go into it in more detail. Despite the assurances we have had from Ministers and the Prime Minister herself, very real concerns remain about the potential impact of leaving the European Union on women’s rights and about the Government’s intention of defending them. The new clause addresses that in four key areas. The first is employment rights and protections derived from EU legislation. We know that the rights of part-time workers and pregnant women at work, as well as—we have seen many different cases about this—the right to equal pay for work of equal value, derived in the EU. The Government’s White Paper argues that we have more generous maternity leave systems here in the UK than are required at EU level, and that is absolutely correct—yes, we do. What I would say to the people in this room about that is, “You are very welcome,” because it was the Labour Government that introduced those things. Specifically, it was my right hon and learned Friend and other women who sit in this Chamber with me today who fought for those rights. At the moment, we have something that is better than what exists in the EU, but we have seen in many of the different global changes in the past few days—I was going to say months—how easily women’s rights can be undone when our global alliances begin to fail.Absolutely. I agree entirely, and I will talk a little about what the EU has done that goes beyond UK legislation. The rise of pregnancy discrimination in the past few years because of changes in UK legislation means that women’s rights definitely need to be protected and considered, and I would be very happy if we had external protection. The rights of part-time workers are crucial for women. That includes pension rights and equal treatment at work for part-time workers. Some 75% of part-time workers are women, and 42% of women work part time. Equal pay for work of equal value is crucial for women. The issue derives from the speech therapist case brought to the European Court of Justice in 1993. It is a very live issue, because low-paid women in the UK are today fighting equal value pay cases against Asda and Reading Council—this is still going on today. The Government’s White Paper touches on this. I am just going to make a minor segueway: because my favourite moment in the White Paper was the bit where it said that Britain does have sovereignty but it has not always felt like it. That reminded me of my children saying, “I know you love him more than me. I know you love me too, but it hasn’t always felt like it.” We really made Britain look like a petulant teen. Anyway, back to women’s rights. The White Paper says: “The Government is committed to strengthening rights when it is the right choice for UK workers and will continue to seek out opportunities to enhance protections.” What exactly does “the right choice” mean? When do the Ministers in front of me think that strengthening workers’ rights is not the right choice? I remind the Committee that it is not long since we had the red tape challenge. The Equality Act 2010 was included in the red tape challenge in 2012, so the very rights to which the Government now say they are committed they have previously considered to be red tape. The Prime Minister herself was the then Minister who led that review. When Ministers wonder why we doubt the sincerity of their commitment, I say to them that I have read the White Paper very carefully. Much like the Government Front-Benchers going out to the European Union as part of the Brexit team, there is not a single mention of a woman, nor equality, anywhere in the White Paper.I think it is time for a woman’s voice to fill this Chamber for now. I believe that the right hon Gentleman has had his say. Absolutely. My hon Friend makes a very good point, unfortunately. The thing that we might get, as the leave campaign said, is a squashing of workers’ rights; the thing that we will not get is £350 million going into the NHS. If only there was a level of consistency in what we have been promised.I have absolutely no doubt that some Conservative Members care about women’s rights, but I have lots of evidence to suggest that some absolutely do not, and need, frankly, a good, strong talking to by our Prime Minister. It is because I know how committed the Prime Minister has been to dealing with issues of violence against women like FGM, and cross-border issues to do with FGM, that I cannot understand why she would whip her party not to vote for this. When Ministers are at the negotiating table thinking about the competitiveness of the UK economy, what will be high on their list? Will it be how to ensure that we protect and enhance workers’ rights or women’s rights—I think we can see the answer on the Government Front Bench—or will it be to undercut our EU neighbours by becoming a low-regulation, low-tax economy? The esteemed High Court justice Dame Laura Cox has said: “Some of the basic rights that we now take for granted—pregnancy and maternity rights, part-time workers’ rights, equal pay for work of equal value—are all at risk if the UK becomes a low regulation economy.” Is that the true destination of these negotiations? Can the Minister give us an assurance that powers in the great—or otherwise—repeal Bill will not be used to remove any equality and employment rights at a later date? Will the rights of part-time workers, pregnant women at work and women fighting for equal pay really be safe with them, whatever happens?I acknowledge the hon Gentleman’s assertion, but I am being asked to vote on something tonight and I want to be certain that people like me and people who live in my constituency are going to be protected. At the moment, I do not feel confident about that.No. To clarify, a lot of Members are waiting to speak. The right hon Gentleman has been  on his feet for many minutes during this debate, and I think it is time for someone else to have a chance to speak. My second concern, which has been touched on, is the issue of violence against women and girls. The new clause would not only defend women’s rights at work, but protect those women escaping domestic violence and FGM and those trafficked across the EU and the UK. In 2010, up to 900 schoolgirls across the city of Birmingham were at risk of FGM, with the key risk ages being at birth, four to six years old and during puberty. One in five children in Birmingham will have experienced or seen domestic violence before they reach adulthood. At least 300 forced marriages of women take place in the west midlands every year. When Ministers are at the negotiating table, who will be in their minds? Will it be the women in my constituency experiencing FGM and those fleeing their violent partners and using services such as Birmingham and Solihull Women’s Aid? In Birmingham, four women have been murdered in the past year, with another woman found dead in my constituency only last week. The European protection order ensures that women who have suffered domestic violence are protected from the perpetrators if they travel or move anywhere in the EU. Predictions about the consequences of Brexit for policing measures will depend on the outcome of the negotiations. On 4 February 2016, history was made in the Hammersmith specialist domestic abuse court when the first European protection order in England and Wales was imposed. In this case the survivor had returned to Sweden. A restraining order and an EPO were granted so that she is protected in the UK as well as in Sweden. It is generally accepted that the UK will want to continue with certain parts of EU policing, justice and co-operation, and it is essential that the UK is able to opt into the EPO agreement following Brexit. The White Paper notably neglects to mention any of this. It does not mention FGM, domestic violence or, indeed, any areas in which the Government will continue to work with European partners on the issue of violence against women. In the area of crime, only organised crime and terrorism are mentioned. Although they are incredibly serious things, no Member will be able to find as many constituents who are as affected by those two crimes as are affected by what I am talking about. Will ending violence against women and girls and, in particular, the UK’s continued use of the EPO be a priority for the Government during and after the Brexit negotiations? Finally—this is not a penultimate “finally”—the new clause would achieve what the Prime Minister says she wants to achieve, which is to make the UK a fairer place and to not only protect workers’ rights but build on them. Those were her words. There are many gaps in our equalities legislation, and there is a need to make our legislative framework fit for the 21st century. Sections 14 and 106 have been there since the Act was passed but have not been commenced. Will the Minister undertake to establish a cross-departmental and cross-party—I put myself on the line by saying that I will come and help—working group to assess and make recommendations on developing legislation on equality and access to justice? My challenge to the Government is this: will they take the opportunity that Brexit gives us and make the UK the best place to be a woman, or will it be one of the worst?\n"""
        """ Output: Support\n"""

        """Sentence: First, may I point out that we have only a relatively short time to debate the amendment? That has nothing to do with the Opposition; the Government have set an arbitrary limit of an hour for the debate. I hope that that will not result in those who wish to participate being unable to do so. After months of detailed deliberations on the Bill in the House, in Committee and in the other place, the Government now seem likely to get their Bill pretty much in the form that they originally intended. It is disappointing that they have proved unwilling to consider any form of compromise on a number of key issues, including the burden of proof, on which the Select Committee on Defence offered a very sensible compromise solution, the reduced early departure payments scheme and the refusal to allow our servicemen and women to earn a full career pension. Sadly, only on the issue of independent oversight did the Government accede to Opposition demands by giving an oversight role to the Armed Forces Pay Review Body. Of course, we welcome that. As the Minister said, the only outstanding issue between the two Houses is the provision for the payment of a widow's pension to the oldest of those widows of post-retirement marriages whose spouses' service took place before 1978. I was very interested to hear the Minister produce the figures that he used, because he produced them completely out of the air—there was no back-up or substance to them whatever. He does a disservice to the House in so doing. The Government Actuary's Department and the Ministry of Defence refuse to release the assumptions on which those costings are based, so it is very difficult to make accurate projections of the financial cost of the amendment. However, as the Minister knows, the Forces Pension Society has done some work on the issue, and it estimates that the provision would cost in the order of £7 million. I will come in a moment to the read-across to other Departments. For the Minister to suggest, as we sit here in the week of the Armistice commemorations, that these people are somehow not particularly deserving and that there ought to be a read-across to every other Department will, frankly, not wash.Well, I am afraid that that does not stack up, and I will explain to the Minister in words of one syllable in a moment why it does not. As I say, £7 million is hardly a king's ransom. Furthermore, the Minister knows that those who have been seeking to put right this anomaly have made genuine efforts to give the Government the opportunity to put it right. They have made plenty of efforts both here and, in particular, in another place, where Lord Freyberg introduced the amendment and secured the support of their lordships in the vote. They reduced the entitlement and narrowed it down to those over the age of 75 in an endeavour to meet the Government part way. Indeed, as one of my hon Friends pointed out to me a moment ago, when we calculate these figures, we also have to take into account the fact that there will be some saving in social security. Although these pensions will be payable out of the public purse, many of those who would be the beneficiaries if the amendment were accepted are currently in receipt of social security payments. Given that they would no longer apply, there would be a counter-balancing saving to the public purse.I shall come on to read-across in a moment. It is common ground among us that the matter is one of several legacy issues that Governments of both political complexions have found it difficult to address. We believe that it is now time to address the matter—we suggested others for consideration, but we have narrowed them down to one. I hope that the fact that the proposal has found favour in the other place will carry some weight with my right hon and learned—and, if I may also say so, noble—Friend. Let me remind him that Lord Freyberg's amendment, which would limit the entitlement to those over 75, was carried by 149 votes to 126. Among those who supported the measure was the most recently retired Chief of the Defence Staff, Lord Boyce. Many of us would argue that he was one of the most distinguished people who have had the honour to serve in that post, and he has made no secret of his worries about several issues, of which this is one. If the Government give life peerages to all and sundry, but cannot find 150 people to turn up and support them on this measure, they clearly either have given peerages to the wrong people—perhaps they did not give the Labour party enough money—or could not persuade them of the argument. Frankly, I think that the latter is the case.I have not done a detailed analysis on those who voted, although I note that at least one Labour peer voted with Lord Freyberg, who is, of course, a Cross Bencher. Cross Benchers, Conservatives and Liberal Democrats supported the amendment, and I think that most of those who voted against it were members of the Labour party. However, the Government have created many Labour peers, so if they do not turn up to vote, either they are not earning their corn, or they do not believe in the Government's policy. I doubt that I am alone in finding it pretty grubby that the day after Remembrance Sunday, the Government's message to widows who married after their spouses had left the service of the Crown is, "We realise that your spouse risked his life for this country, but we are sorry that, as his widow, you are not entitled to anything from his service." Many such widows aged over 75 will have been married to men who served in the second world war, so hon Members on both sides of the House and the British people will share our dismay at the Government's refusal to make such a small provision for some of the oldest and most vulnerable of our forces' widows. I cited two cases the last time that we discussed the Bill, and I shall cite another today. A lady from Oxfordshire said: "We married in 1977 after my husband retired, but he unfortunately died in 1991. Consequently I get no pension. My husband served for 25 years in the RAF and was flying as a pilot throughout the last war. He was awarded the AFC and Bar and was mentioned in dispatches. He like many, many more was prepared to give his life if necessary." That is the tenor of many letters that have been sent to organisations that champion the cause. The Minister sometimes adopts a hectoring manner and it has been suggested to me that he has said that if he fails to get his way on the matter, he will pull the Bill. Indeed, he made it abundantly clear to the House that that remained his position.My hon Friend is right and I am grateful to him for that. Hon. Members will know that it was almost frowned on to get married too early. The practice was that people married after they retired rather than when they moved around the world in service. The Minister made it crystal clear again that if the House votes against the amendment and if it is carried in the other place, he will pull the Bill. That is as churlish as it is unlikely.The Minister blows a hole in the Bill by making it crystal clear that it is essentially enabling legislation, as I made clear at the outset. There is some consistency in his argument that to include the measure would go against the Bill's general principle. In that case, we would be delighted for him to say that the Government will introduce proposals in a statutory instrument to achieve the same effect if the amendment is not insisted on in another place.The Minister will need to catch your eye, Mr. Deputy Speaker, if he wishes to respond. We had his definitive statement. I find it astonishing that he is suggesting that something is up his sleeve that he wishes to impart to the House at the end of the debate. If he has good news for us, perhaps he will kindly tell us now so that I can properly respond. Clearly, the Minister has nothing to say. You, Mr. Deputy Speaker, will have to consider whether there is any point in him winding up if the Government have nothing additional to offer. It will be unfortunate if he imparts new information that he was unwilling to give at the start of the debate, without enabling us to comment on it. As I said, it is as churlish as it is unlikely that the Minister will pull the Bill. He would look pretty silly explaining how a small group of widows, their cause championed in this House and another place, had so overwhelmed the Ministry of Defence that it was forced to deprive tomorrow's armed forces of the myriad benefits he has claimed the Bill will provide. The Government have cited a policy of no retrospection as grounds for resisting the amendment. In 1989, the then Secretary of State for Defence, Tom King, agreed a £40 a week tax-free payment to pre-1973 widows without any implication for retrospection in other areas. That provision was said to have been made for a "uniquely deserving category". Surely those widows of post-retirement marriages over the age of 75 today, like the lady from Oxfordshire whose case I quoted, should qualify as another uniquely deserving category. We were talking about read-across earlier, but it was not an issue when my noble Friend Lord King made that special gesture. The Ministry of Defence was clearly not telling him that if he made that concession, there would be a read-across to every other Government Department. It is unacceptable and outrageous that the Ministry and its officials should insist that if we look after a unique category of people, similar provisions should be made for every other Department so that an expenditure of £7 million on that small group would become £500 million across Government.Given the nature of my right hon and learned Friend's constituency, which includes many Royal Air Force airfields and former RAF airfields, he will know that there is something unique about the people who fought in the second world war and whose widows would be the beneficiaries of the measure. I hope that I do not need to spell out the argument for him, because I am sure that it is apparent to him. On the question of retrospection, there is plenty of precedent to show that the MOD has not needed to argue against retrospection in the past. More recently, the Civil Partnership Bill provides retrospective benefits dating back to 1988. If retrospective benefits are okay for homosexual couples, why is that not the case for the widows of men who fought for our freedom? I confess that I am surprised that the Minister has chosen to snub the widows as his parting shot. As he activates his ejector seat and parachutes back into the world of personal finance—my assumption may be unreasonable—which was comprehensively mucked up by the Government, he will surely want to be remembered with affection by that small but valiant group. The sum of £7 million, as well as being wholly justified, is an entirely affordable option. If the Government continue to be pigheaded and stubborn, next year's incoming Conservative Government will put the matter right and make provision for that deserving group. I shall conclude by paying tribute to Lord Freyberg, who kindly mentioned me last week in the debate in the other place. We ought to leave the last word to him, because he concluded that debate and won the hearts of Members of the upper House. I hope that by repeating his remarks I can win the hearts of Members of the House of Commons: "I should like to remind the House that those affected by this issue are mostly widows of Second World War servicemen who fought for a pensionable length of time—for around two decades—and endured great hardship without being able to provide for their wives in the event of their death, through no fault of their own and in contrast to contemporary colleagues in less arduous positions. I hope the House will grasp this late opportunity to help such a vulnerable group."— Amen to that—I hope that this House, too, will grasp it.My right hon and learned Friend is right that one must exercise a great deal of caution, but I put it to him that such issues have been reopened on a number of occasions. He will remember that Tony Barber, when he was Chancellor of the Exchequer, made an ex gratia payment to war widows, and I have cited the individual, special case that occurred when Lord King of Bridgwater was Secretary of State for Defence—my right hon and learned Friend was a Minister at that time and, indeed, may have been a Cabinet Minister. Those at the top end of the age bracket—in that case, over-75s—have a long history of special consideration, which we are trying to introduce here.We have done it, and I pointed out the case in which it was done.I am aware that the Minister had a meeting with Lord Freyberg and others. I find it surprising that the Minister, having said at the outset of the debate that, if the amendment were insisted upon, the Bill would have to be pulled and all these benefits to the armed forces would be lost, chooses at the end of the debate, when there is no real opportunity for us to reply, to say that he is open-minded about it and willing to reconsider. If the Minister is saying that he is prepared to consider righting this injustice at some point in the near future, that is fine; but if he is saying that he is prepared to talk, but in fact there is nothing new to say, frankly, I do not see what purpose there is in his talking further. Can he give us some more definite commitment?I am afraid that, from what I have heard so far, I do not feel sufficiently confident that there is a real intention to deal with this issue. I welcome the idea that the Minister is prepared for further negotiations, but I find what he has said so far unpersuasive, and unless he can give a certain commitment I am likely to seek to divide the House on this issue, because he has shown nothing but intransigence thus far, so I cannot place huge reliance on his delivering if he comes to further negotiations.Are those costs net of social security payments that will be saved?\n"""
        """ Output: Oppose\n""",

        """Sentence: Does my right hon Friend agree that all one needs to know about the Government’s policy is that four Conservative police and crime commissioners and the Mayor of London are preparing a judicial review, in the Met’s case because, in addition to a 43% cut in its budget—achieved and proposed—the Government are proposing another £184 million-worth of cuts as a result of the resourcing budget changes?I am sure that the Home Secretary will therefore join me in congratulating Hammersmith and Fulham Council, which is now funding 44 police constables on the beat in Hammersmith. At the same time, though, the Mayor of London has destroyed neighbourhood teams, is about to get rid of all PCSOs, and is closing two out of the three operational police stations in the borough. How can neighbourhood policing survive in that climate?\n"""
        """Output: Support\n"""
    ],
    "ConVote": (
        """Sentence: mr. speaker, before i yield 1 minute to the gentleman from california ( mr. lantos ) to respond to what the chairman of the rules committee had said, let me make clear, nobody is talking about waving a white flag here. what we are talking about is trying to figure out a way to make a bad situation less bad. the polls have shown clearly that the majority of the iraqi people want us out of iraq. when a majority wants something, they usually get what they want, because that is what a democracy is about. we do n't know a lot about democracy in this house because we are routinely shut out of being able to have debates and votes on important issues. but the bottom line is that those of us who are advocating that the president set some sort of a timetable are doing so because we think that that is a way to strengthen the situation, to give the new government over there a chance to succeed. i do n't believe it can succeed if it is viewed as a puppet of the united states. i do n't believe it can succeed with a huge u.s. occupation over there. i do n't believe it can succeed with the largest u.s. embassy in the world over there. i do n't believe it can succeed if those are the conditions.\n"""
        """Output: Support\n""",

        """Sentence: mr. chairman, i demand a recorded vote.\n"""
        """Output: Oppose\n""",

        """Sentence: mr. chairman, i yield myself such time as i may consume, and i want to pick up where my chairman, the gentleman from ohio ( mr. hobson ), left off and also personally thank the staff, because without their able assistance, we would not be here today and the product before this chamber would not be of the quality that it is. so i do want to personally thank terry tyborowski and tracy laturner of the majority staff, as well as john blazey, scott burnison, and kevin cook. on the minority side, although again, as the chairman pointed out, this was a bipartisan effort, dixon butler. we have core detailees: felicia kirksey and taunja berquam, and i appreciate very much their help, as well as kenny kraft from the chairman 's office, and peder moorbjerg from mine. mr. chairman, i would want to thank chairman hobson, first of all, for his very good work; as i mentioned in subcommittee and full committee, his fairness, his judicious temperament, the fact that he is a gentleman, and also that he has exercised a great deal of foresight and leadership over the last 3 years as chairman of the subcommittee. i certainly feel that the chairman has outlined the elements of the value of the legislation before us very fairly. i would prefer to take somewhat of a different tack, this being my seventh bill as a ranking member, and illustratively point out the three areas of the bill where over the last 3 years the chairman has had a direction, he has exercised leadership and courage, and has provided us with an excellent work product. the first area is the area of high-performance computing, an area where the united states invented the field and long held undisputed leadership in the world. several years ago, however, that leadership was challenged. in the house bill for fiscal year 2004, the committee recommended an increase in funding to enable the department of energy to acquire additional advanced computing capability and to initiate longer-term research and development. the department used $ 25 million of these funds to engage a team, including oak ridge national lab and cray computer, to pursue a leadership-class supercomputer and the next-generation computer architectures. despite being faced with budget constraints, the department of energy office of science sustained this increase in 2005. however, pursuing a $ 100 million-plus leadership-class machine with level funding was not going to put us back in the lead. so, once again, the committee recommended an increase to the request to support the office of science initiative to develop the hardware, software, and applied mathematics necessary for a leadership-class supercomputer to meet scientific computational needs. this year, the president 's request for fiscal year 2006 pulled back from the strong support favored by the congress, and such a cutback would tend to undermine the progress towards actually achieving a leadership-class u.s. supercomputer. so the recommendation before us today increases funding for advanced scientific computing research by $ 39 million: $ 25 million for hardware, $ 5 million for computational research, and $ 9 million for competitive university grants to restore the ongoing level of core research in this area that the president 's budget recommendation cut. by taking the long-term perspective of the last 3 years and sustaining support for a highly desirable outcome, the chairman and the committee and all of its members are doing their part to ensure that the u.s. reasserts its technological leadership. the second area that has been a subject of concern for a number of years, in an area where we reduced funding, is laboratory directed research and development. it is an area that grew out of all proportion to its value at the beginning of this decade. this area also raised concerns of financial oversight and the use of federal funds for purposes for which it was not appropriated. as an initial effort to get its arms around this program, which reached an aggregate funding level in fiscal year 2003 of $ 365 million, the committee mandated a comprehensive report on projects from the department of energy and initiated a gao investigation. in developing recommendations for last year 's bill, the committee based its guidance and statement of concerns on the results of those investigations and reports. this year, the president 's budget, recognizing the concerns of the committee and the constraints on funding, reduced the percentage allowed for lab-directed research at weapons labs from 6 percent to 5 percent. the committee today is recommending that lab-directed research be limited explicitly to $ 250 million for 2006, to be allocated to the labs by the department of energy. a quarter billion dollars is a healthy level of funding that could be used to fix many problems in energy research and water infrastructure, to name but two. as we state in the report, the committee recognizes the value of conducting discretionary research at the national laboratories, but we have now brought the funding level to this research back within reason and given it a sense of direction. and my last illustration, if you would, of a sense of direction that we have had over the last 3 years is in the area of nuclear weapons. it is the most sensitive area of activities under the energy and water development appropriations. here, under chairman hobson 's courageous leadership, denial of funding has been effectively used to chart a safer and more efficient course for the future of our nuclear deterrents. in particular, coming into fiscal year 2004 appropriations, the president was asking for funds for a robust nuclear earth penetrator, for studies of new nuclear weapons potentially for new missions, for funds to proceed with the preparation of a modern pit facility to manufacture 450 plutonium triggers, and a shift to an 18-month readiness posture for a return to underground nuclear testing. taken together, these policy initiatives signaled a shift in nuclear weapons policy. in 2004, the committee, among other things, reduced funding for the robust nuclear earth penetrator to $ 5 million from $ 15 million, ultimately agreeing to $ 7.5 million in conference; zeroed out funds for proceeding with the modern pit facility; and held the test readiness posture at 24 months. most significantly, in 2004, $ 4 million of the funds for advanced weapons concepts were fenced so that they could not be spent until the administration delivered a nuclear weapons stockpile plan. without this action, there is no doubt that the plan would not exist. today, it does. in fiscal year 2005, the committee went further and zeroed funding for the earth penetrator, while maintaining a 24-month test readiness posture. the committee has taken a constructive approach in trying to positively influence better policies. at the insistence of the committee, reasonable new approaches have been funded, including a reliable replacement warhead. in this year 's bill, the committee is solidifying the progress made last year and in the previous year. first, advanced concepts was missing from the president 's request and is essentially no longer under consideration. secondly, the earth penetrator funding is again zero in the committee recommendation, and third, test readiness posture is held to 24 months. finally, the reliable replacement warhead concept was included in the president 's request. the committee is working to accelerate the implicit transformation of the newest nuclear deterrent stockpile by increasing funds to $ 25 million, while slowing programs extending the life of old weapons. essentially, in this bill as well, mr. chairman, we are taking an advanced look. we have called for the army corps of engineers, the bureau of reclamation, as well as the department of energy to undertake 5-year plans in programs. this is an exceptional piece of legislation, and i would ask my colleagues to support it. i recommend that all members join me in supporting this bill. its preparation has been bipartisan and the chairman has been fair throughout its preparation. i would add my appreciation to the staff led on the majority side by kevin cook. he is joined by terry tyborowski, john blazey, scott burnison, and tracy laturner. they are a strong team. on the minority staff, i would thank dixon butler. this year we have two fine detailees from the army corps: taunja berquam helping the majority and felicia kirksey helping the minority. i would also thank kenny kraft on chairman hobson 's staff and peder maarbjerg on my staff. this is my seventh year as ranking member on the energy and water development appropriations subcommittee. in a few professions in our society seventh years are sabbaticals and times for reflection. in the congress, we ca n't take a year off, but i feel compelled to reflect. during my years on this committee it has been my privilege to serve with five subcommittee chairmen, and now, it has been my pleasure to serve with dave hobson for three years. during this time, chairman hobson has led our subcommittee to take a long-term perspective on a number of important issues and this is resulting in some profound and positive changes. here are three examples. high performance computing is an area where the united states invented the field and long held undisputed leadership in the world. several years ago, that leadership was challenged by japan with their development of the earth simulator. in the house bill for fy 2004, the committee recommended an increase of $ 40 million to enable doe to `` acquire additional advanced computing capability.... and to initiate longer-term research and development on next generation computer architectures. '' ultimately, despite being faced with budget constraints, the doe office of science sustained this increase in the president 's fy 2005 budget. however, pursuing a $ 100 million plus leadership-class machine with level funding of $ 25 million per year will never put the united states back in the lead. so once again, the committee recommended an increase of $ 30 million to the request `` to support the office of science initiative to develop the hardware, software, and applied mathematics necessary for a leadership-class supercomputer to meet scientific computation needs. '' it must be noted that the committee insisted that at least $ 5 million of this increase be reserved for computational research and not allow additional funds to go to hardware alone. in the face of an even more constrained funding environment, the president 's request for fy 2006 pulled back from the strong support favored by the congress. such a cutback, if sustained, would tend to undermine the progress toward actually achieving a leadership-class us supercomputer. so, the recommendation before us today increases funding for advanced scientific computing research by $ 39 million -- $ 25 million for hardware, $ 5 million for computational research, and $ 9 million for competitive university grants to restore the on-going level of core research in this area that the president 's budget recommended for cuts. by taking the long-term perspective and sustaining support for a highly desirable outcome, the committee is doing its part to ensure that the u.s. reasserts it technological leadership in the area of supercomputing -- a technical capability that underpins our ability to invent the future. laboratory directed research and development ( ldrd ) is an area that grew out of all proportion to its value at the beginning of this decade. this area also raised concerns of financial oversight and the use of federal funds for purposes for which it was not appropriated. as an initial effort to get its arms around this program, which reached an aggregate funding level in fy 2003 of $ 365 million per year, the committee mandated a comprehensive report on ldrd projects from doe and initiated a gao investigation of ldrd. in developing its recommendations for fy 2005, the committee based its guidance and statement of concerns on the results of the gao investigation and what had been learned from reviewing the extensive doe reports. the fy 2005 committee report directs doe to shift to direct requests for ldrd. the president 's budget request for fy 2006, recognizing the concerns of the committee and the constraints on funding, reduced the percentage allowed for ldrd at weapons labs from 6 % to 5 %. the committee is today recommending that ldrd be limited explicitly to $ 250 million in fy 2006, to be allocated to the labs by doe. a quarter billion dollars is a healthy level of funding that could be used to fix many problems in energy research, water infrastructure, etc., so the `` committee [ truly ] recognizes the value of conducting discretionary research at doe 's national laboratories '', but has now brought the funding level for this research back within reason and given it a sense of direction. nuclear weapons is the most sensitive area of activity under the energy and water development appropriation. here, under chairman hobson 's courageous leadership, the denial of funding has been effectively used to chart a safer and more efficient course for the future of our nuclear deterrent. in particular, coming into the fy 2004 appropriations process, the president was asking for funds for a robust nuclear earth penetrator ( rnep ), for studies of new nuclear weapons potentially for new missions, for funds to proceed with preparation of a modern pit facility to manufacture 450 plutonium triggers per year, and a shift to an i8-month readiness posture for a return to underground nuclear testing. taken together, these policy initiatives signaled the house report accompanying the fy 2004 energy and water appropriations bill states, `` the fiscal year 2004 budget request is the second budget request delivered to the committee that is loosely justified on the requirements of the nuclear posture review policy document but lacking a formal plan that specifies the changes to the stockpile reflecting the president 's decision [ on the nuclear weapons stockpile plan ]. '' the committee reduced funding for the rnep to $ 5 million from $ 15 million ( ultimately agreeing to $ 7.5 million in conference ), zeroed funds for proceeding with a modern pit facility, and held the test readiness posture at 24 months. most significantly, $ 4 million of the funds for advanced weapons concepts were fenced so that they could not be spent until the administration delivered a nuclear weapons stockpile plan. without this action, there is doubt that this plan would yet exist. in fy 2005, the committee went further and zeroed funding for the rnep while maintaining the 24-month test readiness posture and continuing to defer the modern pit facility. but, the committee is a constructive influence and seeks to support better policies. at the insistence of the committee, the dangerous advanced concepts approach was scrapped and a reasonable new approach was funded -- the reliable replacement warhead ( rrw ). in fy2006, the committee is solidifying the progress made last year. first, advanced concepts was missing from the president 's request and is essentially no longer under consideration. second, rnep funding is again zero in the committee 's recommendation. third, test readiness posture is held to 24 months. fourth, the rrw concept was included in the president 's request. the committee is working to accelerate the implicit transformation of the u.s. nuclear deterrent stockpile by increasing funds to $ 25 million while slowing programs extending the life of old weapons. the promise of the rrw is that the u.s. will never need to resume nuclear weapons testing and will be able to sustain our deterrent with a smaller, less-expensive complex. in light of these examples where taking a longer-term perspective is showing results, i fully support the efforts in this fy2006 energy and water development appropriation to get all three principal agencies funded in this bill to adopt and communicate 5-year plans for their programs. further, we have long under-invested in the water infrastructure of our nation, and although this year is no exception, the bill undertakes significant efforts to help the u.s. army corps of engineers get effective control over management, particularly fiscal management of projects. management improvements prepare the way for the most effective use of whatever level of funding can be supplied in the future. concentrating funding on high-priority water projects to get them done should significantly improve the overall benefits of investment through the corps and bureau of reclamation, and so, i support this painful approach as well. the chairman and i are taking steps to involve all members of the subcommittee in the oversight of the programs we fund. everyone is being asked to concentrate on two subsets of our work. this also takes the long-term perspective as it will prepare our capable colleagues for future roles as chairs and rankings of appropriations subcommittees while strengthening our current work as appropriators. so, upon reflection, i am pleased with the positive effects of the last three years of energy and water development appropriations bills. far more has been accomplished than the simple funding of government programs and the accommodation of congressional priorities. the nation and the world are better and safer as a result. what a privilege and pleasure to participate! mr. chairman, i reserve the balance of my time.\n"""
        """Output: Oppose\n"""
    ),
    "HanDeSeT": (
        """Sentence: Does my hon. Friend accept that if someone represents a party whose sole interest is to conserve the wealth of people who already have it, it is absolutely inevitable that people who are unfortunately still at the bottom of the pile will remain there as long as that party remains in government?\n"""
        """Output: Positive\n""",

        """Sentence: A phrase in the motion stands out as pretty strong stuff, and I would welcome the right hon. Gentleman's explanation of it. It claims that the "QUOTATION". I thought we had already established across the House that the electorate can both walk and chew gum. I am not entirely sure how the result could be "QUOTATION". I have heard a rumour that the Labour Members are all in a Trident submarine somewhere, sailing around and looking for things.\n"""
        """Output: Negative\n""",

        """Sentence: Does my right hon. Friend agree that while this Government bicker about the structure of the energy companies, my elderly and infirm constituents will be perhaps be dying this winter because of the energy price hikes under that lot over there? Is the Secretary of State aware that the poorest people cannot switch if they are in debt to the company they are with?\n"""
        """Output: Positive\n"""
    ),
    "ParlVote": (
        """Sentence: I beg to move, That the Bill be now read a Second time. Further to that point of order, Mr Speaker. Given the significant financial implications of this decision, have you had any indication from a member of the Treasury ministerial team that they will come to address the House today on the matter?\n"""
        """Output: Positive\n""",

        """Sentence: I beg to move, That this House deplores and opposes the Government’s introduction of the housing benefit under-occupancy penalty; believes it to be unjust and unworkable; notes growing public anger at its introduction; believes that the Government is showing a reckless lack of care and attention to the consequences of its introduction for low-income households affected by disability; further believes that it will adversely affect, amongst others, families of service personnel, foster families and those struggling with the effects of family breakdown; notes that some parts of the UK will be disproportionately hit because of the mismatch between the available social housing stock and the needs of tenants; further notes that according to the Department for Work and Pensions’ Equality Impact Assessment, 63 per cent of the 660,000 claimants affected by the under-occupancy penalty or their partners are disabled; believes that the measure unfairly penalises tenants in rural and inner-city areas; further believes the under-occupancy penalty will fail to meet its stated objectives; and calls on the Government to abandon this policy immediately. I welcome this debate. Unjust, unfair and unnecessary are the words to describe this tax. Households in my constituency will suffer dramatically as a direct result of the introduction of this tax. Indeed, families throughout Scotland and the United Kingdom will suffer the consequences of this tax. In Scotland, we are told that a total of 94,000 tenants living in the social rented sector are considered to be under-occupying their homes. We are told that a total of 75,000-plus tenants are under-occupying by only one bedroom. With still unacceptable levels of unemployment and soaring energy and fuel prices, this measure brings nothing but further bad news for the struggling households across Scotland and the UK. Specialist bodies, including Citizens Advice and Shelter, have already warned that 40,000 households in Scotland alone are likely to run up arrears, with research suggesting that up to 10,000 households could face homelessness. That is on top of tackling the homeless problem we already have in Scotland. The prospect of homelessness is a reflection of the direction in which the Government are taking the country. The bedroom tax is neither a cost-cutting exercise by the Government nor about introducing fair reform to the welfare state; it is nothing more than a tax on the poor and the most vulnerable in communities across the country. Of the 94,000-plus Scots who will be affected by the tax, it is estimated that about 23,000 have a disabled household member, with up to 16,000 households already having some form of aid or necessary adaption in place. Constituents have approached me as they have become aware of how this unfair tax will affect their quality of life. I will give one example, although I could give many others. One lady came to me who previously had shared a home with her daughter. Her daughter has moved on, however, having found employment in another part of the country. The lady has a two-bedroom apartment, but now has one spare room. She has lived in the apartment for more than 20 years. She feels safe there and has good neighbours, but is now scared she will have to move and feels unsettled and frightened at the prospect of being moved across the constituency. My constituent asked me, “Where can I go?” Down-sizing is not an option for her, because in my constituency there is not much one-bedroom accommodation. It is so limited, in fact, that she would be in her 80s before she would be offered one-bedroom accommodation, if she was lucky. Indeed, there is a lack of family accommodation in my constituency, too, so we really need to address the lack of housing and the building of new housing in and around Inverclyde. She wonders, if she were to move to the private sector, whether she would end up in a house of multiple occupancy, where we see that the private sector’s reference to efficiency involves merely pushing people into rooms with shared facilities. By introducing this tax, the Government will do nothing more than cement their unfair and unjust attack on those who need our help the most. I support today’s motion, which calls on them to abandon this unfair, unjust and unnecessary tax, and I add my voice to the list of many here and beyond this place calling on the Government urgently to change course before these reforms hit our constituents hard. I also call on the Scottish Government to act to alleviate the burden of the tax on the people of Scotland. Across Scotland, local authorities already suffering as a direct result of severe cuts to their budgets will find it impossible to minimise the impact of the bedroom tax on many of our constituents and communities.That is an option, but as I have said, the difficulty in my constituency is that we have limited accommodation, and the reclassification of bedrooms is not an option there. I have been working with many agencies in my constituency that have been offering advice to those who think they will be affected by the tax. We have been holding events and information evenings, and people are frightened that they will fall foul of this tax and lose their homes. The Scottish Government could provide more guidance and help to local authorities about how to cope with the impact we know is coming. The bedroom tax is not a Westminster attack on Scotland alone. As we have heard, it is an attack on many constituencies across the UK, and I join others in calling on the Government to abandon this unjust, unfair and very unnecessary tax.\n"""
        """Output: Negative\n""",

        """Sentence: I beg to move, That the Bill be now read a Second time. As Epping forest is in my constituency, this concerns me very much. The right hon Gentleman says that the legislation will not change; but will the money change? If there were more members of the common council interested only in keeping costs down in the centre, with no commitment to open spaces outside the centre, could they, under the proposed voting system, have more power to cut financial support for the open spaces?I am the first listed objector to the Bill, but I presume that others will wish to speak. I am grateful for the way in which the right hon Member for Cities of London and Westminster expressed his support for the Bill. He accepted a number of interventions, and tried to respond to them. At one point, he said that he wanted to get on because he wanted to find out how his speech would end. We are pleased to have heard the end of the speech—but I am not sure that it was worth it. The last time I crossed swords with the right hon Gentleman on a private Bill was when he sponsored a Bill that related to the City of Westminster. I spoke against it for nearly three hours. I do not intend to speak for anywhere near that long tonight, but as I listened to the right hon Gentleman's speech, I recalled that his Bill dealt with a number of businesses in Westminster, such as porn shops. I wondered whether, if the principles being applied to the business community of the City of London—allowing that community all the votes—applied to Westminster, the right hon Gentleman would represent the porn shops. The Bill creates a huge democratic deficit. In fact, "deficit" is a kind description; it is really a democratic negation. My hon Friends will say more about this, but the City of London Labour party has pointed out that the residents' share of the franchise will fall from its current 25 per cent. or thereabouts to less than 10 per cent., and that voters could be nominated by occupiers or agents who might live anywhere: they might not even be United Kingdom citizens, and might not even have set foot in the City of London. The City of London Labour party also points out that there are no guarantees in the Bill for residents, and that their position will be worse. It states: Business interests should not be allowed to override those of residents, as they do now, in matters like planning, traffic and the environment. That is a fair point. Like any other local authority, the court of common council will discuss those local issues: planning, traffic, the environment in the City. It should be the residents—because they are the ones who will be affected by decisions in the main—who exercise that democratic element. Mention was made of representations by Malcolm Matson. I have his letter. Presumably, it was sent to other hon Members.I am surprised at that intervention. The key principle is that residents should be the voters, rather than businesses, which are in many ways absent in terms of business interests; perhaps their headquarters are elsewhere, too. However, some constituencies for this Parliament are very far flung because that is the way in which we achieve an equal number of residents voting. I do not see why all the wards have to be of an equal size in any system. Therefore, I do not think that the hon Gentleman's point applies. Mr. Matson sent a letter on the Bill to hon Members. It said: the Corporation of London wants to extend … the undemocratic 'business vote'. Actually the proposal is even more bizarre. The Bill is the first retreat from the principle of universal suffrage since the Reform Act of 1832 … which began a long march to 'one person one vote'. The Bill will give votes to companies and other bodies according to the rateable value of their offices. The higher the rateable value the more votes they will get. For the first time in a modern western democracy you will be able to buy as many votes in an election for a local authority as you can afford—just keep on adding to your property portfolio! He calls on us to stop "the last rotten borough". That is a good summary of what I politely describe as the democratic deficit. My hon Friends will want to say more about that, but the corporation of London should rethink that aspect. As I have said, there are no guarantees to residents, but nor are there any guarantees to those who enjoy open spaces that are outside the City of London, but which are owned and run by the corporation. My main reason for objecting to the Bill—it is not just the democratic deficit—involves the representations that I have received from the Open Spaces Society. Bernard Selwyn, honorary parliamentary consultant of the society, said that the Bill could affect the character of the court of common council and how the corporation's extra-mural duties are carried out, including, of course, those on Epping forest. He says that some constituencies have open spaces outside the City which the Corporation has acquired and been proudly and conscientiously maintaining for many years. I agree. It has done a relatively good job. He says that those open spaces could be put at risk. Mr. Selwyn adds that the corporation is responsible for the London metropolitan archives, that they should be protected, and that assurances should be given on them as well. He says: Over 40,000 new business votes will be created, but some of the existing votes are expected to be replaced by them so that the total electorate will reduce to more than 54,000 of which some 49,000 will be business voters. He goes on to say: Many of the qualifying bodies will be foreign and have no attachment to London except as a financial centre. While we hope that they will take some pride in the traditions and wider interests of the City, some may only wish to ensure that any money raised by rates or from other sources is not used more than can be avoided for purposes of no benefit to themselves, and they may seek to appoint representatives who have no personal connection with London and can be trusted to vote and even stand as candidates for election to the common council solely to protect the selfish concerns of the body appointing them. That is my concern. If we get more people with that selfish interest, who will be on the common council to stop them spending money on open spaces or to restrict it? The right hon Member for Cities of London and Westminster was right to say that the councillors make the decisions on the Epping forest land for which they are responsible, but it will be councillors with that pressure on them—with that electorate. They may say, "That is something that we are not interested in."I hear what the right hon Gentleman says and I heard what he said about City's cash, which presumably is a separate fund, but he said that councillors take the decisions regarding Epping forest. Those councillors will have an electorate who may not be interested in Epping forest, so that is the main basis of my objection. I look to protect the interests of my constituents who enjoy Epping forest land. I am grateful that the corporation of London has run it relatively well up to now, but I want that to be maintained and improved.I hear the hon Gentleman's point. I have not been critical of the corporation of London. In certain respects, I have—in individual cases where I do not think that it has done a good enough job for my local area—but the general point is that it has run matters well. However, we will have an altered balance of the franchise and businesses. Some will have foreign interests, as the Open Spaces Society has said, little interest in the City and even less interest in the area outside the City for which the corporation is responsible. The hon Gentleman may be right in suggesting that the policy will not change. I certainly hope that that is the case, but by changing the franchise it puts at risk that commitment. That is why I object—to ensure that that commitment is absolutely maintained. That is my main concern.I appreciate the hon Lady's point, but the Open Spaces Society does not agree with it. The society stated that the businesses that will now have the vote may seek to appoint representatives who have no personal connection with London and can be trusted to vote and even stand as candidates for election to the common council solely to protect the selfish concerns of the body appointing them. That is a very real concern to the Open Spaces Society. I am therefore not convinced by the point made by the hon Member for Beckenham —that the new representatives will be dead keen to live in the City, to be active there and to work 100 per cent. in the City's best interests. I am certainly not convinced that they will automatically be interested in the City's functions outside the square mile. I also suspect that they will not be much interested in the Epping forest land in my constituency—but I am. I am very concerned about it, as are my constituents. We want to ensure that we receive assurances that the current commitment will be maintained and even increased.I am grateful to my hon Friend for clarifying the point. The Open Spaces Society points out that the corporation is responsible for the management and conservation of more than 10,000 acres—more than 15 square miles—of open space. Those spaces are paid for out of the City's cash account—the private fund which has been built over the centuries and was mentioned by the right hon Member for Cities of London and Westminster. Mr. Selwyn said: However, we regret that no accounts of this fund are published although the expenditure has to be approved by the common council and the duties are subject to statutory requirements. I heard the comments made by the right hon Member for Cities of London and Westminster on annual estimates. Although that concession is welcome, it is wrong for there to be such secrecy surrounding details of the fund, which is so important to Londoners. The matter should be opened up. I should like to provide an example—in which my hon Friend the Minister for London and Construction might be quite interested—of the effects of the secrecy. The Government have a new deal policy, in which one option for young people is to serve on an environmental task force, doing environmental work. The City of London corporation should want to assist the Government in the project. Perhaps we should expect the corporation to help financially with the project. However, the corporation might say, "We don't have the funds to do it", or, "We're not really interested in helping the Government or in getting young people into training and working on an environmental task force." All the time, it could be sitting on top of secret funds totalling millions of pounds, which could be helping young people and the Government's policy. That is only one example of why there should be accountability of and transparency in City's cash. The public might have some interest—I take the point, Mr. Deputy Speaker. I am saying only that there should be some transparency and accountability about City's cash. The new representatives, who will be elected on the basis of the new franchise, might say, "We don't have the money to maintain current open-spaces policies and commitments", whereas in secret they will have the money. I think that people should know the exact situation. I should like to deal with a few local issues, if my hon Friends will allow me to do so—I know that they would like to return to the main issue of the democratic deficit. Nevertheless, there are a few constituency matters in relation to the open spaces and the corporation's policies. I should like to mention some of them, not least because I might get them in the local newspapers and please the local residents. The Hollow pond is run by the City of London corporation, at Whipps Cross, and is heavily used. Parts of it have become quite barren, and it requires proper replanting. There should be a better policy to that end. The land is used very heavily, proportionately more than other parts of Epping forest. Moreover, there has been much work on the M11 link road in the neighbouring area.I do apologise, Mr. Deputy Speaker. In his reply, I should like to hear from the right hon Member for Cities of London and Westminster how the new franchise and election of a new common council will impact on those local issues. That information would interest my constituents, who clearly want the Hollow pond at Whipps Cross to be maintained and improved. The pond that has dried up and was just left at the junction—I shall not pursue the matter further today, but I will pursue it in writing with the corporation, as it affects my constituents—such as an individual who wants, for example, to locate a bench with a plaque to his mother, but has been turned down.I do apologise, Mr. Deputy Speaker. I shall not do it again. All these matters show the importance to my area—and many other areas of London—of maintaining the corporation's open spaces commitment. I have, up to now, had no quibble with the policy—other than those little individual ones, about which I shall be writing. However, the little matters also clarify the general issue, which is that we want the common council to maintain and improve the policy. The assurances that I seek are therefore vital. I remain concerned that the franchise change will worsen the situation for those who, like my constituents and others, enjoy open spaces. It is also important to have greater accountability.\n"""
        """Output: Positive\n"""
    )
}

## ParlVote

In [ ]:
ParlVote_path = folder + "/gpt-4.1-nano/binary_classification/ParlVote/"
os.makedirs(ParlVote_path, exist_ok=True)

In [ ]:
print(INSTRUCTION_PROMPT['sentiment_analysis'])

You are a sentiment classification assistant. Classify the sentences using the following labels: positive, negative.

In [ ]:
print(EXAMPLES['ParlVote'])

('Sentence: I beg to move, That the Bill be now read a Second time. Further to that point of order, Mr Speaker. Given the significant financial implications of this decision, have you had any indication from a member of the Treasury ministerial team that they will come to address the House today on the matter?\nOutput: Positive\n', 'Sentence: I beg to move, That this House deplores and opposes the Government’s introduction of the housing benefit under-occupancy penalty; believes it to be unjust and unworkable; notes growing public anger at its introduction; believes that the Government is showing a reckless lack of care and attention to the consequences of its introduction for low-income households affected by disability; further believes that it will adversely affect, amongst others, families of service personnel, foster families and those struggling with the effects of family breakdown; notes that some parts of the UK will be disproportionately hit because of the mismatch between the available social housing stock and the needs of tenants; further notes that according to the Department for Work and Pensions’ Equality Impact Assessment, 63 per cent of the 660,000 claimants affected by the under-occupancy penalty or their partners are disabled; believes that the measure unfairly penalises tenants in rural and inner-city areas; further believes the under-occupancy penalty will fail to meet its stated objectives; and calls on the Government to abandon this policy immediately. I welcome this debate. Unjust, unfair and unnecessary are the words to describe this tax. Households in my constituency will suffer dramatically as a direct result of the introduction of this tax. Indeed, families throughout Scotland and the United Kingdom will suffer the consequences of this tax. In Scotland, we are told that a total of 94,000 tenants living in the social rented sector are considered to be under-occupying their homes. We are told that a total of 75,000-plus tenants are under-occupying by only one bedroom. With still unacceptable levels of unemployment and soaring energy and fuel prices, this measure brings nothing but further bad news for the struggling households across Scotland and the UK. Specialist bodies, including Citizens Advice and Shelter, have already warned that 40,000 households in Scotland alone are likely to run up arrears, with research suggesting that up to 10,000 households could face homelessness. That is on top of tackling the homeless problem we already have in Scotland. The prospect of homelessness is a reflection of the direction in which the Government are taking the country. The bedroom tax is neither a cost-cutting exercise by the Government nor about introducing fair reform to the welfare state; it is nothing more than a tax on the poor and the most vulnerable in communities across the country. Of the 94,000-plus Scots who will be affected by the tax, it is estimated that about 23,000 have a disabled household member, with up to 16,000 households already having some form of aid or necessary adaption in place. Constituents have approached me as they have become aware of how this unfair tax will affect their quality of life. I will give one example, although I could give many others. One lady came to me who previously had shared a home with her daughter. Her daughter has moved on, however, having found employment in another part of the country. The lady has a two-bedroom apartment, but now has one spare room. She has lived in the apartment for more than 20 years. She feels safe there and has good neighbours, but is now scared she will have to move and feels unsettled and frightened at the prospect of being moved across the constituency. My constituent asked me, “Where can I go?” Down-sizing is not an option for her, because in my constituency there is not much one-bedroom accommodation. It is so limited, in fact, that she would be in her 80s before she would be offered one-bedroom accommodation, if she was lucky. Indeed, there is a lack of family accommodation in my constituency, too, so we really need to address the lack of housing and the building of new housing in and around Inverclyde. She wonders, if she were to move to the private sector, whether she would end up in a house of multiple occupancy, where we see that the private sector’s reference to efficiency involves merely pushing people into rooms with shared facilities. By introducing this tax, the Government will do nothing more than cement their unfair and unjust attack on those who need our help the most. I support today’s motion, which calls on them to abandon this unfair, unjust and unnecessary tax, and I add my voice to the list of many here and beyond this place calling on the Government urgently to change course before these reforms hit our constituents hard. I also call on the Scottish Government to act to alleviate the burden of the tax on the people of Scotland. Across Scotland, local authorities already suffering as a direct result of severe cuts to their budgets will find it impossible to minimise the impact of the bedroom tax on many of our constituents and communities.That is an option, but as I have said, the difficulty in my constituency is that we have limited accommodation, and the reclassification of bedrooms is not an option there. I have been working with many agencies in my constituency that have been offering advice to those who think they will be affected by the tax. We have been holding events and information evenings, and people are frightened that they will fall foul of this tax and lose their homes. The Scottish Government could provide more guidance and help to local authorities about how to cope with the impact we know is coming. The bedroom tax is not a Westminster attack on Scotland alone. As we have heard, it is an attack on many constituencies across the UK, and I join others in calling on the Government to abandon this unjust, unfair and very unnecessary tax.\nOutput: Negative\n', 'Sentence: I beg to move, That the Bill be now read a Second time. As Epping forest is in my constituency, this concerns me very much. The right hon Gentleman says that the legislation will not change; but will the money change? If there were more members of the common council interested only in keeping costs down in the centre, with no commitment to open spaces outside the centre, could they, under the proposed voting system, have more power to cut financial support for the open spaces?I am the first listed objector to the Bill, but I presume that others will wish to speak. I am grateful for the way in which the right hon Member for Cities of London and Westminster expressed his support for the Bill. He accepted a number of interventions, and tried to respond to them. At one point, he said that he wanted to get on because he wanted to find out how his speech would end. We are pleased to have heard the end of the speech—but I am not sure that it was worth it. The last time I crossed swords with the right hon Gentleman on a private Bill was when he sponsored a Bill that related to the City of Westminster. I spoke against it for nearly three hours. I do not intend to speak for anywhere near that long tonight, but as I listened to the right hon Gentleman\'s speech, I recalled that his Bill dealt with a number of businesses in Westminster, such as porn shops. I wondered whether, if the principles being applied to the business community of the City of London—allowing that community all the votes—applied to Westminster, the right hon Gentleman would represent the porn shops. The Bill creates a huge democratic deficit. In fact, "deficit" is a kind description; it is really a democratic negation. My hon Friends will say more about this, but the City of London Labour party has pointed out that the residents\' share of the franchise will fall from its current 25 per cent. or thereabouts to less than 10 per cent., and that voters could be nominated by occupiers or agents who might live anywhere: they might not even be United Kingdom citizens, and might not even have set foot in the City of London. The City of London Labour party also points out that there are no guarantees in the Bill for residents, and that their position will be worse. It states: Business interests should not be allowed to override those of residents, as they do now, in matters like planning, traffic and the environment. That is a fair point. Like any other local authority, the court of common council will discuss those local issues: planning, traffic, the environment in the City. It should be the residents—because they are the ones who will be affected by decisions in the main—who exercise that democratic element. Mention was made of representations by Malcolm Matson. I have his letter. Presumably, it was sent to other hon Members.I am surprised at that intervention. The key principle is that residents should be the voters, rather than businesses, which are in many ways absent in terms of business interests; perhaps their headquarters are elsewhere, too. However, some constituencies for this Parliament are very far flung because that is the way in which we achieve an equal number of residents voting. I do not see why all the wards have to be of an equal size in any system. Therefore, I do not think that the hon Gentleman\'s point applies. Mr. Matson sent a letter on the Bill to hon Members. It said: the Corporation of London wants to extend … the undemocratic \'business vote\'. Actually the proposal is even more bizarre. The Bill is the first retreat from the principle of universal suffrage since the Reform Act of 1832 … which began a long march to \'one person one vote\'. The Bill will give votes to companies and other bodies according to the rateable value of their offices. The higher the rateable value the more votes they will get. For the first time in a modern western democracy you will be able to buy as many votes in an election for a local authority as you can afford—just keep on adding to your property portfolio! He calls on us to stop "the last rotten borough". That is a good summary of what I politely describe as the democratic deficit. My hon Friends will want to say more about that, but the corporation of London should rethink that aspect. As I have said, there are no guarantees to residents, but nor are there any guarantees to those who enjoy open spaces that are outside the City of London, but which are owned and run by the corporation. My main reason for objecting to the Bill—it is not just the democratic deficit—involves the representations that I have received from the Open Spaces Society. Bernard Selwyn, honorary parliamentary consultant of the society, said that the Bill could affect the character of the court of common council and how the corporation\'s extra-mural duties are carried out, including, of course, those on Epping forest. He says that some constituencies have open spaces outside the City which the Corporation has acquired and been proudly and conscientiously maintaining for many years. I agree. It has done a relatively good job. He says that those open spaces could be put at risk. Mr. Selwyn adds that the corporation is responsible for the London metropolitan archives, that they should be protected, and that assurances should be given on them as well. He says: Over 40,000 new business votes will be created, but some of the existing votes are expected to be replaced by them so that the total electorate will reduce to more than 54,000 of which some 49,000 will be business voters. He goes on to say: Many of the qualifying bodies will be foreign and have no attachment to London except as a financial centre. While we hope that they will take some pride in the traditions and wider interests of the City, some may only wish to ensure that any money raised by rates or from other sources is not used more than can be avoided for purposes of no benefit to themselves, and they may seek to appoint representatives who have no personal connection with London and can be trusted to vote and even stand as candidates for election to the common council solely to protect the selfish concerns of the body appointing them. That is my concern. If we get more people with that selfish interest, who will be on the common council to stop them spending money on open spaces or to restrict it? The right hon Member for Cities of London and Westminster was right to say that the councillors make the decisions on the Epping forest land for which they are responsible, but it will be councillors with that pressure on them—with that electorate. They may say, "That is something that we are not interested in."I hear what the right hon Gentleman says and I heard what he said about City\'s cash, which presumably is a separate fund, but he said that councillors take the decisions regarding Epping forest. Those councillors will have an electorate who may not be interested in Epping forest, so that is the main basis of my objection. I look to protect the interests of my constituents who enjoy Epping forest land. I am grateful that the corporation of London has run it relatively well up to now, but I want that to be maintained and improved.I hear the hon Gentleman\'s point. I have not been critical of the corporation of London. In certain respects, I have—in individual cases where I do not think that it has done a good enough job for my local area—but the general point is that it has run matters well. However, we will have an altered balance of the franchise and businesses. Some will have foreign interests, as the Open Spaces Society has said, little interest in the City and even less interest in the area outside the City for which the corporation is responsible. The hon Gentleman may be right in suggesting that the policy will not change. I certainly hope that that is the case, but by changing the franchise it puts at risk that commitment. That is why I object—to ensure that that commitment is absolutely maintained. That is my main concern.I appreciate the hon Lady\'s point, but the Open Spaces Society does not agree with it. The society stated that the businesses that will now have the vote may seek to appoint representatives who have no personal connection with London and can be trusted to vote and even stand as candidates for election to the common council solely to protect the selfish concerns of the body appointing them. That is a very real concern to the Open Spaces Society. I am therefore not convinced by the point made by the hon Member for Beckenham —that the new representatives will be dead keen to live in the City, to be active there and to work 100 per cent. in the City\'s best interests. I am certainly not convinced that they will automatically be interested in the City\'s functions outside the square mile. I also suspect that they will not be much interested in the Epping forest land in my constituency—but I am. I am very concerned about it, as are my constituents. We want to ensure that we receive assurances that the current commitment will be maintained and even increased.I am grateful to my hon Friend for clarifying the point. The Open Spaces Society points out that the corporation is responsible for the management and conservation of more than 10,000 acres—more than 15 square miles—of open space. Those spaces are paid for out of the City\'s cash account—the private fund which has been built over the centuries and was mentioned by the right hon Member for Cities of London and Westminster. Mr. Selwyn said: However, we regret that no accounts of this fund are published although the expenditure has to be approved by the common council and the duties are subject to statutory requirements. I heard the comments made by the right hon Member for Cities of London and Westminster on annual estimates. Although that concession is welcome, it is wrong for there to be such secrecy surrounding details of the fund, which is so important to Londoners. The matter should be opened up. I should like to provide an example—in which my hon Friend the Minister for London and Construction might be quite interested—of the effects of the secrecy. The Government have a new deal policy, in which one option for young people is to serve on an environmental task force, doing environmental work. The City of London corporation should want to assist the Government in the project. Perhaps we should expect the corporation to help financially with the project. However, the corporation might say, "We don\'t have the funds to do it", or, "We\'re not really interested in helping the Government or in getting young people into training and working on an environmental task force." All the time, it could be sitting on top of secret funds totalling millions of pounds, which could be helping young people and the Government\'s policy. That is only one example of why there should be accountability of and transparency in City\'s cash. The public might have some interest—I take the point, Mr. Deputy Speaker. I am saying only that there should be some transparency and accountability about City\'s cash. The new representatives, who will be elected on the basis of the new franchise, might say, "We don\'t have the money to maintain current open-spaces policies and commitments", whereas in secret they will have the money. I think that people should know the exact situation. I should like to deal with a few local issues, if my hon Friends will allow me to do so—I know that they would like to return to the main issue of the democratic deficit. Nevertheless, there are a few constituency matters in relation to the open spaces and the corporation\'s policies. I should like to mention some of them, not least because I might get them in the local newspapers and please the local residents. The Hollow pond is run by the City of London corporation, at Whipps Cross, and is heavily used. Parts of it have become quite barren, and it requires proper replanting. There should be a better policy to that end. The land is used very heavily, proportionately more than other parts of Epping forest. Moreover, there has been much work on the M11 link road in the neighbouring area.I do apologise, Mr. Deputy Speaker. In his reply, I should like to hear from the right hon Member for Cities of London and Westminster how the new franchise and election of a new common council will impact on those local issues. That information would interest my constituents, who clearly want the Hollow pond at Whipps Cross to be maintained and improved. The pond that has dried up and was just left at the junction—I shall not pursue the matter further today, but I will pursue it in writing with the corporation, as it affects my constituents—such as an individual who wants, for example, to locate a bench with a plaque to his mother, but has been turned down.I do apologise, Mr. Deputy Speaker. I shall not do it again. All these matters show the importance to my area—and many other areas of London—of maintaining the corporation\'s open spaces commitment. I have, up to now, had no quibble with the policy—other than those little individual ones, about which I shall be writing. However, the little matters also clarify the general issue, which is that we want the common council to maintain and improve the policy. The assurances that I seek are therefore vital. I remain concerned that the franchise change will worsen the situation for those who, like my constituents and others, enjoy open spaces. It is also important to have greater accountability.\nOutput: Positive\n')

In [ ]:
dataset = pd.read_csv(f"{folder}/binary_classification/ParlVote/test.csv")

In [ ]:
dataset.head(2)

   label                                               text label_value
0      0  I beg to move amendment No. 8, in page 4, line...    Negative
1      1  I beg to move, That this House notes the overp...    Positive

### Zero-Shot

In [ ]:
results = ask_gpt_classification(dataset, INSTRUCTION_PROMPT['sentiment_analysis'])
pd.DataFrame(results).to_csv(f"{ParlVote_path}/zero_shot_binary_classification.csv", index=False)

Dataset label                                                          0
text           I beg to move amendment No. 8, in page 4, line...
label_value                                             Negative
Name: 0, dtype: object


Instructions You are a sentiment classification assistant. Classify the sentences using the following labels: positive, negative.

 38%|███▊      | 1279/3345 [07:12<11:38,  2.96it/s]

KeyboardInterrupt:

In [ ]:
results[0]

### Few-Shot

In [ ]:
instuctions_examples = f"{INSTRUCTION_PROMPT['sentiment_analysis']}\n{EXAMPLES['ParlVote']}"
print(instuctions_examples)

In [ ]:
results = ask_gpt_classification(dataset, instuctions_examples)
pd.DataFrame(results).to_csv(f"{ParlVote_path}/few_shot_binary_classification.csv", index=False)

In [ ]:
results[0]

## HanDeSeT

In [ ]:
HanDeSeT_path = folder + "/gpt-4.1-nano/binary_classification/HanDeSeT/"
os.makedirs(HanDeSeT_path, exist_ok=True)

In [ ]:
print(INSTRUCTION_PROMPT['sentiment_analysis'])

In [ ]:
print(EXAMPLES['HanDeSeT'])

In [ ]:
dataset = pd.read_csv(f"{folder}/binary_classification/HanDeSeT/test.csv")

In [ ]:
dataset.head(2)

### Zero-Shot

In [ ]:
results = ask_gpt_classification(dataset, INSTRUCTION_PROMPT['sentiment_analysis'])
pd.DataFrame(results).to_csv(f"{HanDeSeT_path}/zero_shot_binary_classification.csv", index=False)

In [ ]:
results[0]

### Few-Shot

In [ ]:
instuctions_examples = f"{INSTRUCTION_PROMPT['sentiment_analysis']}\n{EXAMPLES['HanDeSeT']}"
print(instuctions_examples)

In [ ]:
results = ask_gpt_classification(dataset, instuctions_examples)
pd.DataFrame(results).to_csv(f"{HanDeSeT_path}/few_shot_binary_classification.csv", index=False)

## ConVote

In [ ]:
ConVote_path = folder + "/gpt-4.1-nano/binary_classification/ConVote/"
os.makedirs(ConVote_path, exist_ok=True)

In [ ]:
print(INSTRUCTION_PROMPT['stance_detection'])

In [ ]:
print(EXAMPLES['ConVote'])

In [ ]:
dataset = pd.read_csv(f"{folder}/binary_classification/ConVote/test.csv")

In [ ]:
dataset.head(2)

### Zero-Shot

In [ ]:
results = ask_gpt_classification(dataset, INSTRUCTION_PROMPT['stance_detection'])
pd.DataFrame(results).to_csv(f"{ConVote_path}/zero_shot_binary_classification.csv", index=False)

In [ ]:
results[0]

### Few-Shot

In [ ]:
instuctions_examples = f"{INSTRUCTION_PROMPT['stance_detection']}\n{EXAMPLES['ConVote']}"
print(instuctions_examples)

In [ ]:
results = ask_gpt_classification(dataset, instuctions_examples)
pd.DataFrame(results).to_csv(f"{ConVote_path}/few_shot_binary_classification.csv", index=False)

## AusHansard

In [ ]:
AusHansard_path = folder + "/gpt-4.1-nano/binary_classification/AusHansard/"
os.makedirs(AusHansard_path, exist_ok=True)

In [ ]:
print(INSTRUCTION_PROMPT['stance_detection'])

In [ ]:
print(EXAMPLES['AusHansard'])

In [ ]:
dataset = pd.read_csv(f"{folder}/binary_classification/AusHansard/test.csv")

In [ ]:
dataset.head(2)

### Zero-Shot

In [ ]:
results = ask_gpt_classification(dataset, INSTRUCTION_PROMPT['stance_detection'])
pd.DataFrame(results).to_csv(f"{AusHansard_path}/zero_shot_binary_classification.csv", index=False)

In [ ]:
results[0]

### Few-Shot

In [ ]:
instuctions_examples = f"{INSTRUCTION_PROMPT['stance_detection']}\n{EXAMPLES['AusHansard']}"
print(instuctions_examples)

In [ ]:
results = ask_gpt_classification(dataset, instuctions_examples)
pd.DataFrame(results).to_csv(f"{AusHansard_path}/few_shot_binary_classification.csv", index=False)

In [ ]:
results[0]

# MULTI CLASS CLASSIFICATION

In [13]:
INSTRUCTION_PROMPT = {
    "ElecDeb60to20": (
        "You are a relation classification assistant. Classify the sentences separated by [SEP] using the labels: support, attack, no_relation\n\n"
    ),
    "ArgUNSC": (
        "You are a relation classification assistant. Classify the sentences separated by [SEP] using the labels: support, attack, no_relation\n\n"
    ),

    "MotionPolicyPreference": (
        "You are a motion policy preference classification assistant. Classify the motions using the following labels:"
        "Military: Positive, Military: Negative, Peace, Internationalism: Positive, "
        "European Union: Positive, European Union: Negative, Human Rights, "
        "Direct Democracy: Positive, Constitutionalism: Positive, Constitutionalism: Negative, "
        "Decentralisation: Positive, Centralisation: Positive, Governative and Administrative Efficiency, "
        "Political Corruption, Political Authority: Party, Free Market Economy, Incentives: Positive, "
        "Market Regulation, Economic Planning, Corporatism/Mixed Economy, Protectionism: Negative, "
        "Economic Goals, Keynesian Demand Management, Economic Growth: Positive, "
        "Technology and Infrastructure: Positive, Controlled Economy, Nationalisation, "
        "Economic Orthodoxy, Environmental Protection, Culture: Positive, Equality: Positive, "
        "Welfare State Expansion, Welfare State Limitation, Education Expansion, "
        "National Way of Life: Positive, National Way of Life: Negative, "
        "Law and Order: Positive, Civic Mindedness: Positive, Multiculturalism: Positive, "
        "Multiculturalism: Negative, Labour Groups: Positive, Agriculture and Farmers: Positive, "
        "Middle Class and Professional Groups, Underprivileged Minority Groups, "
        "Non-economic Demographic Groups\n\n"
    ),

    "ParlVote+": (
        "You are a motion policy preference classification assistant. Classify the motions using the following labels:"
        "Military: Positive, Military: Negative, Peace, European Union: Positive, "
        "European Union: Negative, Human Rights, Direct Democracy: Positive, "
        "Constitutionalism: Positive, Constitutionalism: Negative, Decentralisation: Positive, "
        "Centralisation: Positive, Political Corruption, Political Authority: Party, "
        "Political Authority: Personal, Free Market Economy, Incentives: Positive, "
        "Market Regulation, Technology: Positive, Nationalisation, Environmental Protection, "
        "Equality: Positive, Welfare State Expansion, Welfare State Limitation, "
        "Education Expansion, Education Limitation, Immigration: Negative, Immigration: Positive, "
        "Traditional Morality: Positive, Traditional Morality: Negative, "
        "Law and Order: Positive, Law and Order: Negative, "
        "Labour Groups: Positive, Labour Groups: Negative, "
        "Underprivileged Minority Groups\n\n"
    ),
}

In [2]:
EXAMPLES = {
    "ElecDeb60to20": [
        "Sentence: we have avoided surrender of principle or territory at the conference table [SEP] In the past seven years, in President Eisenhower's Administration, this situation has been reversed\n"
        "Output: support\n",

        "Sentence: although we are today, as Senator Kennedy has admitted, the strongest nation in the world militarily [SEP] we must increase our strength\n"
        "Output: attack\n",

        "Sentence: You know, people said it was a big risk at that time [SEP] when there was a crisis involving the Mexican peso, again, President Bill Clinton showed bold and dynamic leadership\n"
        "Output: no_relation\n",
    ],

    "MotionPolicyPreference": [
        "Sentence: expresses concern about the impact of the Care Records Service on patient confidentiality\n"
        "Output: Human Rights\n",

        "Sentence: condemns the pursuit of uniformity at the expense of diversity\n"
        "Output: Equality: Positive\n",

        "Sentence: observes that the Health and Safety Act 1974 made it a legal necessity for workplaces to train someone in medical first aid\n"
        "Output: Labour Groups: Positive\n",
    ],

    "ParlVote+": [
        "Sentence: Please stick to the motion.I congratulate the right hon Member for Birkenhead  and thank the Backbench Business Committee for granting us this very timely debate to reconsider the impact on the lowest-paid workers of the proposed changes to tax credits and to call for the Government to bring mitigation proposals to this House. Early next year it is the centenary of the birth of Harold Wilson. That Huddersfield lad coined the phrase, “A week is a long time in politics.” A lot of ermine and a flood of emails have flowed under the bridge since I signed this motion last week. I want to make it clear from the start that I absolutely support the Chancellor in getting Britain to live within its means. In fact, I often suggest to folk back home in Yorkshire who are talking about austerity that we should replace it with the phrase “living within our means”. That brings a whole new meaning to the campaign slogan “anti-living within your means”. Since last week, many constituents have echoed my position. To follow the style of the Leader of the Opposition, Martin from Holme Valley says that he agrees with the shift from tax credits to increased pay but shares my concern about the transitional impact of the changes. Bob from Salendine Nook says that he understands the point I make about employers underpaying staff and agrees with me on the need to reconsider the pace of change. Nicola from Oakes says that she agrees that the tax credits system is imperfect, as is the whole benefits system. She says that she would be better off financially reducing her hours, as she works full time, and that a change to the system needs to be implemented. She says that she feels she is currently being punished by the benefits system for trying to bring home more money by working her way up, and that a single person on income support, disability living allowance, housing benefit and other benefits could, in effect, be paid more in benefits than she brings home, including with her tax credits, to support a family. Dorothy from Marsden says that she fully understands the need for reform. As the motion clearly states, this about the pace and the impact on the lowest-paid workers. I firmly believe that work should always pay. People should always be better off in a job than on benefits. I say that as someone who did not go to university. When I left school, I did a succession of low-paid, part-time jobs before I joined the Royal Air Force at the age of 19, worked my way up, and travelled the world. I am proud that since 2010 unemployment is down by 51% in my constituency. I am proud that youth unemployment is down by more than half. I am proud that there is a net increase of 170 new businesses and there have been over 4,700 new apprenticeship starts. I am proud to say that I have just taken on my first apprentice and that I am paying him the living wage. On Friday 20 November I will hold my latest jobs fair at Holmfirth civic hall, where over 30 local businesses and organisations will be offering quality jobs and apprenticeships. We must build a low-tax, low-welfare, high-wage economy. As a compassionate Conservative, I want to live in a country where everyone has the opportunity of a decent, well-paid job. So let us crack on with it, and let us stand up for working people. I welcome the Chancellor’s announcement that he will lessen the impact on families and will set out these plans in the autumn statement. I hope that he and his Treasury boffins will be listening very carefully to the various suggestions, some of them very inventive, for transitional arrangements. Let us show that Britain can live within its means while, most importantly, looking after the most vulnerable and supporting those who go out and work every day. Several hon Members rose—\n"
        "Output: Welfare State Expansion\n",

        """Sentence: I had begun to doubt myself. Having intended to speak in favour of amendment No. 279, I began to have my doubts when I heard Labour Members question my hon Friend the Member for Westmorland and Lonsdale . However, I have now returned to my former opinion℄even more starkly℄having heard the hon Member for Edinburgh, West , who raises every fear that I had about the Bill. The Bill states: Statutory functions may be conferred on the Scottish Ministers".  Having read the Bill in its totality, I would welcome the addition of the rider: "but not in so far as they might affect England, Wales and Northern Ireland." That seems entirely proper, and everything that the hon Member for Edinburgh, West has said confirms that. It is difficult to confer a general duty on a Member of Parliament to hold the Executive to account when there remains a possibility℄albeit theoretical℄that the Executive are not accountable to him. That is a theoretical argument, but there is a more important argument which has more resonance in terms of public opinion. I would say to the hon and learned Member for Edinburgh, Pentlands  that, in these matters, perceptions are even more important than reality. Even now, I am approached by constituents at meetings and in public℄in a most unwelcome, unsolicited and unhelpful way℄who share their observation that, "Now Scotland is getting its own Parliament, isn't it awful and awkward that we have a Government entirely dominated by Scottish Members?" I have to point out to them that their concern is quite illegitimate and that they have no proper grievance. Those who sit on the Treasury Bench have a mandate and are very properly there. I should hate it if a situation arose in which my constituents had a legitimate grievance, and amendment No. 279 would prevent that from happening. As said, perception is important in these respects, and the Committee has a duty to remove such sources of conflict and public discontent..\n"""
        "Output: Centralisation: Positive\n",

        """Sentence: I speak on behalf of those who are prepared to accept the Government's proposals—or to be bought off, as the hon Member for Kingston and Surbiton  suggests. I shall explain why. I am pleased that we are having this debate. My direct involvement in this Bill began when I chaired the Joint Scrutiny Committee—with the Home Affairs Committee and the Work and Pensions Committee—on it. Perhaps I should not say so as the Chairman of that Committee, but its work showed the value of draft scrutiny, because many other issues were sorted out before the Bill was introduced. I wish that we did that more often. The issue before the House is one of the few outstanding issues on which the Committee took a different view from the Government on what should be in the Bill. I argued the same case on Report and I have seen amendments passed in the other place, and I welcome the efforts that the Minister has made to get us to where we are tonight. I know—and from comments that have been made, the House knows—how much work it has required from him to get us to this position. For some people, who have followed the Bill from the perspective of losing friends or relatives in accidents such as the Marchioness disaster or train crashes, this subject appears to be a late entry into the Bill, which has given rise to concerns that the Bill itself may be threatened by our desire to extend it to cover custody. The Minister has done his best to get us to a position where the principle of covering deaths in custody is covered by the Bill without putting it under threat. He deserves the thanks of the House for that. Why am I prepared to accept this when, from the amendments that I tabled last time, it is evident that my preference would be a straightforward amendment to the Bill? The answer is that I believe that the amendment the Minister has tabled today will trigger a process that will lead inexorably to deaths in custody being brought within the scope of the Bill. Whether or not he feels he has the freedom tonight to talk about time scales, the fact is that the process, once started, will be unstoppable. The Minister is also responsible for prisons, and I do not believe that when he next meets the director of the Prison Service, he will say to him, "I've got you out of that problem for the next few years, so I wouldn't worry about it if I were you. Instead, the Minister will say that deaths in custody could be included at any time and the Prison Service will have to be ready for that. Many of us would accept that, even if the provision had been on the face of the Bill, some delay in commencement would have been necessary to get the Prison Service to face up to its responsibilities in a way that it has not done so far. That is how the conversation will go. I do not wish to prejudge inquests in the pipeline, but there are some whose verdicts could make it untenable for the Government not to bring forward the resolution necessary under the amendment, however much the Government may prefer to consider the statutory ombudsman first and the forum next. I fear that there will be other inquests beyond those. That is the historical record, and the result will be that it will not be tenable for this or any Government not to enact this change. I believe that those of us who, a year or so ago, set out to bring this matter within the scope of the Bill are going to achieve our objective tonight. It is for that reason that I recommend to the House that we support the Government's proposal, which takes us a long way forward. As ever when Governments are asked to take a very different position from the one that they started with, there is a certain choreography about how such matters must be handled, but the amendment in lieu in the end gets us to where we want to go and delivers the result that we want. I am therefore very grateful to the Minister for everything that he has done.\n"""
        "Output: Law and Order: Positive\n",
    ],
    "ArgUNSC": [
        "Sentence: the facilitation of contacts between the warring parties, are a positive sign but they are not enough. [SEP] we will remain vigilant to ensure that support for the separatists finally ceases, that the weakening of the State and the rule of law is checked, and that the ceasefire is fully respected.\n"
        "Output: no_relation\n",

        "Sentence: the separatists trained, supplied and supported by  Russia are launching a full-scale attack on the strategic city of Debaltseve, inside Ukrainian-controlled territory, in blatant violation of the 19 September Minsk ceasefire lines, in an attemp to gain control of a significant rail juncture. [SEP] It is dangerous because Russia continues to train and equip separatists with heavy weapons and to fight by their side, in flagrant violation of the September Minsk agreement, Ukrainian sovereignty and international law.\n"
        "Output: support\n",

        "Sentence: I would repeat that Russia would never refuse to implement any useful document agreed upon during the crisis, including the 21 February agreement. [SEP] Regarding what one colleague said, that Russia is refusing to implement the 17 April Geneva statement\n"
        "Output: attack\n"
    ]
}

## ArgUNSC

In [ ]:
ArgUNSC_relations_path = folder + "/gpt-4.1-nano/multi_class_classification/ArgUNSC/"
os.makedirs(ArgUNSC_relations_path, exist_ok=True)

In [10]:
dataset = pd.read_csv(folder + "/multi_class_classification/ArgUNSC/test.csv")

In [11]:
dataset.head()

                                                text  label  label_value
0  There is no doubt that the flow of heavy weapo...      1  no_relation
1  We appeal to all those in a position to influe...      1  no_relation
2  We have reached such moment. [SEP] Let this tr...      2      support
3  Among this, we have heard the usual pattern of...      1  no_relation
4  "The bloody murder of dozens of civilians and ...      1  no_relation

### Zero-Shot

In [ ]:
results = ask_gpt_classification(dataset, INSTRUCTION_PROMPT['ArgUNSC'])
pd.DataFrame(results).to_csv(f"{ArgUNSC_relations_path}/zero_shot_multi_class_classification.csv", index=False)

In [ ]:
results[0]

### Few-Shot

In [14]:
instuctions_examples = f"{INSTRUCTION_PROMPT['ArgUNSC']}\n{EXAMPLES['ArgUNSC']}"
print(instuctions_examples)

You are a relation classification assistant. Classify the sentences separated by [SEP] using the labels: support, attack, no_relation


['Sentence: the facilitation of contacts between the warring parties, are a positive sign but they are not enough. [SEP] we will remain vigilant to ensure that support for the separatists finally ceases, that the weakening of the State and the rule of law is checked, and that the ceasefire is fully respected.\nOutput: no_relation\n', 'Sentence: the separatists trained, supplied and supported by  Russia are launching a full-scale attack on the strategic city of Debaltseve, inside Ukrainian-controlled territory, in blatant violation of the 19 September Minsk ceasefire lines, in an attemp to gain control of a significant rail juncture. [SEP] It is dangerous because Russia continues to train and equip separatists with heavy weapons and to fight by their side, in flagrant violation of the September Minsk agreement, Ukrainian sovereignty and international law.\nOutput: support\n', 'Sentence: I would repeat that Russia would never refuse to implement any useful document agreed upon during the crisis, including the 21 February agreement. [SEP] Regarding what one colleague said, that Russia is refusing to implement the 17 April Geneva statement\nOutput: attack\n']

In [ ]:
results = ask_gpt_classification(dataset, instuctions_examples)
pd.DataFrame(results).to_csv(f"{ArgUNSC_relations_path}/few_shot_multi_class_classification.csv", index=False)

## ElecDeb60to20

In [ ]:
ElecDeb60to20_relations_path = folder + "/gpt-4.1-nano/multi_class_classification/ElecDeb60to20/"
os.makedirs(ElecDeb60to20_relations_path, exist_ok=True)

In [15]:
dataset = pd.read_csv(folder + "/multi_class_classification/ElecDeb60to20/test.csv")

In [16]:
dataset.head()

                                                text  label label_value
0  That has been reinforced by direct commitments...      1     support
1  it's been reinforced by a number of other nati...      1     support
2  we have a contractual right to be in Berlin co...      1     support
3  I've stated on many occasions that the United ...      1     support
4  It is a commitment that we have to meet if we'...      1     support

### Zero-Shot

In [ ]:
results = ask_gpt_classification(dataset, INSTRUCTION_PROMPT['ElecDeb60to20'])
pd.DataFrame(results).to_csv(f"{ElecDeb60to20_relations_path}/zero_shot_multi_class_classification.csv", index=False)

In [ ]:
results[0]

### Few-Shot

In [17]:
instuctions_examples = f"{INSTRUCTION_PROMPT['ElecDeb60to20']}\n{EXAMPLES['ElecDeb60to20']}"
print(instuctions_examples)

You are a relation classification assistant. Classify the sentences separated by [SEP] using the labels: support, attack, no_relation


["Sentence: we have avoided surrender of principle or territory at the conference table [SEP] In the past seven years, in President Eisenhower's Administration, this situation has been reversed\nOutput: support\n", 'Sentence: although we are today, as Senator Kennedy has admitted, the strongest nation in the world militarily [SEP] we must increase our strength\nOutput: attack\n', 'Sentence: You know, people said it was a big risk at that time [SEP] when there was a crisis involving the Mexican peso, again, President Bill Clinton showed bold and dynamic leadership\nOutput: no_relation\n']

In [ ]:
results = ask_gpt_classification(dataset, instuctions_examples)
pd.DataFrame(results).to_csv(f"{ElecDeb60to20_relations_path}/few_shot_multi_class_classification.csv", index=False)

## ParlVote+

In [ ]:
ParlVotePlus_path = folder + "/gpt-4.1-nano/multi_class_classification/ParlVote+/"
os.makedirs(ParlVotePlus_path, exist_ok=True)

In [18]:
dataset = pd.read_csv(folder + "/multi_class_classification/ParlVote+/test.csv")

In [19]:
dataset.head()

,text,label,label_value
0,After the earlier fireworks from Government Me...,12,Political Authority: Party
1,The hon Gentleman gives a very interesting int...,10,Centralisation: Positive
2,I fully support the position the Minister is t...,3,European Union: Positive
3,Thousands of families in my constituency will ...,12,Political Authority: Party
4,"My father does not speak perfect English, but ...",3,European Union: Positive

### Zero-Shot

In [20]:
INSTRUCTION_PROMPT['ParlVote+']

'You are a motion policy preference classification assistant. Classify the motions using the following labels:Military: Positive, Military: Negative, Peace, European Union: Positive, European Union: Negative, Human Rights, Direct Democracy: Positive, Constitutionalism: Positive, Constitutionalism: Negative, Decentralisation: Positive, Centralisation: Positive, Political Corruption, Political Authority: Party, Political Authority: Personal, Free Market Economy, Incentives: Positive, Market Regulation, Technology: Positive, Nationalisation, Environmental Protection, Equality: Positive, Welfare State Expansion, Welfare State Limitation, Education Expansion, Education Limitation, Immigration: Negative, Immigration: Positive, Traditional Morality: Positive, Traditional Morality: Negative, Law and Order: Positive, Law and Order: Negative, Labour Groups: Positive, Labour Groups: Negative, Underprivileged Minority Groups\n\n'

In [ ]:
results = ask_gpt_classification(dataset, INSTRUCTION_PROMPT['ParlVote+'])
pd.DataFrame(results).to_csv(f"{ParlVotePlus_path}/zero_shot_multi_class_classification.csv", index=False)

In [ ]:
results[0]

### Few-Shot

In [21]:
instuctions_examples = f"{INSTRUCTION_PROMPT['ParlVote+']}\n{EXAMPLES['ParlVote+']}"
print(instuctions_examples)

You are a motion policy preference classification assistant. Classify the motions using the following labels:Military: Positive, Military: Negative, Peace, European Union: Positive, European Union: Negative, Human Rights, Direct Democracy: Positive, Constitutionalism: Positive, Constitutionalism: Negative, Decentralisation: Positive, Centralisation: Positive, Political Corruption, Political Authority: Party, Political Authority: Personal, Free Market Economy, Incentives: Positive, Market Regulation, Technology: Positive, Nationalisation, Environmental Protection, Equality: Positive, Welfare State Expansion, Welfare State Limitation, Education Expansion, Education Limitation, Immigration: Negative, Immigration: Positive, Traditional Morality: Positive, Traditional Morality: Negative, Law and Order: Positive, Law and Order: Negative, Labour Groups: Positive, Labour Groups: Negative, Underprivileged Minority Groups


['Sentence: Please stick to the motion.I congratulate the right hon Member for Birkenhead  and thank the Backbench Business Committee for granting us this very timely debate to reconsider the impact on the lowest-paid workers of the proposed changes to tax credits and to call for the Government to bring mitigation proposals to this House. Early next year it is the centenary of the birth of Harold Wilson. That Huddersfield lad coined the phrase, “A week is a long time in politics.” A lot of ermine and a flood of emails have flowed under the bridge since I signed this motion last week. I want to make it clear from the start that I absolutely support the Chancellor in getting Britain to live within its means. In fact, I often suggest to folk back home in Yorkshire who are talking about austerity that we should replace it with the phrase “living within our means”. That brings a whole new meaning to the campaign slogan “anti-living within your means”. Since last week, many constituents have echoed my position. To follow the style of the Leader of the Opposition, Martin from Holme Valley says that he agrees with the shift from tax credits to increased pay but shares my concern about the transitional impact of the changes. Bob from Salendine Nook says that he understands the point I make about employers underpaying staff and agrees with me on the need to reconsider the pace of change. Nicola from Oakes says that she agrees that the tax credits system is imperfect, as is the whole benefits system. She says that she would be better off financially reducing her hours, as she works full time, and that a change to the system needs to be implemented. She says that she feels she is currently being punished by the benefits system for trying to bring home more money by working her way up, and that a single person on income support, disability living allowance, housing benefit and other benefits could, in effect, be paid more in benefits than she brings home, including with her tax credits, to support a family. Dorothy from Marsden says that she fully understands the need for reform. As the motion clearly states, this about the pace and the impact on the lowest-paid workers. I firmly believe that work should always pay. People should always be better off in a job than on benefits. I say that as someone who did not go to university. When I left school, I did a succession of low-paid, part-time jobs before I joined the Royal Air Force at the age of 19, worked my way up, and travelled the world. I am proud that since 2010 unemployment is down by 51% in my constituency. I am proud that youth unemployment is down by more than half. I am proud that there is a net increase of 170 new businesses and there have been over 4,700 new apprenticeship starts. I am proud to say that I have just taken on my first apprentice and that I am paying him the living wage. On Friday 20 November I will hold my latest jobs fair at Holmfirth civic hall, where over 30 local businesses and organisations will be offering quality jobs and apprenticeships. We must build a low-tax, low-welfare, high-wage economy. As a compassionate Conservative, I want to live in a country where everyone has the opportunity of a decent, well-paid job. So let us crack on with it, and let us stand up for working people. I welcome the Chancellor’s announcement that he will lessen the impact on families and will set out these plans in the autumn statement. I hope that he and his Treasury boffins will be listening very carefully to the various suggestions, some of them very inventive, for transitional arrangements. Let us show that Britain can live within its means while, most importantly, looking after the most vulnerable and supporting those who go out and work every day. Several hon Members rose—\nOutput: Welfare State Expansion\n', 'Sentence: I had begun to doubt myself. Having intended to speak in favour of amendment No. 279, I began to have my doubts when I heard Labour Members question my hon Friend the Member for Westmorland and Lonsdale . However, I have now returned to my former opinion℄even more starkly℄having heard the hon Member for Edinburgh, West , who raises every fear that I had about the Bill. The Bill states: Statutory functions may be conferred on the Scottish Ministers".  Having read the Bill in its totality, I would welcome the addition of the rider: "but not in so far as they might affect England, Wales and Northern Ireland." That seems entirely proper, and everything that the hon Member for Edinburgh, West has said confirms that. It is difficult to confer a general duty on a Member of Parliament to hold the Executive to account when there remains a possibility℄albeit theoretical℄that the Executive are not accountable to him. That is a theoretical argument, but there is a more important argument which has more resonance in terms of public opinion. I would say to the hon and learned Member for Edinburgh, Pentlands  that, in these matters, perceptions are even more important than reality. Even now, I am approached by constituents at meetings and in public℄in a most unwelcome, unsolicited and unhelpful way℄who share their observation that, "Now Scotland is getting its own Parliament, isn\'t it awful and awkward that we have a Government entirely dominated by Scottish Members?" I have to point out to them that their concern is quite illegitimate and that they have no proper grievance. Those who sit on the Treasury Bench have a mandate and are very properly there. I should hate it if a situation arose in which my constituents had a legitimate grievance, and amendment No. 279 would prevent that from happening. As said, perception is important in these respects, and the Committee has a duty to remove such sources of conflict and public discontent..\nOutput: Centralisation: Positive\n', 'Sentence: I speak on behalf of those who are prepared to accept the Government\'s proposals—or to be bought off, as the hon Member for Kingston and Surbiton  suggests. I shall explain why. I am pleased that we are having this debate. My direct involvement in this Bill began when I chaired the Joint Scrutiny Committee—with the Home Affairs Committee and the Work and Pensions Committee—on it. Perhaps I should not say so as the Chairman of that Committee, but its work showed the value of draft scrutiny, because many other issues were sorted out before the Bill was introduced. I wish that we did that more often. The issue before the House is one of the few outstanding issues on which the Committee took a different view from the Government on what should be in the Bill. I argued the same case on Report and I have seen amendments passed in the other place, and I welcome the efforts that the Minister has made to get us to where we are tonight. I know—and from comments that have been made, the House knows—how much work it has required from him to get us to this position. For some people, who have followed the Bill from the perspective of losing friends or relatives in accidents such as the Marchioness disaster or train crashes, this subject appears to be a late entry into the Bill, which has given rise to concerns that the Bill itself may be threatened by our desire to extend it to cover custody. The Minister has done his best to get us to a position where the principle of covering deaths in custody is covered by the Bill without putting it under threat. He deserves the thanks of the House for that. Why am I prepared to accept this when, from the amendments that I tabled last time, it is evident that my preference would be a straightforward amendment to the Bill? The answer is that I believe that the amendment the Minister has tabled today will trigger a process that will lead inexorably to deaths in custody being brought within the scope of the Bill. Whether or not he feels he has the freedom tonight to talk about time scales, the fact is that the process, once started, will be unstoppable. The Minister is also responsible for prisons, and I do not believe that when he next meets the director of the Prison Service, he will say to him, "I\'ve got you out of that problem for the next few years, so I wouldn\'t worry about it if I were you. Instead, the Minister will say that deaths in custody could be included at any time and the Prison Service will have to be ready for that. Many of us would accept that, even if the provision had been on the face of the Bill, some delay in commencement would have been necessary to get the Prison Service to face up to its responsibilities in a way that it has not done so far. That is how the conversation will go. I do not wish to prejudge inquests in the pipeline, but there are some whose verdicts could make it untenable for the Government not to bring forward the resolution necessary under the amendment, however much the Government may prefer to consider the statutory ombudsman first and the forum next. I fear that there will be other inquests beyond those. That is the historical record, and the result will be that it will not be tenable for this or any Government not to enact this change. I believe that those of us who, a year or so ago, set out to bring this matter within the scope of the Bill are going to achieve our objective tonight. It is for that reason that I recommend to the House that we support the Government\'s proposal, which takes us a long way forward. As ever when Governments are asked to take a very different position from the one that they started with, there is a certain choreography about how such matters must be handled, but the amendment in lieu in the end gets us to where we want to go and delivers the result that we want. I am therefore very grateful to the Minister for everything that he has done.\nOutput: Law and Order: Positive\n']

In [ ]:
results = ask_gpt_classification(dataset, instuctions_examples)
pd.DataFrame(results).to_csv(f"{ParlVotePlus_path}/few_shot_multi_class_classification.csv", index=False)

# NER

In [23]:
PROMPT = {
    "instructions": (
        "Task: identify the entities in the sentence.\n\n"
        "Possible categories are:\n"
        "CC (coordinating conjunction, e.g. 'and', 'but'), "
        "CD (cardinal number, e.g. 'three'), "
        "DT (determiner, e.g. 'the'), "
        "EX (existential 'there'), "
        "FW (foreign word, e.g. 'ad hoc'), "
        "IN (preposition or subordinating conjunction, e.g. 'because'), "
        "JJ (adjective, e.g. 'strong'), "
        "JJR (comparative adjective, e.g. 'stronger'), "
        "JJS (superlative adjective, e.g. 'strongest'), "
        "LS (list marker, e.g. '1.'), "
        "MD (modal verb, e.g. 'must'), "
        "NN (singular noun, e.g. 'argument'), "
        "NNP (proper noun, e.g. 'Jennifer'), "
        "NNPS (plural proper noun, e.g. 'Americans'), "
        "NNS (plural noun, e.g. 'arguments'), "
        "PDT (predeterminer, e.g. 'all'), "
        "POS (possessive ending, e.g. \"'s\"), "
        "PRP (personal pronoun, e.g. 'she'), "
        "RB (adverb, e.g. 'clearly'), "
        "RBR (comparative adverb, e.g. 'more'), "
        "RBS (superlative adverb, e.g. 'most'), "
        "RP (particle, e.g. 'up' in 'give up'), "
        "SYM (symbol, e.g. '$'), "
        "TO (infinitive marker 'to'), "
        "UH (interjection, e.g. 'oh'), "
        "VB (base verb, e.g. 'argue'), "
        "VBD (past verb, e.g. 'argued'), "
        "VBG (gerund, e.g. 'arguing'), "
        "VBN (past participle, e.g. 'supported'), "
        "VBP (present verb, e.g. 'believe'), "
        "VBZ (3rd person present verb, e.g. 'believes'), "
        "WDT (wh-determiner, e.g. 'which'), "
        "WP (wh-pronoun, e.g. 'who'), "
        ", (comma), "
        ": (colon), "
        ". (dot), "
        "WRB (wh-adverb, e.g. 'why').\n\n"
        "Rewrite the entire sentence exactly as given.\n"
        "Surround each identified entity span with <tag>...</tag>.\n"
        "Do not add, remove, or change any words.\n\n"
        "Output the fully tagged sentence only.\n\n"
    ),
    "examples": (
        "Sentence: He was trying to get rid of sanctions for a reason : He wanted to restart weapons programs .\n"
        "Output: <PRP>He</PRP> <VBD>was</VBD> <VBG>trying</VBG> <TO>to</TO> <VB>get</VB> <JJ>rid</JJ> <IN>of</IN> <NNS>sanctions</NNS> <IN>for</IN> <DT>a</DT> <NN>reason</NN> <:>:</:> <PRP>He</PRP> <VBD>wanted</VBD> <TO>to</TO> <VB>restart</VB> <NNS>weapons</NNS> <NNS>programs</NNS><.>.</.> \n\n"

        "Sentence: He 'll have two minutes to answer .\n"
        "Output: <PRP>He</PRP> <MD>'ll</MD> <VB>have</VB> <CD>two</CD> <NNS>minutes</NNS> <TO>to</TO> <VB>answer</VB><.>.</.>\n\n"

        "Sentence: You remember the last debate ?\n"
        "Output: <PRP>You</PRP> <VBP>remember</VBP> <DT>the</DT> <JJ>last</JJ> <NN>debate</NN><.>.</.>\n\n"
    )
}

## NEREX

In [ ]:
nerex_path = folder + "/gpt-4.1-nano/ner/nerex/"
os.makedirs(nerex_path, exist_ok=True)

In [22]:
dataset = load_data(f"{folder}/ner/nerex/test.json")
len(dataset)

3237

### Zero-Shot

In [24]:
print(PROMPT['instructions'])

Task: identify the entities in the sentence.

Possible categories are:
CC (coordinating conjunction, e.g. 'and', 'but'), CD (cardinal number, e.g. 'three'), DT (determiner, e.g. 'the'), EX (existential 'there'), FW (foreign word, e.g. 'ad hoc'), IN (preposition or subordinating conjunction, e.g. 'because'), JJ (adjective, e.g. 'strong'), JJR (comparative adjective, e.g. 'stronger'), JJS (superlative adjective, e.g. 'strongest'), LS (list marker, e.g. '1.'), MD (modal verb, e.g. 'must'), NN (singular noun, e.g. 'argument'), NNP (proper noun, e.g. 'Jennifer'), NNPS (plural proper noun, e.g. 'Americans'), NNS (plural noun, e.g. 'arguments'), PDT (predeterminer, e.g. 'all'), POS (possessive ending, e.g. "'s"), PRP (personal pronoun, e.g. 'she'), RB (adverb, e.g. 'clearly'), RBR (comparative adverb, e.g. 'more'), RBS (superlative adverb, e.g. 'most'), RP (particle, e.g. 'up' in 'give up'), SYM (symbol, e.g. '$'), TO (infinitive marker 'to'), UH (interjection, e.g. 'oh'), VB (base verb, e.g. 'argue'), VBD (past verb, e.g. 'argued'), VBG (gerund, e.g. 'arguing'), VBN (past participle, e.g. 'supported'), VBP (present verb, e.g. 'believe'), VBZ (3rd person present verb, e.g. 'believes'), WDT (wh-determiner, e.g. 'which'), WP (wh-pronoun, e.g. 'who'), , (comma), : (colon), . (dot), WRB (wh-adverb, e.g. 'why').

Rewrite the entire sentence exactly as given.
Surround each identified entity span with <tag>...</tag>.
Do not add, remove, or change any words.

Output the fully tagged sentence only.

In [25]:
dataset.head(2)

,sentence,ner_tag
0,Good_evening from the University of Miami Conv...,"vbg in dt nnp in nnp nnp nnp in nnp nnp , nnp ."
1,I 'm Jim Lehrer of The NewsHour on PBS .,prp vbp nnp nnp in dt nn in nnp .

In [ ]:
results = ask_gpt_NER(dataset, instructions)
pd.DataFrame(results).to_csv(f"{nerex_path}/zero_shot_ner.csv", index=False)

100%|██████████| 1448/1448 [31:19<00:00,  1.30s/it]

In [ ]:
results[0]

### Few-Shot

In [26]:
instuctions_examples = f"{PROMPT['instructions']}\n{PROMPT['examples']}"
print(instuctions_examples)

Task: identify the entities in the sentence.

Possible categories are:
CC (coordinating conjunction, e.g. 'and', 'but'), CD (cardinal number, e.g. 'three'), DT (determiner, e.g. 'the'), EX (existential 'there'), FW (foreign word, e.g. 'ad hoc'), IN (preposition or subordinating conjunction, e.g. 'because'), JJ (adjective, e.g. 'strong'), JJR (comparative adjective, e.g. 'stronger'), JJS (superlative adjective, e.g. 'strongest'), LS (list marker, e.g. '1.'), MD (modal verb, e.g. 'must'), NN (singular noun, e.g. 'argument'), NNP (proper noun, e.g. 'Jennifer'), NNPS (plural proper noun, e.g. 'Americans'), NNS (plural noun, e.g. 'arguments'), PDT (predeterminer, e.g. 'all'), POS (possessive ending, e.g. "'s"), PRP (personal pronoun, e.g. 'she'), RB (adverb, e.g. 'clearly'), RBR (comparative adverb, e.g. 'more'), RBS (superlative adverb, e.g. 'most'), RP (particle, e.g. 'up' in 'give up'), SYM (symbol, e.g. '$'), TO (infinitive marker 'to'), UH (interjection, e.g. 'oh'), VB (base verb, e.g. 'argue'), VBD (past verb, e.g. 'argued'), VBG (gerund, e.g. 'arguing'), VBN (past participle, e.g. 'supported'), VBP (present verb, e.g. 'believe'), VBZ (3rd person present verb, e.g. 'believes'), WDT (wh-determiner, e.g. 'which'), WP (wh-pronoun, e.g. 'who'), , (comma), : (colon), . (dot), WRB (wh-adverb, e.g. 'why').

Rewrite the entire sentence exactly as given.
Surround each identified entity span with <tag>...</tag>.
Do not add, remove, or change any words.

Output the fully tagged sentence only.


Sentence: He was trying to get rid of sanctions for a reason : He wanted to restart weapons programs .
Output: <PRP>He</PRP> <VBD>was</VBD> <VBG>trying</VBG> <TO>to</TO> <VB>get</VB> <JJ>rid</JJ> <IN>of</IN> <NNS>sanctions</NNS> <IN>for</IN> <DT>a</DT> <NN>reason</NN> <:>:</:> <PRP>He</PRP> <VBD>wanted</VBD> <TO>to</TO> <VB>restart</VB> <NNS>weapons</NNS> <NNS>programs</NNS><.>.</.>

Sentence: He 'll have two minutes to answer .
Output: <PRP>He</PRP> <MD>'ll</MD> <VB>have</VB> <CD>two</CD> <NNS>minutes</NNS> <TO>to</TO> <VB>answer</VB><.>.</.>

Sentence: You remember the last debate ?
Output: <PRP>You</PRP> <VBP>remember</VBP> <DT>the</DT> <JJ>last</JJ> <NN>debate</NN><.>.</.>

In [ ]:
results = ask_gpt_NER(dataset, instuctions_examples)
pd.DataFrame(results).to_csv(f"{nerex_path}/few_shot_ner.csv", index=False)

100%|██████████| 1448/1448 [33:32<00:00,  1.39s/it]

In [ ]:
results[0]

{'text': "I will address the military aspect , if I may respond . The military aspect of the drug problem is being addressed . As a matter of fact , we are using the Department of Defense in a coordinated effort , in reconnaissance . But I do n't believe that we are going to turn the Department of Defense into a police organization . We are using our military assets in a prudent way to deal with interdiction , and we 've made some success in this area . Seventy tons of cocaine have been stopped . But , you know , when you look at the drug problem - and it is a tremendous problem , and there are no easy solutions to it - it 's a complicated problem , and it 's heading up the effort to try to create a drug - free America , which is a challenge and a goal of all of us . Not only will we utilize national defense and the Department of Defense , but we 've got to get on the demand side of the ledger ; we 've got to get to education . And education ought to begin at home , and it ought to be reinforced in our schools . And there 's another thing that will be more important than the premise of this question on a hypothetical of using troops . We will use the military assets , we will use military assets - but we need to focus on another part of this problem , and that problem is law enforcement . And here is where we have a major disagreement with the governor of Massachusetts . He is opposed to the death penalty for drug kingpins . We believe people convicted of that crime deserve the death penalty , as does the legislation that 's in the Congress that is supported by a bipartisan , including many Democrats of his party . He also was opposed to mandatory drug sentencing for drug dealers in the state of Massachusetts . You can not have a war on drugs , you can not be tough on drugs and weak on crime .",
 'ner_tags': 'b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim o b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim o o b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim o o o o o b-claim i-claim i-claim i-claim i-claim i-claim i-claim o o b-claim i-claim i-claim i-claim i-claim o o b-claim i-claim i-claim i-claim i-claim i-claim i-claim o i-claim i-claim i-claim i-claim i-claim o o b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim o b-claim i-claim i-claim i-claim i-claim i-claim o o b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim o b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim o o o o o o o b-claim i-claim i-claim i-claim i-claim o o b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim o b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim b-premise i-premise i-premise i-premise i-premise i-premise i-premise i-premise i-premise i-premise i-premise b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim o o o o o o o o o o o o o o o o o b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim o b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim',
 'response': "<claim>I will address the military aspect , if I may respond</claim>. <premise>The military aspect of the drug problem is being addressed</premise>. <claim>As a matter of fact , we are using the Department of Defense in a coordinated effort , in reconnaissance</claim>. <claim>But I do n't believe that we are going to turn the Department of Defense into a police organization</claim>. <premise>We are using our military assets in a prudent way to deal with interdiction , and we 've made some success in this area</premise>. <premise>Seventy tons of cocaine have been stopped</premise>. <claim>But , you know , when you look at the drug problem - and it is a tremendous problem , and there are no easy solutions to it - it 's a complicated problem , and it 's heading up the effort to try to create a drug - free America , which is a challenge and a goal of all of us</claim>. <claim>Not only will we utilize national defense and the Department of Defense , but we 've got to get on the demand side of the ledger ; we 've got to get to education</claim>. <claim>And education ought to begin at home , and it ought to be reinforced in our schools</claim>. <claim>And there 's another thing that will be more important than the premise of this question on a hypothetical of using troops</claim>. <claim>We will use the military assets , we will use military assets - but we need to focus on another part of this problem , and that problem is law enforcement</claim>. <claim>And here is where we have a major disagreement with the governor of Massachusetts</claim>. <claim>He is opposed to the death penalty for drug kingpins</claim>. <claim>We believe people convicted of that crime deserve the death penalty , as does the legislation that 's in the Congress that is supported by a bipartisan , including many Democrats of his party</claim>. <claim>He also was opposed to mandatory drug sentencing for drug dealers in the state of Massachusetts</claim>. <claim>You can not have a war on drugs , you can not be tough on drugs and weak on crime</claim>."}