In [ ]:
!pip install --upgrade openai

Requirement already satisfied: openai in /usr/local/lib/python3.12/dist-packages (1.108.0)
Collecting openai
  Downloading openai-2.0.1-py3-none-any.whl.metadata (29 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai) (4.10.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from openai) (0.11.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from openai) (2.11.9)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.12/dist-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->openai) (3.10)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (2025.8.3)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->openai) (0.4.1)
Downloading openai-2.0.1-py3-none-any.whl (956 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 956.3/956.3 kB 8.5 MB/s eta 0:00:00
Installing collected packages: openai
  Attempting uninstall: openai
    Found existing installation: openai 1.108.0
    Uninstalling openai-1.108.0:
      Successfully uninstalled openai-1.108.0
Successfully installed openai-2.0.1

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
from openai import OpenAI
from tqdm import tqdm
import pandas as pd
import json

In [ ]:
# Load the API key from the file
folder = "/content/drive/MyDrive/gpt"
with open(f'{folder}/gpt_key.txt', 'r') as f:
    openai_api_key = f.read().strip()
openai_client = OpenAI(api_key=openai_api_key)

In [ ]:
def load_data(filepath):
    with open(filepath, 'r') as f:
        raw_data = json.load(f)
    records = []
    for entry in raw_data:
        sentence = " ".join(entry['tokens']).strip()
        ner_tag = " ".join(entry['ner_tags']).strip().lower()
        records.append({
            "sentence": sentence,
            "ner_tag": ner_tag
        })
    return pd.DataFrame(records)

# ARGUMENT DETECTION

In [ ]:
instructions = (
    "You are an argument analysis assistant. Your task is to identify and label argumentative spans in the input sentence according to the following types: claim and premise. A claim expresses a stance, opinion, or proposed policy, while a premise provides justification or support for a claim. "
    "Rewrite the entire sentence without changing or omitting any words. Surround each identified span with a tag indicating its type, using the format <claim>...</claim> or <premise>...</premise>."
    "Only apply tags to complete spans of meaning, not to partial words or fragments. Do not tag anything that does not clearly belong to one of the listed types. Output only the fully tagged sentence, do not include any additional text.")
examples = (
    """Examples:
    1) Sentence: Yes, I voted for it, supported it. Output: <premise>Yes, I voted for it</premise>, <claim>supported it.</claim>
    2) Sentence: Next question here for President Clinton. Yes, ma'am, here on the front row. Output: Next question here for President Clinton. Yes, ma'am, here on the front row.
    3) Sentence: Not some of the military. That was the decision of the Joint Chiefs of Staff, recommended to us and agreed to by the president. That is a fact. Output: <claim>Not some of the military.</claim> <premise>That was the decision of the Joint Chiefs of Staff, recommended to us and agreed to by the president. That is a fact.</premise>
    """
)

In [ ]:
examples

"Examples:\n    1) Sentence: Yes, I voted for it, supported it. Output: <premise>Yes, I voted for it</premise>, <claim>supported it.</claim>\n    2) Sentence: Next question here for President Clinton. Yes, ma'am, here on the front row. Output: Next question here for President Clinton. Yes, ma'am, here on the front row.\n    3) Sentence: Not some of the military. That was the decision of the Joint Chiefs of Staff, recommended to us and agreed to by the president. That is a fact. Output: <claim>Not some of the military.</claim> <premise>That was the decision of the Joint Chiefs of Staff, recommended to us and agreed to by the president. That is a fact.</premise>\n    "

In [ ]:
dataset = load_data(f"{folder}/argument_detection/test.json")
len(dataset)

2436

In [ ]:
dataset.head(2)

,sentence,ner_tag
0,Ohio had the best year it's ever had last year...,b-claim i-claim i-claim i-claim i-claim i-clai...
1,Yes?,o

## Zero-Shot

In [ ]:
print(instructions)

You are an argument analysis assistant. Your task is to identify and label argumentative spans in the input sentence according to the following types: claim and premise. A claim expresses a stance, opinion, or proposed policy, while a premise provides justification or support for a claim. Rewrite the entire sentence without changing or omitting any words. Surround each identified span with a tag indicating its type, using the format <claim>...</claim> or <premise>...</premise>.Only apply tags to complete spans of meaning, not to partial words or fragments. Do not tag anything that does not clearly belong to one of the listed types. Output only the fully tagged sentence, do not include any additional text.

In [ ]:
dataset.head(2)

,sentence,ner_tag
0,Ohio had the best year it's ever had last year...,b-claim i-claim i-claim i-claim i-claim i-clai...
1,Yes?,o

In [ ]:
results = []
engine = "gpt-4.1-nano"
max_token = 512
temperature = 0.0  # Lower temp for consistency

for idx, (sentence, tag) in tqdm(dataset.iterrows(), total=len(dataset)):
    response = openai_client.chat.completions.create(
        model=engine,
        messages=[{"role": "system", "content": instructions},
                  {"role": "user", "content": f"Sentence: {sentence}"}],
        max_tokens=max_token,
        temperature=temperature,
    ).choices[0].message.content.strip()
    results.append({
        'sentence': sentence,
        'tags': tag,
        'gpt_response': response
    })

pd.DataFrame(results).to_csv(f"{folder}/argument_detection_zero_shot_results.csv", index=False)

100%|██████████| 2436/2436 [1:13:04<00:00,  1.80s/it]

In [ ]:
results[0]

{'sentence': "Ohio had the best year it's ever had last year. Michigan had the best year they've ever had.",
 'tags': 'b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim o o o o o o o o',
 'gpt_response': "Ohio had the <claim>best year it's ever had last year</claim>. Michigan had the <claim>best year they've ever had</claim>."}

## Few-Shot

In [ ]:
instuctions_examples = f"{instructions}\n{examples.strip()}"
print(instuctions_examples)

You are an argument analysis assistant. Your task is to identify and label argumentative spans in the input sentence according to the following types: claim and premise. A claim expresses a stance, opinion, or proposed policy, while a premise provides justification or support for a claim. Rewrite the entire sentence without changing or omitting any words. Surround each identified span with a tag indicating its type, using the format <claim>...</claim> or <premise>...</premise>.Only apply tags to complete spans of meaning, not to partial words or fragments. Do not tag anything that does not clearly belong to one of the listed types. Output only the fully tagged sentence, do not include any additional text.
Examples:
    1) Sentence: Yes, I voted for it, supported it. Output: <premise>Yes, I voted for it</premise>, <claim>supported it.</claim>
    2) Sentence: Next question here for President Clinton. Yes, ma'am, here on the front row. Output: Next question here for President Clinton. Yes, ma'am, here on the front row.
    3) Sentence: Not some of the military. That was the decision of the Joint Chiefs of Staff, recommended to us and agreed to by the president. That is a fact. Output: <claim>Not some of the military.</claim> <premise>That was the decision of the Joint Chiefs of Staff, recommended to us and agreed to by the president. That is a fact.</premise>

In [ ]:
results = []
engine = "gpt-4.1-nano"
max_token = 512
temperature = 0.0  # Lower temp for consistency

for idx, (sentence, tag) in tqdm(dataset.iterrows(), total=len(dataset)):
    response = openai_client.chat.completions.create(
        model=engine,
        messages=[{"role": "system", "content": instuctions_examples},
                  {"role": "user", "content": f"Sentence: {sentence}"}],
        max_tokens=max_token,
        temperature=temperature,
    ).choices[0].message.content.strip()
    results.append({
        'sentence': sentence,
        'tags': tag,
        'gpt_response': response
    })

pd.DataFrame(results).to_csv(f"{folder}/argument_detection_few_shot_results.csv", index=False)

100%|██████████| 2436/2436 [1:17:49<00:00,  1.92s/it]

In [ ]:
results[0]

{'sentence': "Ohio had the best year it's ever had last year. Michigan had the best year they've ever had.",
 'tags': 'b-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim i-claim o o o o o o o o',
 'gpt_response': "Ohio had the <claim>best year it's ever had last year</claim>. Michigan had the <claim>best year they've ever had</claim>."}

# SENTIMENT ANALYSIS

In [ ]:
instructions = (
    "You are a sentiment classification assistant. Your task is to classify the sentiment of the sentence. The possibile sentiments are: positive or negative."
    "Output only one of the allowed relation types: positive or negative. Do not include punctuation, explanation, or formatting."
)
examples = ("""Examples:
1) Sentence: "Do not the Government’s proposals introduce some quite substantial financial risks for local authorities... councils in the very tough position of deciding who are the deserving poor and who are not?" Output: Negative
2) Sentence: "It is a pleasure to follow the right hon Member... the Minister's ID card proposals do not meet that threshold..." Output: Positive
3) Sentence: "Today’s debate is not just about reform of the health service; it is about democracy, accountability and transparency... That is a disgrace, and we should all support the motion today." Output: Negative
""")

In [ ]:
print(instructions)

You are a sentiment classification assistant. Your task is to classify the sentiment of the sentence. The possibile sentiments are: positive or negative.Output only one of the allowed relation types: positive or negative. Do not include punctuation, explanation, or formatting.

In [ ]:
dataset = pd.read_csv(f"{folder}/sentiment_analysis/test.csv")
len(dataset)

3346

In [ ]:
dataset.head(3)

                                                text  label
0  The important words are "akin to".We have had ...      0
1  The Minister says that it is a minor matter, b...      0
2  May I reciprocate by thanking my hon Friend fo...      1

## Zero-Shot

In [ ]:
results = []
engine = "gpt-4.1-nano"
max_token = 50
temperature = 0.0  # Lower temp for consistency

for idx, (sentence, label) in tqdm(dataset.iterrows(), total=len(dataset)):
    response = openai_client.chat.completions.create(
        model=engine,
        messages=[{"role": "system", "content": instructions},
                  {"role": "user", "content": f"Sentence: {sentence}"}],
        max_tokens=max_token,
        temperature=temperature,
    ).choices[0].message.content.strip()
    results.append({
        'sentence': sentence,
        'label': label,
        'gpt_response': response
    })

pd.DataFrame(results).to_csv(f"{folder}/sentiment_analysis_zero_shot_results.csv", index=False)

100%|██████████| 3346/3346 [38:14<00:00,  1.46it/s]

In [ ]:
results[0]

{'sentence': 'The important words are "akin to".We have had a good debate. My hon Friends have made excellent contributions but, as my hon Friend the Under-Secretary of State for Scotland has commented, it has been our pleasure to sit and watch a tableau of—That would be a rather cruel way to characterise it. Perhaps it would be fairer to say that a range of views was expressed.I have barely started, but if the hon Gentleman insists.I should not have bothered. I want to focus attention on the practical effects of the amendments, which would make changes that, as several hon Members pointed out, would alter the Bill\'s nature and character. They would introduce a series of discrepancies in the provisions, which would make it unworkable. The amendments that the hon Member for Gainsborough  tabled would allow siblings to form civil partnerships. The amendments that the hon Member for Christchurch  tabled would allow unmarried parents and children and unmarried siblings to form such partnerships, as long as they shared a home. He would also extend such provision to cohabiting couples. On Second Reading, the Bill received a majority of 377 votes on the basis that earlier amendments, which had the effect of including close family relatives, would be removed. In Committee, we voted 13 to one to remove the amendments. The argument for limiting civil partnership to unrelated same sex couples is clear and compelling and has been rehearsed on many occasions on the Floor of the House and in Committee. Furthermore, the hon Member for Gainsborough said on Second Reading that the amendments that the House of Lords had passed might be unworkable as they stood. I am happy to agree with him about that. Given that, I find it difficult to accept his reasoning for tabling amendments to reinstate new categories of civil partnerships for siblings. They are no more workable. Indeed, they give rise to new anomalies. I do not want to spend an inordinate amount of time reiterating all the detailed arguments about the issue but I want to re-emphasise the clear aim of the Bill. We introduced it with a specific purpose, which is to provide legal recognition for unrelated same-sex couples who do not currently have the option, which is available to opposite-sex couples, to marry. We seek to create a parallel but different legal relationship that mirrors as fully as possible the rights and responsibilities enjoyed by those who can marry, and that uses civil marriage as a template for the processes, rights and responsibilities that go with civil partnership. We are doing this for reasons of equality and social justice.As I have just pointed out, we have used civil marriage as the template for creating a completely new legal relationship, that of the civil partnership. We had some discussion about this in Committee, and our view was that, unless there was an objective justification for a difference in the approaches taken to civil marriage and civil partnership, no difference should exist. There are very few areas in which any difference does exist. The whole point, however, is that civil partnership is not civil marriage, for a variety of reasons, such as the traditions and history—religious and otherwise—that accompany marriage. It is not marriage, but it is, in many ways—dare I say it?—akin to marriage. We make no apology for that.My hon Friend is absolutely right. In fact, the hon Member for Aldershot  let the cat out of the bag when he said that his reason for wanting to call this new relationship a gay marriage was precisely to provoke protest out in the country. We have identified a particular issue, and we want a 21st century legal process to resolve the difficulties involved. That is what we are delivering in the Bill.While that is not a criterion in the Bill, I have said clearly on Second Reading—and I intend to say again later—that the particular difficulty identified here involves the thousands of gay and lesbian couples who live together and share their lives, yet have no way of gaining legal recognition for their relationship. I am quite happy to say that, and I am sorry that the hon Gentleman thinks that that is somehow a difficult motive to have. Civil partnership has not been designed as a legal relationship for people who are related to each other.I resent the hon Gentleman\'s comments. I have been absolutely open about what the Government intend to do with this new legal relationship. I have been open about the extent to which it replicates the provisions of civil marriage, where there is no objective justification for it not to do so. But it is not marriage. It is a new legal relationship for same-sex couples so that they can have the legal recognition that they cannot currently get.My hon Friend is right. Clearly, that is because we have identified an injustice for thousands of couples who are sharing their lives and who cannot at the moment find a legal way to have that relationship recognised, and, with that, have the range of rights and responsibilities that go with civil partnerships. That is the justification for this legislation. It is not designed, however, to address the problems for those people who are related to each other. That has been accepted not only by large numbers of Members of the House but by organisations that lobby on behalf of the interests of those people, the Law Society, the National Association of Citizens Advice Bureaux, the Solicitors Family Law Association, the trade union movement, equality groups, carers groups and the leaders of all three main parties in the House. These and similar amendments have come in various different guises throughout proceedings on the Bill. At one point, in another place, they were ostensibly concerned with protecting carers. Once Carers UK indicated clearly that not only would they not support carers but positively damage caring relationships in many places, people backed off from that justification. Today, we have heard a new justification; the argument about inheritance tax. That is a reasonable debate, but at a cost of £2.8 billion a year to abolish inheritance tax, hon Members are right that that would not be one of my top priorities. Nevertheless, they can raise that during consideration of the Finance Bill. Neither is it the case that the Government have not recognised that there are particular issues not only for opposite-sex cohabiting couples but for others. The argument remains, however, that this is not the right Bill to address those problems. It is not only the Government who believe that. The Law Commission concluded in its report on home sharers in 2002 that one solution was not possible for all the different permutations of home sharers. It stated: "It is not possible . . . to devise a statutory scheme for the ascertainment and quantification of beneficial interests in the   shared home which can operate fairly and evenly across the diversity of domestic circumstances which are now to be encountered." The Law Commission recognised that there was not one simple way to approach the matter, as do the Government, and the Bill addresses a particular issue. I will move on to the detail of the amendments and take the House on a short tour of the new absurdities that hon Members have created in relation to their amendments. First, with respect to the arguments about siblings and other family members, to which the amendment of the hon Member for Christchurch  extends, of course, siblings and other family members already have legal recognition of their relationships by virtue of the fact that they are related. They do not need legal recognition in the same way that same-sex couples do. Siblings, for example, are already recognised in law, whereas the law often treats the relationships between same-sex couples as invisible. That is the basis of many of the issues that they face, as was rightly identified by the hon Member for Wealden . Secondly, as several hon Members have mentioned, there is what we could call the Chekhov problem; the three sisters problem. There may be three sisters who live together—With uncle Vanya— They may wish to benefit from some of these rights and responsibilities. How are they to decide who forms a civil partnership? What impact would that decision have on internal family decisions and relationships? I do not believe that it could be positive. Thirdly—perhaps we should call this the uncle Vanya question—is it only siblings, parents and children who live together in caring relationships? What about a niece who cares for an aunt or a grandson who cares for a grandfather? Why should only siblings, parents and children be singled out for the dubious honour of forming a legal relationship that does not in any case meet the needs of their joint lives? Fourthly, as several Members have pointed out, the financial repercussions of the new clauses and amendments render the Bill nonsensical. I am thinking of the effect on both the pension and the benefit provisions. The fifth point relates to the introduction of new dissolution procedures for the new categories of civil partnership favoured by the hon Members for Christchurch and for Gainsborough . Under the procedure favoured by the hon Member for Gainsborough, a dissolution order would be granted without discussion following an application to the court by one of the civil partners. The hon Gentleman has been quite honest. He has created that new procedure to overcome a problem that we identified on Second Reading; the ridiculousness of expecting two sisters, or a mother and son, to go through a divorce-like process. Nevertheless, a process whereby dissolution is almost immediate involves its own myriad absurdities. Were family members to form civil partnerships under the hon Gentleman\'s provisions, a decision to end such a partnership could be made by one of them in the space of a few moments. There would be little time in which to think the decision through. There would be cursory notice to be given to the other party, and minimal support for the partner left behind. Leaving a family member—a civil partner—with few protections is as daft as forcing a daughter to undergo a divorce-style procedure with her mother. Regardless of how the hon Gentlemen may seek to include family members, their proposals create legal nonsense after legal nonsense. Let me make this as clear as I can. Family members should not be dealt with in this Bill, and torturing the Bill to make provision for them will not change the fundamental absurdity of including them. The hon Member for Christchurch believes that we should extend the Bill to opposite-sex cohabiting couples. We had some discussion about that on Second Reading and in Committee. The hon Gentleman\'s proposals would allow both opposite-sex and same-sex couples to form civil partnerships whether or not they were related in the prohibited degrees, and would also apply to overseas relationships. It has been made clear at several stages, both here and in the other place, that the Bill is designed to deal with disadvantages experienced by same-sex couples who cannot marry. Opposite-sex couples have no need of civil partnership, because they can marry. Some Members asked, "What if they do not want or feel able to take on the responsibilities of marriage?" The point has rightly been made that many of the provisions relating to civil partnership are very similar to those relating to civil marriage. I fail to see why someone who was unwilling to take on the responsibilities of civil marriage would want to take on the equivalent responsibilities of civil partnership. Either we have the rights and responsibilities, the legal registration process and the dissolution—which people may well reject—or we set up what can only be described as my hon Friend the Member for Wallasey  described it, "marriage-lite". If anything were likely to undermine the brand of marriage more—if I may employ the free-marketeer language used by the hon Member for Christchurch—it would be his proposal for the lightweight, easy-in, easy-out relationship that he appears to favour. There are serious issues for cohabiting couples. That is why the Government are undertaking not just to advise and educate people about their legal status if they are not married, but to consider how we can ensure that the legal rights currently applying to, for instance, the protection of children in the Children Bill can be better utilised for cohabiting couples than they are now. Also, we will ask the Law Commission to review the law in this area. There is a whole range of ways in which we can and will address these issues. The new clauses and amendments seek to change yet again the Bill\'s fundamental principles. We reject them, because we have a clear view as to what a civil partnership is and whom it is for. Its purpose is to enable legal recognition, respect and dignity for thousands of gay and lesbian couples in this country. A charitable interpretation of the amendments is that they are misguided. They would not improve the position for carers and other family members; arguably, they would damage those relationships, and they cannot address issues of concern to cohabiting opposite sex couples. A less charitable but perhaps more realistic assessment is that, in all their permutations, these are wrecking amendments, supported by those who cannot and will not accept the value of stable gay and lesbian relationships. Whether misguided or mischievous, they are wrong and I hope that the House will reject them.',
 'label': 0,
 'gpt_response': 'negative'}

## Few-Shot

In [ ]:
instuctions_examples = f"{instructions}\n{examples.strip()}"
print(instuctions_examples)

You are a sentiment classification assistant. Your task is to classify the sentiment of the sentence. The possibile sentiments are: positive or negative.Output only one of the allowed relation types: positive or negative. Do not include punctuation, explanation, or formatting.
Examples:
1) Sentence: "Do not the Government’s proposals introduce some quite substantial financial risks for local authorities... councils in the very tough position of deciding who are the deserving poor and who are not?" Output: Negative
2) Sentence: "It is a pleasure to follow the right hon Member... the Minister's ID card proposals do not meet that threshold..." Output: Positive
3) Sentence: "Today’s debate is not just about reform of the health service; it is about democracy, accountability and transparency... That is a disgrace, and we should all support the motion today." Output: Negative

In [ ]:
results = []
engine = "gpt-4.1-nano"
max_token = 50
temperature = 0.0  # Lower temp for consistency

for idx, (sentence, label) in tqdm(dataset.iterrows(), total=len(dataset)):
    response = openai_client.chat.completions.create(
        model=engine,
        messages=[{"role": "system", "content": instuctions_examples},
                  {"role": "user", "content": f"Sentence: {sentence}"}],
        max_tokens=max_token,
        temperature=temperature,
    ).choices[0].message.content.strip()
    results.append({
        'sentence': sentence,
        'label': label,
        'gpt_response': response
    })

pd.DataFrame(results).to_csv(f"{folder}/sentiment_analysis_few_shot_results.csv", index=False)

100%|██████████| 3346/3346 [26:35<00:00,  2.10it/s]

In [ ]:
results[0]

{'sentence': 'The important words are "akin to".We have had a good debate. My hon Friends have made excellent contributions but, as my hon Friend the Under-Secretary of State for Scotland has commented, it has been our pleasure to sit and watch a tableau of—That would be a rather cruel way to characterise it. Perhaps it would be fairer to say that a range of views was expressed.I have barely started, but if the hon Gentleman insists.I should not have bothered. I want to focus attention on the practical effects of the amendments, which would make changes that, as several hon Members pointed out, would alter the Bill\'s nature and character. They would introduce a series of discrepancies in the provisions, which would make it unworkable. The amendments that the hon Member for Gainsborough  tabled would allow siblings to form civil partnerships. The amendments that the hon Member for Christchurch  tabled would allow unmarried parents and children and unmarried siblings to form such partnerships, as long as they shared a home. He would also extend such provision to cohabiting couples. On Second Reading, the Bill received a majority of 377 votes on the basis that earlier amendments, which had the effect of including close family relatives, would be removed. In Committee, we voted 13 to one to remove the amendments. The argument for limiting civil partnership to unrelated same sex couples is clear and compelling and has been rehearsed on many occasions on the Floor of the House and in Committee. Furthermore, the hon Member for Gainsborough said on Second Reading that the amendments that the House of Lords had passed might be unworkable as they stood. I am happy to agree with him about that. Given that, I find it difficult to accept his reasoning for tabling amendments to reinstate new categories of civil partnerships for siblings. They are no more workable. Indeed, they give rise to new anomalies. I do not want to spend an inordinate amount of time reiterating all the detailed arguments about the issue but I want to re-emphasise the clear aim of the Bill. We introduced it with a specific purpose, which is to provide legal recognition for unrelated same-sex couples who do not currently have the option, which is available to opposite-sex couples, to marry. We seek to create a parallel but different legal relationship that mirrors as fully as possible the rights and responsibilities enjoyed by those who can marry, and that uses civil marriage as a template for the processes, rights and responsibilities that go with civil partnership. We are doing this for reasons of equality and social justice.As I have just pointed out, we have used civil marriage as the template for creating a completely new legal relationship, that of the civil partnership. We had some discussion about this in Committee, and our view was that, unless there was an objective justification for a difference in the approaches taken to civil marriage and civil partnership, no difference should exist. There are very few areas in which any difference does exist. The whole point, however, is that civil partnership is not civil marriage, for a variety of reasons, such as the traditions and history—religious and otherwise—that accompany marriage. It is not marriage, but it is, in many ways—dare I say it?—akin to marriage. We make no apology for that.My hon Friend is absolutely right. In fact, the hon Member for Aldershot  let the cat out of the bag when he said that his reason for wanting to call this new relationship a gay marriage was precisely to provoke protest out in the country. We have identified a particular issue, and we want a 21st century legal process to resolve the difficulties involved. That is what we are delivering in the Bill.While that is not a criterion in the Bill, I have said clearly on Second Reading—and I intend to say again later—that the particular difficulty identified here involves the thousands of gay and lesbian couples who live together and share their lives, yet have no way of gaining legal recognition for their relationship. I am quite happy to say that, and I am sorry that the hon Gentleman thinks that that is somehow a difficult motive to have. Civil partnership has not been designed as a legal relationship for people who are related to each other.I resent the hon Gentleman\'s comments. I have been absolutely open about what the Government intend to do with this new legal relationship. I have been open about the extent to which it replicates the provisions of civil marriage, where there is no objective justification for it not to do so. But it is not marriage. It is a new legal relationship for same-sex couples so that they can have the legal recognition that they cannot currently get.My hon Friend is right. Clearly, that is because we have identified an injustice for thousands of couples who are sharing their lives and who cannot at the moment find a legal way to have that relationship recognised, and, with that, have the range of rights and responsibilities that go with civil partnerships. That is the justification for this legislation. It is not designed, however, to address the problems for those people who are related to each other. That has been accepted not only by large numbers of Members of the House but by organisations that lobby on behalf of the interests of those people, the Law Society, the National Association of Citizens Advice Bureaux, the Solicitors Family Law Association, the trade union movement, equality groups, carers groups and the leaders of all three main parties in the House. These and similar amendments have come in various different guises throughout proceedings on the Bill. At one point, in another place, they were ostensibly concerned with protecting carers. Once Carers UK indicated clearly that not only would they not support carers but positively damage caring relationships in many places, people backed off from that justification. Today, we have heard a new justification; the argument about inheritance tax. That is a reasonable debate, but at a cost of £2.8 billion a year to abolish inheritance tax, hon Members are right that that would not be one of my top priorities. Nevertheless, they can raise that during consideration of the Finance Bill. Neither is it the case that the Government have not recognised that there are particular issues not only for opposite-sex cohabiting couples but for others. The argument remains, however, that this is not the right Bill to address those problems. It is not only the Government who believe that. The Law Commission concluded in its report on home sharers in 2002 that one solution was not possible for all the different permutations of home sharers. It stated: "It is not possible . . . to devise a statutory scheme for the ascertainment and quantification of beneficial interests in the   shared home which can operate fairly and evenly across the diversity of domestic circumstances which are now to be encountered." The Law Commission recognised that there was not one simple way to approach the matter, as do the Government, and the Bill addresses a particular issue. I will move on to the detail of the amendments and take the House on a short tour of the new absurdities that hon Members have created in relation to their amendments. First, with respect to the arguments about siblings and other family members, to which the amendment of the hon Member for Christchurch  extends, of course, siblings and other family members already have legal recognition of their relationships by virtue of the fact that they are related. They do not need legal recognition in the same way that same-sex couples do. Siblings, for example, are already recognised in law, whereas the law often treats the relationships between same-sex couples as invisible. That is the basis of many of the issues that they face, as was rightly identified by the hon Member for Wealden . Secondly, as several hon Members have mentioned, there is what we could call the Chekhov problem; the three sisters problem. There may be three sisters who live together—With uncle Vanya— They may wish to benefit from some of these rights and responsibilities. How are they to decide who forms a civil partnership? What impact would that decision have on internal family decisions and relationships? I do not believe that it could be positive. Thirdly—perhaps we should call this the uncle Vanya question—is it only siblings, parents and children who live together in caring relationships? What about a niece who cares for an aunt or a grandson who cares for a grandfather? Why should only siblings, parents and children be singled out for the dubious honour of forming a legal relationship that does not in any case meet the needs of their joint lives? Fourthly, as several Members have pointed out, the financial repercussions of the new clauses and amendments render the Bill nonsensical. I am thinking of the effect on both the pension and the benefit provisions. The fifth point relates to the introduction of new dissolution procedures for the new categories of civil partnership favoured by the hon Members for Christchurch and for Gainsborough . Under the procedure favoured by the hon Member for Gainsborough, a dissolution order would be granted without discussion following an application to the court by one of the civil partners. The hon Gentleman has been quite honest. He has created that new procedure to overcome a problem that we identified on Second Reading; the ridiculousness of expecting two sisters, or a mother and son, to go through a divorce-like process. Nevertheless, a process whereby dissolution is almost immediate involves its own myriad absurdities. Were family members to form civil partnerships under the hon Gentleman\'s provisions, a decision to end such a partnership could be made by one of them in the space of a few moments. There would be little time in which to think the decision through. There would be cursory notice to be given to the other party, and minimal support for the partner left behind. Leaving a family member—a civil partner—with few protections is as daft as forcing a daughter to undergo a divorce-style procedure with her mother. Regardless of how the hon Gentlemen may seek to include family members, their proposals create legal nonsense after legal nonsense. Let me make this as clear as I can. Family members should not be dealt with in this Bill, and torturing the Bill to make provision for them will not change the fundamental absurdity of including them. The hon Member for Christchurch believes that we should extend the Bill to opposite-sex cohabiting couples. We had some discussion about that on Second Reading and in Committee. The hon Gentleman\'s proposals would allow both opposite-sex and same-sex couples to form civil partnerships whether or not they were related in the prohibited degrees, and would also apply to overseas relationships. It has been made clear at several stages, both here and in the other place, that the Bill is designed to deal with disadvantages experienced by same-sex couples who cannot marry. Opposite-sex couples have no need of civil partnership, because they can marry. Some Members asked, "What if they do not want or feel able to take on the responsibilities of marriage?" The point has rightly been made that many of the provisions relating to civil partnership are very similar to those relating to civil marriage. I fail to see why someone who was unwilling to take on the responsibilities of civil marriage would want to take on the equivalent responsibilities of civil partnership. Either we have the rights and responsibilities, the legal registration process and the dissolution—which people may well reject—or we set up what can only be described as my hon Friend the Member for Wallasey  described it, "marriage-lite". If anything were likely to undermine the brand of marriage more—if I may employ the free-marketeer language used by the hon Member for Christchurch—it would be his proposal for the lightweight, easy-in, easy-out relationship that he appears to favour. There are serious issues for cohabiting couples. That is why the Government are undertaking not just to advise and educate people about their legal status if they are not married, but to consider how we can ensure that the legal rights currently applying to, for instance, the protection of children in the Children Bill can be better utilised for cohabiting couples than they are now. Also, we will ask the Law Commission to review the law in this area. There is a whole range of ways in which we can and will address these issues. The new clauses and amendments seek to change yet again the Bill\'s fundamental principles. We reject them, because we have a clear view as to what a civil partnership is and whom it is for. Its purpose is to enable legal recognition, respect and dignity for thousands of gay and lesbian couples in this country. A charitable interpretation of the amendments is that they are misguided. They would not improve the position for carers and other family members; arguably, they would damage those relationships, and they cannot address issues of concern to cohabiting opposite sex couples. A less charitable but perhaps more realistic assessment is that, in all their permutations, these are wrecking amendments, supported by those who cannot and will not accept the value of stable gay and lesbian relationships. Whether misguided or mischievous, they are wrong and I hope that the House will reject them.',
 'label': 0,
 'gpt_response': 'positive'}

# RELATION CLASSIFICATION

In [ ]:
instructions = (
    "You are a relation classification assistant. Your task is to determine the type of argumentative relation between two argument spans in the sentence below. The two arguments are separated by a [SEP] tag."
    "Output only one of the allowed relation types: support, attack, or neither. Do not include punctuation, explanation, or formatting."
)
examples = (
    """Examples:
    1) Sentence: "We're not going to support the $300 billion tax cut that they have for corporate America and the very wealthy. It didn't meet my test."
    Output: neither

    2) Sentence: "They do have stakes in it. What we need now is a president who understands how to bring these other countries together to recognize their stakes in this."
    Output: support

    3) Sentence: "I respect the belief about life and when it begins. I can't take what is an article of faith for me and legislate it for someone who doesn't share that article of faith, whether they be agnostic, atheist, Jew, Protestant, whatever."
    Output: attack"""
)

In [ ]:
print(instructions)

You are a relation classification assistant. Your task is to determine the type of argumentative relation between two argument spans in the sentence below. The two arguments are separated by a [SEP] tag.Output only one of the allowed relation types: support, attack, or neither. Do not include punctuation, explanation, or formatting.

In [ ]:
dataset = pd.read_csv(f"{folder}/relation_classification/test.csv")
len(dataset)

5102

In [ ]:
dataset.head()

   link_type  linked                                               text
0          0       1  we want to do is commit more forces anywhere. ...
1          0       1  We need to call upon Syria to release the thre...
2          1       1  that's not the way this country ought to be ru...
3          1       1  if we remain dependent on a source of energy t...
4          2       0  This strategy requires additional troops. [SEP...

In [ ]:
for idx, row in tqdm(dataset.iterrows(), total=len(dataset)):
    print(row)
    break

  0%|          | 0/5102 [00:00<?, ?it/s]

link_type                                                    0
linked                                                       1
text         we want to do is commit more forces anywhere. ...
Name: 0, dtype: object

## Zero-Shot

In [ ]:
results = []
engine = "gpt-4.1-nano"
max_token = 50
temperature = 0.0  # Lower temp for consistency

for idx, row in tqdm(dataset.iterrows(), total=len(dataset)):
    sentence = row.text
    link_type = row.link_type
    response = openai_client.chat.completions.create(
        model=engine,
        messages=[{"role": "system", "content": instructions},
                  {"role": "user", "content": f"Sentence: {sentence}"}],
        max_tokens=max_token,
        temperature=temperature,
    ).choices[0].message.content.strip()
    results.append({
        'sentence': sentence,
        'link_type': link_type,
        'gpt_response': response
    })

pd.DataFrame(results).to_csv(f"{folder}/relation_classification_zero_shot_results.csv", index=False)

100%|██████████| 5102/5102 [39:55<00:00,  2.13it/s]

In [ ]:
results[0]

{'sentence': 'we want to do is commit more forces anywhere. [SEP] What I want the President to do, and I think he may have done it, his last statement, call for an unconditional end of the violence',
 'link_type': 0,
 'gpt_response': 'support'}

## Few-Shot

In [ ]:
instuctions_examples = f"{instructions}\n{examples.strip()}"
print(instuctions_examples)

You are a relation classification assistant. Your task is to determine the type of argumentative relation between two argument spans in the sentence below. The two arguments are separated by a [SEP] tag.Output only one of the allowed relation types: support, attack, or neither. Do not include punctuation, explanation, or formatting.
Examples:
    1) Sentence: "We're not going to support the $300 billion tax cut that they have for corporate America and the very wealthy. It didn't meet my test."
    Output: neither

    2) Sentence: "They do have stakes in it. What we need now is a president who understands how to bring these other countries together to recognize their stakes in this."
    Output: support

    3) Sentence: "I respect the belief about life and when it begins. I can't take what is an article of faith for me and legislate it for someone who doesn't share that article of faith, whether they be agnostic, atheist, Jew, Protestant, whatever."
    Output: attack

In [ ]:
results = []
engine = "gpt-4.1-nano"
max_token = 50
temperature = 0.0  # Lower temp for consistency

for idx, row in tqdm(dataset.iterrows(), total=len(dataset)):
    sentence = row.text
    link_type = row.link_type
    response = openai_client.chat.completions.create(
        model=engine,
        messages=[{"role": "system", "content": instuctions_examples},
                  {"role": "user", "content": f"Sentence: {sentence}"}],
        max_tokens=max_token,
        temperature=temperature,
    ).choices[0].message.content.strip()
    results.append({
        'sentence': sentence,
        'link_type': link_type,
        'gpt_response': response
    })

pd.DataFrame(results).to_csv(f"{folder}/relation_classification_few_shot_results.csv", index=False)

100%|██████████| 5102/5102 [45:09<00:00,  1.88it/s]

In [ ]:
results[0]

{'sentence': 'we want to do is commit more forces anywhere. [SEP] What I want the President to do, and I think he may have done it, his last statement, call for an unconditional end of the violence',
 'link_type': 0,
 'gpt_response': 'neither'}

# STANCE CLASSIFICATION

In [ ]:
instructions = (
    "You are a stance classification assistant. "
    "Your task is to identify the stance expressed in the given argument toward the topic. "
    "The topic is presented in the first sentence with the tag [TOPIC]. "
    "The argument follows, separated by [SEP]. "
    "Output 0 if the argument is against the topic, 1 if it is in favor of the topic, or 2 if it is neutral/irrelevant. "
    "Do not include any explanation, punctuation, or formatting—only output the digit 0, 1, or 2."
)

examples = (
    """Examples:
    1) Sentence: "TOPIC stability of the economy [SEP] ...one must ask how much money they must make to demonstrate that they are among the best managed companies on the planet. They must make enough money to insure that they can never fail and threaten the stability of the world's economy again. That much money."
    Output: 2

    2) Sentence: "TOPIC prostitution [SEP] Violence is inherent in the sex industry only in the same way that criminality is inherent in business in Russia. All private business in Russia was illegal under communism, so when communism fell, the first and strongest entrants were people from criminal backgrounds who had already been engaging in it illegally. They have not yet lost control."
    Output: 1

    3) Sentence: "TOPIC rim [SEP] Red Auerbach was asked about raising the rim to neutralize some of the supposed advantage held by taller players. He said, I think correctly, that raising the rim would increase that advantage, not decrease it. Are you advocating raising the rim only in the NBA? Should Division I programs also follow suit? Surely high school players would not want the rim raised, many of them short and landlocked. And how many players in the NBA cannot dunk? Nobody would be my guess. You want to neutralize the advantage of taller players? Box out. You want to bring back the mid-range jumper? Get rid of the 3-point shot. I disagree with you Mr. Monroe, but I loved that spin move (even though I think you traveled a lot of the time cupping the ball)."
    Output: 0
    """
)

In [ ]:
print(instructions)

You are a stance classification assistant. Your task is to identify the stance expressed in the given argument toward the topic. The topic is presented in the first sentence with the tag [TOPIC]. The argument follows, separated by [SEP]. Output 0 if the argument is against the topic, 1 if it is in favor of the topic, or 2 if it is neutral/irrelevant. Do not include any explanation, punctuation, or formatting—only output the digit 0, 1, or 2.

In [ ]:
dataset = pd.read_csv(f"{folder}/stance_detection/test.csv")
len(dataset)

2929

In [ ]:
dataset.head(5)

   label                                               text
0      1  TOPIC nuclear power [SEP] I totally agree with...
1      0  TOPIC illegal immigrants [SEP] Who is the mayo...
2      0  TOPIC illegal immigration [SEP] Who is the may...
3      0  TOPIC immigrant [SEP] Who is the mayor of N.Y....
4      0  TOPIC all immigrants [SEP] Who is the mayor of...

## Zero-Shot

In [ ]:
results = []
engine = "gpt-4.1-nano"
max_token = 50
temperature = 0.0  # Lower temp for consistency

for idx, row in tqdm(dataset.iterrows(), total=len(dataset)):
    sentence = row.text
    label = row.label
    response = openai_client.chat.completions.create(
        model=engine,
        messages=[{"role": "system", "content": instructions},
                  {"role": "user", "content": f"Sentence: {sentence}"}],
        max_tokens=max_token,
        temperature=temperature,
    ).choices[0].message.content.strip()
    results.append({
        'sentence': sentence,
        'link_type': label,
        'gpt_response': response
    })

pd.DataFrame(results).to_csv(f"{folder}/stance_detection_zero_shot_results.csv", index=False)

100%|██████████| 2929/2929 [22:14<00:00,  2.20it/s]

In [ ]:
results[0]

{'sentence': "TOPIC nuclear power [SEP] I totally agree with this premise. As a younger person I was against Nuclear power (I was in college during 3 mile island) but now it seems that nuclear should be in the mix. Fission technology is better, and will continue to get better if we actively promote its development. The prospect of fusion energy also needs to be explored. If it's good enough for the sun and the stars, it's good enough for me.",
 'link_type': 1,
 'gpt_response': '1'}

## Few-Shot

In [ ]:
instuctions_examples = f"{instructions}\n{examples.strip()}"
print(instuctions_examples)

You are a stance classification assistant. Your task is to identify the stance expressed in the given argument toward the topic. The topic is presented in the first sentence with the tag [TOPIC]. The argument follows, separated by [SEP]. Output 0 if the argument is against the topic, 1 if it is in favor of the topic, or 2 if it is neutral/irrelevant. Do not include any explanation, punctuation, or formatting—only output the digit 0, 1, or 2.
Examples:
    1) Sentence: "TOPIC stability of the economy [SEP] ...one must ask how much money they must make to demonstrate that they are among the best managed companies on the planet. They must make enough money to insure that they can never fail and threaten the stability of the world's economy again. That much money."
    Output: 2

    2) Sentence: "TOPIC prostitution [SEP] Violence is inherent in the sex industry only in the same way that criminality is inherent in business in Russia. All private business in Russia was illegal under communism, so when communism fell, the first and strongest entrants were people from criminal backgrounds who had already been engaging in it illegally. They have not yet lost control."
    Output: 1

    3) Sentence: "TOPIC rim [SEP] Red Auerbach was asked about raising the rim to neutralize some of the supposed advantage held by taller players. He said, I think correctly, that raising the rim would increase that advantage, not decrease it. Are you advocating raising the rim only in the NBA? Should Division I programs also follow suit? Surely high school players would not want the rim raised, many of them short and landlocked. And how many players in the NBA cannot dunk? Nobody would be my guess. You want to neutralize the advantage of taller players? Box out. You want to bring back the mid-range jumper? Get rid of the 3-point shot. I disagree with you Mr. Monroe, but I loved that spin move (even though I think you traveled a lot of the time cupping the ball)."
    Output: 0

In [ ]:
results = []
engine = "gpt-4.1-nano"
max_token = 50
temperature = 0.0  # Lower temp for consistency

for idx, row in tqdm(dataset.iterrows(), total=len(dataset)):
    sentence = row.text
    label = row.label
    response = openai_client.chat.completions.create(
        model=engine,
        messages=[{"role": "system", "content": instuctions_examples},
                  {"role": "user", "content": f"Sentence: {sentence}"}],
        max_tokens=max_token,
        temperature=temperature,
    ).choices[0].message.content.strip()
    results.append({
        'sentence': sentence,
        'label': label,
        'gpt_response': response
    })

pd.DataFrame(results).to_csv(f"{folder}/stance_detection_few_shot_results.csv", index=False)

100%|██████████| 2929/2929 [33:13<00:00,  1.47it/s]

In [ ]:
results[0]

{'sentence': "TOPIC nuclear power [SEP] I totally agree with this premise. As a younger person I was against Nuclear power (I was in college during 3 mile island) but now it seems that nuclear should be in the mix. Fission technology is better, and will continue to get better if we actively promote its development. The prospect of fusion energy also needs to be explored. If it's good enough for the sun and the stars, it's good enough for me.",
 'label': 1,
 'gpt_response': '1'}