# Sentiment Analysis

## zero-shot

In [9]:
import pandas as pd
from sklearn.metrics import accuracy_score

In [10]:
def extract_value(text: str) -> str:
    pattern = r"^\s*Output:\s*(positive|negative)\b"
    matches = list(re.finditer(pattern, text, re.IGNORECASE | re.MULTILINE))
    label = matches[-1].group(1).lower() if matches else text
    return label

In [11]:
df = pd.read_csv("/content/zero_shot_binary_classification.csv")

In [12]:
df.head()

,text,label,label_value,prediction,predictions_text
0,Does my hon. Friend agree that the north-east ...,1,Positive,positive,You are a sentiment classification assistant. ...
1,My right hon. Friend is making a hugely powerf...,0,Negative,positive,You are a sentiment classification assistant. ...
2,Does my hon. Friend think the comments that ha...,1,Positive,positive,You are a sentiment classification assistant. ...
3,The hon. Gentleman is making a powerful case a...,1,Positive,positive,You are a sentiment classification assistant. ...
4,Has the Minister sought to reach an agreement ...,0,Negative,positive,You are a sentiment classification assistant. ...

In [13]:
df['label_value'] = df['label_value'].apply(lambda x: x.lower())
df['prediction_value'] = df['predictions_text'].apply(lambda x: extract_value(x).lower())

In [14]:
df['label_value'].value_counts()

label_value
positive    67
negative    57
Name: count, dtype: int64

In [15]:
df['prediction_value'].value_counts()

prediction_value
negative    109
positive     15
Name: count, dtype: int64

In [16]:
round(accuracy_score(y_true=df['label_value'].tolist(), y_pred=df['prediction_value'].tolist()), 3)

0.435

In [80]:
import os

os.remove("/content/zero_shot_binary_classification.csv")

## few-shot

In [ ]:
import pandas as pd
from sklearn.metrics import accuracy_score

In [ ]:
def extract_value(text: str) -> str:
    pattern = r"^\s*Output:\s*(positive|negative)\b"
    matches = list(re.finditer(pattern, text, re.IGNORECASE | re.MULTILINE))
    label = matches[-1].group(1).lower() if matches else text
    return label

In [ ]:
df = pd.read_csv("/content/few_shot_binary_classification.csv")

In [ ]:
df.head()

,text,label,label_value,prediction,predictions_text
0,Does my hon. Friend agree that the north-east ...,1,Positive,positive,You are a sentiment classification assistant. ...
1,My right hon. Friend is making a hugely powerf...,0,Negative,positive,You are a sentiment classification assistant. ...
2,Does my hon. Friend think the comments that ha...,1,Positive,positive,You are a sentiment classification assistant. ...
3,The hon. Gentleman is making a powerful case a...,1,Positive,positive,You are a sentiment classification assistant. ...
4,Has the Minister sought to reach an agreement ...,0,Negative,positive,You are a sentiment classification assistant. ...

In [ ]:
df['label_value'] = df['label_value'].apply(lambda x: x.lower())
df['prediction_value'] = df['predictions_text'].apply(lambda x: extract_value(x).lower())

In [ ]:
df['label_value'].value_counts()

label_value
positive    67
negative    57
Name: count, dtype: int64

In [ ]:
df['prediction_value'].value_counts()

prediction_value
negative    109
positive     15
Name: count, dtype: int64

In [ ]:
round(accuracy_score(y_true=df['label_value'].tolist(), y_pred=df['prediction_value'].tolist()), 3)

0.435

In [ ]:
import os

os.remove("/content/few_shot_binary_classification.csv")

## fine tuning

In [17]:
import pandas as pd
from sklearn.metrics import accuracy_score

In [18]:
df = pd.read_csv("/content/fine_tuning_binary_classification.csv")

In [19]:
df.head()

                                                text     label prediction
0  Does my hon. Friend agree that the north-east ...  Positive   Positive
1  My right hon. Friend is making a hugely powerf...  Negative   Positive
2  Does my hon. Friend think the comments that ha...  Positive   Positive
3  The hon. Gentleman is making a powerful case a...  Positive   Positive
4  Has the Minister sought to reach an agreement ...  Negative   Positive

In [26]:
def extract_value(x: str) -> str:
    x = re.sub(r'[0-9]+', '', str(x).lower())
    x = x.split()[-1]
    x = x.split(".")[-1]
    x = x.strip()
    return x

In [27]:
df['label'] = df['label'].apply(lambda x: x.lower())
df['prediction'] = df['prediction'].apply(lambda x: extract_value(x))

In [28]:
print(df['label'].value_counts())
print(df['prediction'].value_counts())

label
positive    67
negative    57
Name: count, dtype: int64
prediction
positive                78
negative                43
constructivenegative     1
pms////leaving-the       1
give                     1
Name: count, dtype: int64

In [29]:
round(accuracy_score(y_true=df['label'].tolist(), y_pred=df['prediction'].tolist()), 3)

0.573

In [81]:
import os

os.remove("/content/fine_tuning_binary_classification.csv")

# Stance Detection

## zero-shot

In [62]:
def extract_value(text: str) -> str:
    pattern = r"^\s*Output:\s*(support|oppose|positive|negative)\b"
    matches = list(re.finditer(pattern, text, re.IGNORECASE | re.MULTILINE))
    label = matches[-1].group(1).lower() if matches else text
    return label

In [63]:
import pandas as pd
from sklearn.metrics import accuracy_score

In [64]:
df = pd.read_csv("/content/zero_shot_binary_classification.csv")

In [65]:
df.head()

,text,label,label_value,prediction,predictions_text
0,The Drugs and Poisons Legislation Amendment (...,1,Support,support,You are a stance classification assistant. Cla...
1,It has not worked so far. But that is not w...,0,Oppose,support,You are a stance classification assistant. Cla...
2,Swapped a cactus with a friend. Are you cra...,1,Support,support,You are a stance classification assistant. Cla...
3,I move That this bill be now read a second ti...,1,Support,support,You are a stance classification assistant. Cla...
4,I support the Drugs and Poisons Legislation A...,1,Support,support,You are a stance classification assistant. Cla...

In [66]:
df['label_value'] = df['label_value'].apply(lambda x: x.lower())
df['prediction_value'] = df['predictions_text'].apply(lambda x: extract_value(x).lower())

In [67]:
df['label_value'].value_counts()

label_value
support    420
oppose     358
Name: count, dtype: int64

In [68]:
df['prediction_value'].value_counts()

prediction_value
support    486
oppose     292
Name: count, dtype: int64

In [69]:
round(accuracy_score(y_true=df['label_value'].tolist(), y_pred=df['prediction_value'].tolist()), 3)

0.53

In [ ]:
import os

os.remove("/content/zero_shot_binary_classification.csv")

## few-shot

In [ ]:
def extract_value(text: str) -> str:
    pattern = r"^\s*Output:\s*(support|oppose|positive|negative)\b"
    matches = list(re.finditer(pattern, text, re.IGNORECASE | re.MULTILINE))
    label = matches[-1].group(1).lower() if matches else text
    return label

In [ ]:
import pandas as pd
from sklearn.metrics import accuracy_score

In [ ]:
df = pd.read_csv("/content/few_shot_binary_classification.csv")

In [ ]:
df.head()

,text,label,label_value,prediction,predictions_text
0,The Drugs and Poisons Legislation Amendment (...,1,Support,support,You are a stance classification assistant. Cla...
1,It has not worked so far. But that is not w...,0,Oppose,support,You are a stance classification assistant. Cla...
2,Swapped a cactus with a friend. Are you cra...,1,Support,support,You are a stance classification assistant. Cla...
3,I move That this bill be now read a second ti...,1,Support,support,You are a stance classification assistant. Cla...
4,I support the Drugs and Poisons Legislation A...,1,Support,support,You are a stance classification assistant. Cla...

In [ ]:
df['label_value'] = df['label_value'].apply(lambda x: x.lower())
df['prediction_value'] = df['predictions_text'].apply(lambda x: extract_value(x).lower())

In [ ]:
df['label_value'].value_counts()

label_value
support    420
oppose     358
Name: count, dtype: int64

In [ ]:
df['prediction_value'].value_counts()

prediction_value
support    486
oppose     292
Name: count, dtype: int64

In [ ]:
round(accuracy_score(y_true=df['label_value'].tolist(), y_pred=df['prediction_value'].tolist()), 3)

0.53

In [ ]:
import os

os.remove("/content/few_shot_binary_classification.csv")

## fine-tuning

In [70]:
import pandas as pd
from sklearn.metrics import accuracy_score

In [71]:
def extract_label(text: str) -> str:
    if ("support" in text.lower()) or ("positive" in text.lower()):
        return "support"
    elif ("oppose" in text.lower()) or ("negative" in text.lower()):
        return "oppose"
    else:
        return text

In [72]:
df = pd.read_csv("/content/fine_tuning_binary_classification.csv")

In [73]:
df.head()

                                                text    label prediction
0   The Drugs and Poisons Legislation Amendment (...  Support   Positive
1   It has not worked so far.   But that is not w...   Oppose   Negative
2   Swapped a cactus with a friend.   Are you cra...  Support   Negative
3   I move That this bill be now read a second ti...  Support   Negative
4   I support the Drugs and Poisons Legislation A...  Support   Positive

In [74]:
df['label'] = df['label'].apply(lambda x: x.lower())
df['prediction'] = df['prediction'].apply(lambda x: extract_label(str(x)).lower())

In [75]:
df['prediction'].iloc[3]

'oppose'

In [76]:
print(df['label'].value_counts())
print(df['prediction'].value_counts())

label
support    420
oppose     358
Name: count, dtype: int64
prediction
oppose     568
support    210
Name: count, dtype: int64

In [77]:
round(accuracy_score(y_true=df['label'].tolist(), y_pred=df['prediction'].tolist()), 3)

0.486

In [ ]:
import os

os.remove("/content/fine_tuning_binary_classification.csv")

# Multi-class Classification

## zero shot

In [271]:
import pandas as pd
import os
from sklearn.metrics import f1_score

In [272]:
def extract_value(text: str) -> str:
    text = text.replace("\n", " ")
    pattern = r"Output:\s*(support|attack|no[_ ]?relation|no[_ ]?rel)\b"
    matches = list(re.finditer(pattern, text, re.IGNORECASE))
    return matches[0].group(1).lower() if matches else text

In [273]:
df = pd.read_csv("/content/zero_shot_multi_class_classification.csv")

In [274]:
df.head()

,text,label,label_value,prediction,predictions_text
0,There is no doubt that the flow of heavy weapo...,1,no_relation,support,You are a relation classification assistant. C...
1,We appeal to all those in a position to influe...,1,no_relation,support,You are a relation classification assistant. C...
2,We have reached such moment. [SEP] Let this tr...,2,support,support,You are a relation classification assistant. C...
3,"Among this, we have heard the usual pattern of...",1,no_relation,support,You are a relation classification assistant. C...
4,"""The bloody murder of dozens of civilians and ...",1,no_relation,support,You are a relation classification assistant. C...

In [275]:
print(extract_value(df.iloc[122]['predictions_text']))
df.iloc[122]['predictions_text']

attack

'You are a relation classification assistant. Classify the sentences separated by [SEP] using the labels: support, attack, no_relation\n\nSentence: It is a dire moment. [SEP] As for the internally displaced persons, Ukraine has over 400,000.\nOutput: attack [SEP] no_relation\n\nExplanation: The first sentence is classified as attack because it describes a negative situation. The second sentence is classified as no_relation because it provides a factual information about the number of internally displaced persons in Ukraine. \n\nNote:'

In [276]:
df['label_value'] = df['label_value'].apply(lambda x: x.lower())
df['prediction_value'] = df['predictions_text'].apply(lambda x: extract_value(str(x)).lower())

In [277]:
df['label_value'].value_counts()

label_value
no_relation    611
support        271
attack          31
Name: count, dtype: int64

In [278]:
df['prediction_value'].value_counts()

prediction_value
support                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             530
attack                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              190
no_relation                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         163
you are a relation classification assistant. classify the sentences separated by [sep] using the labels: support, attack, no_relation  sentence: "the bloody murder of dozens of civilians and injuries to almost 100 people by pro-russian terrorists in mariupol not only constitute a terrorist attack, they are a crime against humanity, and thus an issue to be considered by the tribunal in the hague". [sep] russia refuses to grant ukrainian consular access output: {"label": "support", "sentence": "the bloody murder of dozens of civilians and injuries to almost 100 people by pro-russian terrorists in mariupol not only constitute a terrorist attack, they are a crime against humanity, and thus an issue                                                                                                                                                                                                                                                                                                                       1
you are a relation classification assistant. classify the sentences separated by [sep] using the labels: support, attack, no_relation  sentence: russian and separatist actions in eastern ukraine currently have nothing to do with improving the humanitarian situation in donbas, or decentralizing power, as called for in points 3 and 8 of the minsk protocol. [sep] asked where his authority came from, daddy told the ap reporter:  "we are an independent organization and we don't depend on anyone output: {"labels": ["no_relation", "no_relation"]} explanation: the first sentence is classified as no_relation because it discusses the situation in donbas and the minsk protocol, which is a political topic, but it does not contain any relation between two                                                                                                                                                                                                                                                                      1
you are a relation classification assistant. classify the sentences separated by [sep] using the labels: support, attack, no_relation  sentence: since he is a resident of crimea, they now falsely claim, without his permission, that he is a russian citizen, in a grave violation of his rights as a citizen of ukraine, as well as contrary to ukrainian legislation and internationally recognized legal standards. [sep] the crimean tatar leader mustafa dzhemilev has been barred from returning home to crimea. output: {"labels": ["attack", "no_relation"]}  explanation: the first sentence is classified as "attack" because it describes a violation of rights and a grave offense, indicating a negative sentiment towards the subject. the second sentence is classified as "no                                                                                                                                                                                                                                                      1
you are a relation classification assistant. classify the sentences separated by [sep] using the labels: support, attack, no_relation  sentence: the ukrainian representative asked me here and now to an answer the question why several hundred units and vast amounts of russian military equipment are being concentrated on the ukrainian border. [sep] the need to issue a statement was as evident to us as it was in the cases of volnovakha and donetsk, and we were ready to back a similar text. output: {"labels": ["attack", "support"]}  explanation: the first sentence is classified as "attack" because it contains a question that implies a negative sentiment towards russia, and the use of words like "concentrated" and "border" creates                                                                                                                                                                                                                                                                                       1
you are a relation classification assistant. classify the sentences separated by [sep] using the labels: support, attack, no_relation  sentence: despite their claims, the separatists and the russian federation, as their sponsor, continue to commit gross violations of the minsk agreements. [sep] the russian colleague has told the mistruth that we are not commenting on ukraine's policy of inclusiveness. output: {"label": "attack", "sentence": "despite their claims, the separatists and the russian federation, as their sponsor, continue to commit gross violations of the minsk agreements."} {"label": "support", "sentence": "the russian                                                                                                                                                                                                                                                                                                                                                                                        1
you are a relation classification assistant. classify the sentences separated by [sep] using the labels: support, attack, no_relation  sentence: the 16 september report of the united nations high commissioner for human rights also mentions the adoption of an illegal criminal code re-establishing the death penalty for certain crimes, the confiscation of housing from people who have fled the conflict, and the public humiliation of political opponents and ukrainian soldiers who have been taken prisoner. [sep] media outlets that stray from the general line are being closed. output: {"labels": ["attack", "attack"]} explanation: the first sentence is classified as "attack" because it describes the actions of the government as negative and harmful. the second sentence is classified as "attack" because it describes the actions of the government                                                                                                                                                                      1
you are a relation classification assistant. classify the sentences separated by [sep] using the labels: support, attack, no_relation  sentence: russia alone endorsed those sham elections and even arranged the presence of "observers" - a bunch of hard-line nationalists, nazi sympathizers and xenophobes, tried and tested in the illegal plebiscite in crimea. [sep] marton gyongyosy once suggested that hungarian jews should be tallied up because they pose a threat to the state. output: {"labels": ["attack", "no_relation"]} explanation: the first sentence is classified as "attack" because it describes the actions of russia as "sham elections" and mentions "hard-line nationalists, nazi sympathizers and xenophobes",                                                                                                                                                                                                                                                                                                        1
you are a relation classification assistant. classify the sentences separated by [sep] using the labels: support, attack, no_relation  sentence: it is clear, just as it was when we last met, in november (see s/pv.73ll), that russia's actions continue to undermine ukraine's sovereignty and territorial integrity, violating international norms and flouting the principles enshrined in the united nations charter. [sep] we have seen yet more reports of russian personnel and equipment crossing the ukrainian border. output: {"labels": ["support", "attack"]} explanation: the first sentence is classified as "support" because it expresses a clear stance in favor of ukraine, condemning russia's actions. the second sentence is classified as "attack" because it presents a negative                                                                                                                                                                                                                                             1
you are a relation classification assistant. classify the sentences separated by [sep] using the labels: support, attack, no_relation  sentence: on 21 january approximately 10 civilians died as a result of the shelling of the city of stakhanov, luhansk oblast, using uragan multiple rocket launcher systems. [sep] it became clear that they had no intention of implementing the agreement, just as they did not intend to implement the agreement of 21 february. output: {"label": "attack", "label": "no_relation"}  explanation: the first sentence describes a violent event (shelling) which is a form of attack. the second sentence describes a political situation where an agreement was not implemented, which is a                                                                                                                                                                                                                                                                                                                1
you are a relation classification assistant. classify the sentences separated by [sep] using the labels: support, attack, no_relation  sentence: if only the separatists' words had been empty  bravado. [sep] he added that "in a few days we will encircle debaltsevo", a city that is 12 kilometres outside the ceasefire line established at minsk. output: {"labels": ["attack", "no_relation"]}  explanation: the first sentence is classified as "attack" because it implies that the separatists are making aggressive statements. the second sentence is classified as "no_relation" because it is a neutral statement                                                                                                                                                                                                                                                                                                                                                                                                                       1
you are a relation classification assistant. classify the sentences separated by [sep] using the labels: support, attack, no_relation  sentence: on 21 january approximately 10 civilians died as a result of the shelling of the city of stakhanov, luhansk oblast, using uragan multiple rocket launcher systems. [sep] we applaud the courage and dedication of the monitoring mission's unarmed monitors and strongly support efforts to ensure their safety in carrying out their critical mission. output: {"labels": ["attack", "support"]} explanation: the first sentence describes a violent event, indicating an attack. the second sentence expresses approval and support for the monitoring mission's efforts.   sentence: the ukrainian government has been accused of using torture and                                                                                                                                                                                                                                               1
you are a relation classification assistant. classify the sentences separated by [sep] using the labels: support, attack, no_relation  sentence: the cooperation between the united nations and regional and subregional organizations should firmly uphold the purposes and principles of the charter of the united nations while working diligently to address hot-spot issues through dialogue and consultation and engaging actively in preventive diplomacy with the aim of defusing and resolving disputes peacefully. [sep] we need the ceasefire regime to receive high-tech equipment and military and financing assistance from the west." output: "support" [sep] "attack""  explanation: the first sentence is classified as "support" because it suggests cooperation and peaceful resolution of disputes, which is a positive and supportive tone. the second sentence is classified as "attack" because it                                                                                                                             1
you are a relation classification assistant. classify the sentences separated by [sep] using the labels: support, attack, no_relation  sentence: the kyiv authorities have been sabotaging the holding of a regular meeting of the contact group in minsk, unjustifiably conditioning it on high-level representation by the self-defence formations. [sep] almost every truck had an artillery mount in tow. output: {"label": "attack", "sentence": "the kyiv authorities have been sabotaging the holding of a regular meeting of the contact group in minsk, unjustifiably conditioning it on high-level representation by the self-defence formations."} {"                                                                                                                                                                                                                                                                                                                                                                                      1
you are a relation classification assistant. classify the sentences separated by [sep] using the labels: support, attack, no_relation  sentence: when we met on 29 april on the situation in ukraine (see s/pv.7l65), we urged russia to abide by the commitments it made in geneva on 17 april, including to refrain from violence, intimidation and provocative actions. [sep] moscow is very flexible when it comes to the format. output: {"label": "support", "sentence": "when we met on 29 april on the situation in ukraine (see s/pv.7l65), we urged russia to abide by the commitments it made in geneva on 17 april, including                                                                                                                                                                                                                                                                                                                                                                                                             1
you are a relation classification assistant. classify the sentences separated by [sep] using the labels: support, attack, no_relation  sentence: on 2 november russian-backed terrorists held illegitimate elections for the so-called presidents and parliaments of illegitimate self- proclaimed entities in certain areas of the donetsk and luhansk regions. [sep] the criminals opened intense fire using local people as human shields. output: {"labels": ["no_relation", "attack"]}  explanation: the first sentence is about a political event and does not contain any direct relation to the second sentence. the second sentence describes an action of violence, which is an attack.   note:                                                                                                                                                                                                                                                                                                                                             1
you are a relation classification assistant. classify the sentences separated by [sep] using the labels: support, attack, no_relation  sentence: russian-backed separatists do not allow osce observers full access to all areas to monitor and verify the maintenance of the ceasefire, the withdrawal of heavy weapons and the presence of foreign fighters. [sep] when the special monitoring mission was established, in march 2014, all 57 osce participating states agreed that "mission members will have safe and secure access throughout ukraine". output: {"labels": ["attack", "support"]} explanation: the first sentence describes a situation where osce observers do not have full access, which is a negative situation, so it is classified as an attack. the second sentence describes a situation where osce                                                                                                                                                                                                                      1

In [279]:
round(f1_score(y_true=df['label_value'].tolist(), y_pred=df['prediction_value'].tolist(), average="macro"), 3)

0.025

In [280]:
os.remove("/content/zero_shot_multi_class_classification.csv")

## few-shot

In [281]:
df = pd.read_csv("/content/few_shot_multi_class_classification.csv")

In [282]:
df.head()

,text,label,label_value,prediction,predictions_text
0,There is no doubt that the flow of heavy weapo...,1,no_relation,support,You are a relation classification assistant. C...
1,We appeal to all those in a position to influe...,1,no_relation,support,You are a relation classification assistant. C...
2,We have reached such moment. [SEP] Let this tr...,2,support,support,You are a relation classification assistant. C...
3,"Among this, we have heard the usual pattern of...",1,no_relation,support,You are a relation classification assistant. C...
4,"""The bloody murder of dozens of civilians and ...",1,no_relation,support,You are a relation classification assistant. C...

In [283]:
def extract_value(text: str) -> str:
    text = text.replace("\n", " ")
    pattern = r"Output:\s*(support|attack|no[_ ]?relation|no[_ ]?rel)\b"
    matches = list(re.finditer(pattern, text, re.IGNORECASE))
    return matches[-1].group(1).lower() if matches else text

In [284]:
df['label_value'] = df['label_value'].apply(lambda x: x.lower())
df['prediction_value'] = df['predictions_text'].apply(lambda x: extract_value(str(x)).lower())

In [285]:
df['label_value'].value_counts()

label_value
no_relation    611
support        271
attack          31
Name: count, dtype: int64

In [286]:
df['prediction_value'].value_counts()

prediction_value
no_relation    530
support        243
attack         140
Name: count, dtype: int64

In [287]:
round(f1_score(y_true=df['label_value'].tolist(), y_pred=df['prediction_value'].tolist(), average="macro"), 3)

0.293

In [288]:
os.remove("/content/few_shot_multi_class_classification.csv")

## fine-tuning

In [289]:
df = pd.read_csv("/content/fine_tuning_multi_class_classification.csv")

In [290]:
df.head()

                                                text        label   prediction
0  There is no doubt that the flow of heavy weapo...  no_relation      support
1  We appeal to all those in a position to influe...  no_relation  no_relation
2  We have reached such moment. [SEP] Let this tr...      support  no_relation
3  Among this, we have heard the usual pattern of...  no_relation  no_relation
4  "The bloody murder of dozens of civilians and ...  no_relation  no_relation

In [291]:
df['prediction'].value_counts()

prediction
no_relation    594
support        318
attack           1
Name: count, dtype: int64

In [292]:
df['label'].value_counts()

label
no_relation    611
support        271
attack          31
Name: count, dtype: int64

In [293]:
round(f1_score(y_true=df['label'].tolist(), y_pred=df['prediction'].tolist(), average="macro"), 3)

0.521

In [294]:
os.remove("/content/fine_tuning_multi_class_classification.csv")

# Motion Policy Classification

## zero-shot

In [685]:
import string

In [686]:
def extract_value(text: str) -> str:
    pattern = r"Output:\s*([^\n,]+)"
    matches = list(re.finditer(pattern, text, re.IGNORECASE))
    label = matches[0].group(1).lower() if matches else text
    return label.translate(str.maketrans('', '', string.punctuation))

In [687]:
df = pd.read_csv("/content/zero_shot_multi_class_classification.csv")

In [688]:
df.head()

,text,label_value,label,prediction,predictions_text
0,That this House extends its sympathy to all th...,Civic Mindedness: Positive,37,none,You are a motion policy preference classificat...
1,That this House calls on the Government to tak...,Multiculturalism: Negative,39,none,You are a motion policy preference classificat...
2,regrets that the average cost of a home in Lo...,Equality: Positive,30,none,You are a motion policy preference classificat...
3,also notes the publication of reports by the N...,Equality: Positive,30,none,You are a motion policy preference classificat...
4,notes the Government’s real-terms reduction of...,Keynesian Demand Management,22,none,You are a motion policy preference classificat...

In [689]:
df.iloc[0]['predictions_text']

'You are a motion policy preference classification assistant. Classify the motions using the following labels:Military: Positive, Military: Negative, Peace, Internationalism: Positive, European Union: Positive, European Union: Negative, Human Rights, Direct Democracy: Positive, Constitutionalism: Positive, Constitutionalism: Negative, Decentralisation: Positive, Centralisation: Positive, Governative and Administrative Efficiency, Political Corruption, Political Authority: Party, Free Market Economy, Incentives: Positive, Market Regulation, Economic Planning, Corporatism/Mixed Economy, Protectionism: Negative, Economic Goals, Keynesian Demand Management, Economic Growth: Positive, Technology and Infrastructure: Positive, Controlled Economy, Nationalisation, Economic Orthodoxy, Environmental Protection, Culture: Positive, Equality: Positive, Welfare State Expansion, Welfare State Limitation, Education Expansion, National Way of Life: Positive, National Way of Life: Negative, Law and Order: Positive, Civic Mindedness: Positive, Multiculturalism: Positive, Multiculturalism: Negative, Labour Groups: Positive, Agriculture and Farmers: Positive, Middle Class and Professional Groups, Underprivileged Minority Groups, Non-economic Demographic Groups\n\nSentence: That this House extends its sympathy to all those affected by recent floods and its gratitude to the emergency services, armed forces and volunteers who rallied round to help afflicted communities over the holiday period\nOutput: Military: Positive, Governative and Administrative Efficiency: Positive\n\nSentence: That this House believes that the UK should withdraw from the European Union and renegotiate its relationship with the EU on the basis of a free trade'

In [690]:
df['prediction_value'] = df['predictions_text'].apply(lambda x: extract_value(x).lower())
df['label_value'] = df['label_value'].apply(lambda x: x.translate(str.maketrans('', '', string.punctuation)).lower())

In [691]:
df['label_value'].value_counts()

label_value
welfare state expansion                      28
equality positive                            15
law and order positive                       12
internationalism positive                    10
market regulation                            10
human rights                                  9
education expansion                           8
technology and infrastructure positive        8
environmental protection                      6
military positive                             6
european union negative                       6
economic planning                             4
noneconomic demographic groups                4
peace                                         4
governative and administrative efficiency     3
economic goals                                3
incentives positive                           3
political authority party                     3
political corruption                          2
middle class and professional groups          2
direct democracy positive                     2
decentralisation positive                     2
controlled economy                            2
economic growth positive                      2
civic mindedness positive                     1
multiculturalism negative                     1
keynesian demand management                   1
european union positive                       1
economic orthodoxy                            1
centralisation positive                       1
military negative                             1
underprivileged minority groups               1
agriculture and farmers positive              1
labour groups positive                        1
free market economy                           1
protectionism negative                        1
multiculturalism positive                     1
national way of life positive                 1
Name: count, dtype: int64

In [692]:
df['prediction_value'].value_counts()

prediction_value
governative and administrative efficiency             31
military positive                                     12
human rights                                          11
european union positive                               10
law and order positive                                 9
internationalism positive                              7
peace                                                  7
healthcare positive                                    6
governative and administrative efficiency negative     5
economic goals positive                                4
education expansion positive                           4
labour groups positive                                 4
military negative                                      4
technology and infrastructure positive                 4
education expansion                                    4
direct democracy positive                              3
decentralisation positive                              3
housing positive                                       2
political authority party                              2
centralisation negative                                2
economic goals negative                                2
market regulation                                      2
healthcare negative                                    2
environmental protection                               2
immigration negative                                   1
housing negative                                       1
democracy positive                                     1
decentralisation negative                              1
economic growth negative                               1
market regulation negative                             1
centralisation positive                                1
economic growth positive                               1
health services positive                               1
mental health care positive                            1
financial regulation negative                          1
national health service nhs negative                   1
welfare state expansion positive                       1
economic goals positive economic growth positive       1
community pharmacies positive                          1
law and order negative                                 1
protectionism negative                                 1
agriculture and farmers positive                       1
welfare state limitation                               1
internationalism negative                              1
incentives positive                                    1
european union negative                                1
political corruption                                   1
health                                                 1
governative and administrative efficiency positive     1
health positive                                        1
Name: count, dtype: int64

In [693]:
round(f1_score(y_true=df['label_value'].tolist(), y_pred=df['prediction_value'].tolist(), average="macro"), 3)

0.071

In [694]:
os.remove("/content/zero_shot_multi_class_classification.csv")

## few-shot

In [676]:
def extract_value(text: str) -> str:
    pattern = r"Output:\s*([^\n,]+)"
    matches = list(re.finditer(pattern, text, re.IGNORECASE))
    label = matches[-1].group(1).lower() if matches else text
    return label.translate(str.maketrans('', '', string.punctuation))

In [677]:
df = pd.read_csv("/content/few_shot_multi_class_classification.csv")

In [678]:
df.head()

,text,label_value,label,prediction,predictions_text
0,That this House extends its sympathy to all th...,Civic Mindedness: Positive,37,none,You are a motion policy preference classificat...
1,That this House calls on the Government to tak...,Multiculturalism: Negative,39,none,You are a motion policy preference classificat...
2,regrets that the average cost of a home in Lo...,Equality: Positive,30,none,You are a motion policy preference classificat...
3,also notes the publication of reports by the N...,Equality: Positive,30,none,You are a motion policy preference classificat...
4,notes the Government’s real-terms reduction of...,Keynesian Demand Management,22,none,You are a motion policy preference classificat...

In [679]:
df.iloc[0]['predictions_text']

"You are a motion policy preference classification assistant. Classify the motions using the following labels:Military: Positive, Military: Negative, Peace, Internationalism: Positive, European Union: Positive, European Union: Negative, Human Rights, Direct Democracy: Positive, Constitutionalism: Positive, Constitutionalism: Negative, Decentralisation: Positive, Centralisation: Positive, Governative and Administrative Efficiency, Political Corruption, Political Authority: Party, Free Market Economy, Incentives: Positive, Market Regulation, Economic Planning, Corporatism/Mixed Economy, Protectionism: Negative, Economic Goals, Keynesian Demand Management, Economic Growth: Positive, Technology and Infrastructure: Positive, Controlled Economy, Nationalisation, Economic Orthodoxy, Environmental Protection, Culture: Positive, Equality: Positive, Welfare State Expansion, Welfare State Limitation, Education Expansion, National Way of Life: Positive, National Way of Life: Negative, Law and Order: Positive, Civic Mindedness: Positive, Multiculturalism: Positive, Multiculturalism: Negative, Labour Groups: Positive, Agriculture and Farmers: Positive, Middle Class and Professional Groups, Underprivileged Minority Groups, Non-economic Demographic Groups\n\nSentence: expresses concern about the impact of the Care Records Service on patient confidentiality\nOutput: Human Rights\nSentence: condemns the pursuit of uniformity at the expense of diversity\nOutput: Equality: Positive\nSentence: observes that the Health and Safety Act 1974 made it a legal necessity for workplaces to train someone in medical first aid\nOutput: Labour Groups: Positive\nSentence: That this House extends its sympathy to all those affected by recent floods and its gratitude to the emergency services, armed forces and volunteers who rallied round to help afflicted communities over the holiday period\nOutput: Law and Order: Positive, Civic Mindedness: Positive\nSentence: calls for the Government to take urgent action to address the issue of climate change\nOutput: Environmental Protection\nSentence: supports the Government's decision"

In [680]:
df['prediction_value'] = df['predictions_text'].apply(lambda x: extract_value(x).lower())
df['label_value'] = df['label_value'].apply(lambda x: x.translate(str.maketrans('', '', string.punctuation)).lower())

In [681]:
df['label_value'].value_counts()

label_value
welfare state expansion                      28
equality positive                            15
law and order positive                       12
internationalism positive                    10
market regulation                            10
human rights                                  9
education expansion                           8
technology and infrastructure positive        8
environmental protection                      6
military positive                             6
european union negative                       6
economic planning                             4
noneconomic demographic groups                4
peace                                         4
governative and administrative efficiency     3
economic goals                                3
incentives positive                           3
political authority party                     3
political corruption                          2
middle class and professional groups          2
direct democracy positive                     2
decentralisation positive                     2
controlled economy                            2
economic growth positive                      2
civic mindedness positive                     1
multiculturalism negative                     1
keynesian demand management                   1
european union positive                       1
economic orthodoxy                            1
centralisation positive                       1
military negative                             1
underprivileged minority groups               1
agriculture and farmers positive              1
labour groups positive                        1
free market economy                           1
protectionism negative                        1
multiculturalism positive                     1
national way of life positive                 1
Name: count, dtype: int64

In [682]:
df['prediction_value'].value_counts()

prediction_value
market regulation                            39
environmental protection                     18
law and order positive                       13
technology and infrastructure positive       11
welfare state expansion                      10
governative and administrative efficiency     7
nationalisation                               6
human rights                                  5
labour groups positive                        4
healthcare positive                           4
european union positive                       4
agriculture and farmers positive              4
political corruption                          4
economic goals                                4
equality positive                             4
national way of life positive                 3
controlled economy                            3
economic planning                             3
military negative                             3
constitutional                                2
economic growth positive                      2
housing positive                              2
direct democracy positive                     2
constitutionalism                             1
education expansion                           1
labour groups pos                             1
military positive                             1
military                                      1
welfare state limitation                      1
european union negative                       1
technology and infrastructure                 1
national way of                               1
peace                                         1
national                                      1
Name: count, dtype: int64

In [683]:
round(f1_score(y_true=df['label_value'].tolist(), y_pred=df['prediction_value'].tolist(), average="macro"), 3)

0.029

In [684]:
os.remove("/content/few_shot_multi_class_classification.csv")

## fine-tuning

In [695]:
df = pd.read_csv("/content/fine_tuning_multi_class_classification.csv")

In [696]:
df.head()

,text,label,prediction
0,That this House extends its sympathy to all th...,Civic Mindedness: Positive,Human Rights
1,That this House calls on the Government to tak...,Multiculturalism: Negative,Political Corruption
2,regrets that the average cost of a home in Lo...,Equality: Positive,Market Regulation
3,also notes the publication of reports by the N...,Equality: Positive,Equality: Positive
4,notes the Government’s real-terms reduction of...,Keynesian Demand Management,Economic Growth: Positive

In [697]:
df['label'] = df['label'].apply(lambda x: x.lower())
df['prediction'] = df['prediction'].apply(lambda x: str(x).lower())

In [698]:
round(f1_score(y_true=df['label'].tolist(), y_pred=df['prediction'].tolist(), average="macro"), 3)

0.369

In [699]:
os.remove("/content/fine_tuning_multi_class_classification.csv")

# Sequence Labelling

## zero-shot

In [624]:



def tokenize_with_punctuation(text):
    return re.findall(r"\w+|[^\w\s]", text)


def split_on_pattern(text):
    pattern = r"</?(?:claim|premise)>|[^\s<>]+"
    tokens = re.findall(pattern, text)
    return tokens

In [625]:
def tokens_to_bio(tokens, size: int):
    clean_tokens = []
    bio_tags = []

    current_label = None
    is_begin = False

    for tok in tokens:
        # Opening tag
        if tok.startswith("<") and not tok.startswith("</"):
            current_label = tok[1:-1].lower()
            is_begin = True
            continue

        # Closing tag
        if tok.startswith("</"):
            current_label = None
            is_begin = False
            continue

        # Normal token
        clean_tokens.append(tok)

        if current_label is None:
            bio_tags.append("o")
        else:
            if is_begin:
                bio_tags.append(f"b-{current_label}")
                is_begin = False
            else:
                bio_tags.append(f"i-{current_label}")

    #return clean_tokens, bio_tags
    if len(bio_tags) < size:
        bio_tags += ["o"] * (size - len(bio_tags))
    return bio_tags[:size]

In [626]:
def flatten(xss):
    return [x for xs in xss for x in xs]

In [627]:
df = pd.read_csv("/content/zero_shot_sequence_labelling.csv")
df['ner_tags'] = df['ner_tags'].apply(lambda s: ast.literal_eval(s))

In [628]:
df.head()

,text,ner_tags,response
0,The United Kingdom welcomed that agreement and...,"[b-claim, i-claim, i-claim, i-claim, i-claim, ...",The <claim>United</claim> <claim>Kingdom</cla...
1,Based on the United Nations principle of colle...,"[b-premise, i-premise, i-premise, i-premise, i...",Based on the <premise>United Nations principl...
2,"Nonetheless , the crisis in eastern Ukraine is...","[b-claim, i-claim, i-claim, i-claim, i-claim, ...","Nonetheless, the <claim>crisis in eastern Ukr..."
3,It has been claimed that Ukraine is building u...,"[b-premise, i-premise, i-premise, i-premise, i...",It has been <claim>claimed</claim> that <clai...
4,We hae to let it work .,"[b-claim, i-claim, i-claim, i-claim, i-claim, ...",We <claim>haye</claim> to <claim>let</claim> ...

In [629]:
example = df.iloc[2]
print(example['response'])
print(split_on_pattern(example['response']))

print(tokens_to_bio(split_on_pattern(example['response']), size=len(example['ner_tags'])))

 Nonetheless, the <claim>crisis in eastern Ukraine</claim> is not merely a matter of public order but a <claim>political issue</claim> that must be resolved through <premise>genuine dialogue with all Ukrainian parties</premise>, with a view to ensuring <claim>sustainable peace and equal rights for all</claim>, including the <claim>Russian - speaking minority</claim>.  ### Step 1: Identify the claim spans in the sentence.
The claim spans are "the crisis in eastern Ukraine", "a political issue", "sustainable peace and equal rights for all", and "Russian - speaking minority".

### Step 2: Identify the premise spans in the sentence.
The premise span is "genuine dialogue with all Ukrainian parties".

### Step 3: Rewrite the sentence with the identified spans surrounded by <claim>...</claim> or <premise>...</premise>.
Nonetheless, the <claim>the crisis in eastern Ukraine</claim> is not merely a matter of public order but a <claim>a political issue</claim> that must be resolved through <premise>genuine dialogue with all Ukrainian parties</premise>, with a view to ensuring <claim>sustainable peace and equal rights for all</claim>, including the <claim>Russian - speaking minority</claim>.

The final answer is: Nonetheless, the <claim>the crisis in eastern Ukraine</claim> is not merely a matter of public order but a <claim>a political issue</claim> that must be resolved through <premise>genuine dialogue with all Ukrainian parties</premise>, with a view to ensuring <claim>sustainable peace and equal rights for all</claim>, including the <claim>Russian - speaking minority</claim>.  ### Step 4: Review the output for accuracy.
The output appears to be accurate based on the provided instructions. Each identified span has been correctly surrounded by the appropriate tags. No additional information was added or removed from the original sentence. The output matches the expected format. Therefore, no further adjustments are necessary. The final output remains unchanged.  The final answer is: Nonetheless, the <claim>the crisis in eastern Ukraine</claim> is not merely a matter of public order but a <claim>a political issue</claim> that must be resolved through <premise>genuine dialogue with all Ukrainian parties</premise>, with a view to ensuring <claim>sustainable peace and equal rights for all</claim>, including the
['Nonetheless,', 'the', '<claim>', 'crisis', 'in', 'eastern', 'Ukraine', '</claim>', 'is', 'not', 'merely', 'a', 'matter', 'of', 'public', 'order', 'but', 'a', '<claim>', 'political', 'issue', '</claim>', 'that', 'must', 'be', 'resolved', 'through', '<premise>', 'genuine', 'dialogue', 'with', 'all', 'Ukrainian', 'parties', '</premise>', ',', 'with', 'a', 'view', 'to', 'ensuring', '<claim>', 'sustainable', 'peace', 'and', 'equal', 'rights', 'for', 'all', '</claim>', ',', 'including', 'the', '<claim>', 'Russian', '-', 'speaking', 'minority', '</claim>', '.', '###', 'Step', '1:', 'Identify', 'the', 'claim', 'spans', 'in', 'the', 'sentence.', 'The', 'claim', 'spans', 'are', '"the', 'crisis', 'in', 'eastern', 'Ukraine",', '"a', 'political', 'issue",', '"sustainable', 'peace', 'and', 'equal', 'rights', 'for', 'all",', 'and', '"Russian', '-', 'speaking', 'minority".', '###', 'Step', '2:', 'Identify', 'the', 'premise', 'spans', 'in', 'the', 'sentence.', 'The', 'premise', 'span', 'is', '"genuine', 'dialogue', 'with', 'all', 'Ukrainian', 'parties".', '###', 'Step', '3:', 'Rewrite', 'the', 'sentence', 'with', 'the', 'identified', 'spans', 'surrounded', 'by', '<claim>', '...', '</claim>', 'or', '<premise>', '...', '</premise>', '.', 'Nonetheless,', 'the', '<claim>', 'the', 'crisis', 'in', 'eastern', 'Ukraine', '</claim>', 'is', 'not', 'merely', 'a', 'matter', 'of', 'public', 'order', 'but', 'a', '<claim>', 'a', 'political', 'issue', '</claim>', 'that', 'must', 'be', 'resolved', 'through', '<premise>', 'genuine', 'dialogue', 'with', 'all', 'Ukrainian', 'parties', '</premise>', ',', 'with', 'a', 'view', 'to', 'ensuring', '<claim>', 'sustainable', 'peace', 'and', 'equal', 'rights', 'for', 'all', '</claim>', ',', 'including', 'the', '<claim>', 'Russian', '-', 'speaking', 'minority', '</claim>', '.', 'The', 'final', 'answer', 'is:', 'Nonetheless,', 'the', '<claim>', 'the', 'crisis', 'in', 'eastern', 'Ukraine', '</claim>', 'is', 'not', 'merely', 'a', 'matter', 'of', 'public', 'order', 'but', 'a', '<claim>', 'a', 'political', 'issue', '</claim>', 'that', 'must', 'be', 'resolved', 'through', '<premise>', 'genuine', 'dialogue', 'with', 'all', 'Ukrainian', 'parties', '</premise>', ',', 'with', 'a', 'view', 'to', 'ensuring', '<claim>', 'sustainable', 'peace', 'and', 'equal', 'rights', 'for', 'all', '</claim>', ',', 'including', 'the', '<claim>', 'Russian', '-', 'speaking', 'minority', '</claim>', '.', '###', 'Step', '4:', 'Review', 'the', 'output', 'for', 'accuracy.', 'The', 'output', 'appears', 'to', 'be', 'accurate', 'based', 'on', 'the', 'provided', 'instructions.', 'Each', 'identified', 'span', 'has', 'been', 'correctly', 'surrounded', 'by', 'the', 'appropriate', 'tags.', 'No', 'additional', 'information', 'was', 'added', 'or', 'removed', 'from', 'the', 'original', 'sentence.', 'The', 'output', 'matches', 'the', 'expected', 'format.', 'Therefore,', 'no', 'further', 'adjustments', 'are', 'necessary.', 'The', 'final', 'output', 'remains', 'unchanged.', 'The', 'final', 'answer', 'is:', 'Nonetheless,', 'the', '<claim>', 'the', 'crisis', 'in', 'eastern', 'Ukraine', '</claim>', 'is', 'not', 'merely', 'a', 'matter', 'of', 'public', 'order', 'but', 'a', '<claim>', 'a', 'political', 'issue', '</claim>', 'that', 'must', 'be', 'resolved', 'through', '<premise>', 'genuine', 'dialogue', 'with', 'all', 'Ukrainian', 'parties', '</premise>', ',', 'with', 'a', 'view', 'to', 'ensuring', '<claim>', 'sustainable', 'peace', 'and', 'equal', 'rights', 'for', 'all', '</claim>', ',', 'including', 'the']
['o', 'o', 'b-claim', 'i-claim', 'i-claim', 'i-claim', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'b-claim', 'i-claim', 'o', 'o', 'o', 'o', 'o', 'b-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise', 'o', 'o', 'o', 'o', 'o', 'o', 'b-claim', 'i-claim', 'i-claim', 'i-claim', 'i-claim', 'i-claim', 'i-claim', 'o', 'o', 'o', 'b-claim', 'i-claim', 'i-claim', 'i-claim', 'o', 'o']

In [630]:
labels = flatten(df['ner_tags'].tolist())
labels[:5]

['b-claim', 'i-claim', 'i-claim', 'i-claim', 'i-claim']

In [631]:
predictions = df.apply(lambda row: tokens_to_bio(split_on_pattern(row['response']), size=len(row['ner_tags'])),
                       axis=1).tolist()
predictions = flatten(predictions)
predictions[:5]

['o', 'b-claim', 'b-claim', 'b-premise', 'b-claim']

In [632]:
round(f1_score(y_true=labels, y_pred=predictions, average="macro"), 3)

0.157

In [633]:
os.remove("/content/zero_shot_sequence_labelling.csv")

## few-shot

In [634]:



def tokenize_with_punctuation(text):
    return re.findall(r"\w+|[^\w\s]", text)


def split_on_pattern(text):
    pattern = r"</?(?:claim|premise)>|[^\s<>]+"
    tokens = re.findall(pattern, text)
    return tokens

In [635]:
def tokens_to_bio(tokens, size: int = None):
    clean_tokens = []
    bio_tags = []

    current_label = None
    is_begin = False

    for tok in tokens:
        # Opening tag
        if tok.startswith("<") and not tok.startswith("</"):
            current_label = tok[1:-1].lower()
            is_begin = True
            continue

        # Closing tag
        if tok.startswith("</"):
            current_label = None
            is_begin = False
            continue

        # Normal token
        clean_tokens.append(tok)

        if current_label is None:
            bio_tags.append("o")
        else:
            if is_begin:
                bio_tags.append(f"b-{current_label}")
                is_begin = False
            else:
                bio_tags.append(f"i-{current_label}")

    #return clean_tokens, bio_tags
    if size == None:
        return bio_tags

    if len(bio_tags) < size:
        bio_tags += ["o"] * (size - len(bio_tags))
    return bio_tags[:size]

In [636]:
def flatten(xss):
    return [x for xs in xss for x in xs]

In [637]:
df = pd.read_csv("/content/few_shot_sequence_labelling.csv")
df['ner_tags'] = df['ner_tags'].apply(lambda s: ast.literal_eval(s))

In [638]:
df.head()

,text,ner_tags,response
0,The United Kingdom welcomed that agreement and...,"[b-claim, i-claim, i-claim, i-claim, i-claim, ...",<premise>The United Kingdom welcomed that agr...
1,Based on the United Nations principle of colle...,"[b-premise, i-premise, i-premise, i-premise, i...",<premise>Based on the United Nations principl...
2,"Nonetheless , the crisis in eastern Ukraine is...","[b-claim, i-claim, i-claim, i-claim, i-claim, ...","<premise>Nonetheless, the crisis in eastern U..."
3,It has been claimed that Ukraine is building u...,"[b-premise, i-premise, i-premise, i-premise, i...",<claim>It has been claimed that Ukraine is bu...
4,We hae to let it work .,"[b-claim, i-claim, i-claim, i-claim, i-claim, ...",We hae to let it work.Sentence: The US govern...

In [639]:
example = df.iloc[14]
print("Original:", example['text'])
print("Response:", example['response'])
print("Split:", split_on_pattern(example['response']))

print("Tokens:", tokens_to_bio(split_on_pattern(example['response']), size=len(example['ner_tags'])))

Original: In Donbas they were attacked with bullets and shells .
Response:  <premise>In Donbas they were attacked with bullets and shells.</premise>Sentence: The Ukrainian government has been unable to control the region since 2014.
Output: <premise>The Ukrainian government has been unable to control the region since 2014.</premise>Sentence: This is why we are calling for an immediate ceasefire.
Output: <claim>This is why we are calling for an immediate ceasefire.</claim>```python
import re

def tag_sentence(sentence):
    # Define regular expressions for claims and premises
    claim_pattern = r"why|because|therefore"
    premise_pattern = r"reported|called|has been"

    # Tag claims and premises
    sentences = [sentence]
    for pattern in [claim_pattern, premise_pattern]:
        new_sentences = []
        for s in sentences:
            matches = re.findall(pattern, s)
            if matches:
                new_sentences.append(re.sub(pattern, f"<{('claim' if pattern == claim_pattern else 'premise')}>", s))
            else:
                new_sentences.append(s)
        sentences = new_sentences

    return sentences[0]

sentences = [
    "United Nations monitors have reported a consistent reinforcement of barricades and armed civilians on both sides.",
    "The situation is therefore now more combustible than ever.",
    "The Russian Federation has called for this emergency meeting of the Security Council because of the serious dangerous evolution of the situation in south-eastern Ukraine.",
    "In Donbas they were attacked with bullets and shells.",
    "The Ukrainian government has been unable to control the region since 2014.",
    "This is why we are calling for an immediate ceasefire."
]

for sentence in sentences:
    print(tag_sentence(sentence))
```

Note: This code uses regular expressions to find patterns in the text. It's not perfect and may not work for all cases, but it should give you a good starting point. You can adjust the regular expressions to better fit your needs. Also, keep in mind that this is a simple implementation and doesn't handle edge cases like punctuation or multiple consecutive tags. For a more robust solution, consider using a natural language processing library like spaCy.
)```python
import re

def tag_sentence(sentence):
    # Define regular expressions for claims and premises
    claim_pattern = r"why|because|therefore"
    premise_pattern = r"reported|called|has been"

    # Tag claims and premises
    sentences = [sentence]
    for pattern in [
Split: ['<premise>', 'In', 'Donbas', 'they', 'were', 'attacked', 'with', 'bullets', 'and', 'shells.', '</premise>', 'Sentence:', 'The', 'Ukrainian', 'government', 'has', 'been', 'unable', 'to', 'control', 'the', 'region', 'since', '2014.', 'Output:', '<premise>', 'The', 'Ukrainian', 'government', 'has', 'been', 'unable', 'to', 'control', 'the', 'region', 'since', '2014.', '</premise>', 'Sentence:', 'This', 'is', 'why', 'we', 'are', 'calling', 'for', 'an', 'immediate', 'ceasefire.', 'Output:', '<claim>', 'This', 'is', 'why', 'we', 'are', 'calling', 'for', 'an', 'immediate', 'ceasefire.', '</claim>', '```python', 'import', 're', 'def', 'tag_sentence(sentence):', '#', 'Define', 'regular', 'expressions', 'for', 'claims', 'and', 'premises', 'claim_pattern', '=', 'r"why|because|therefore"', 'premise_pattern', '=', 'r"reported|called|has', 'been"', '#', 'Tag', 'claims', 'and', 'premises', 'sentences', '=', '[sentence]', 'for', 'pattern', 'in', '[claim_pattern,', 'premise_pattern]:', 'new_sentences', '=', '[]', 'for', 's', 'in', 'sentences:', 'matches', '=', 're.findall(pattern,', 's)', 'if', 'matches:', 'new_sentences.append(re.sub(pattern,', 'f"', "{('claim'", 'if', 'pattern', '==', 'claim_pattern', 'else', "'premise')}", '",', 's))', 'else:', 'new_sentences.append(s)', 'sentences', '=', 'new_sentences', 'return', 'sentences[0]', 'sentences', '=', '[', '"United', 'Nations', 'monitors', 'have', 'reported', 'a', 'consistent', 'reinforcement', 'of', 'barricades', 'and', 'armed', 'civilians', 'on', 'both', 'sides.",', '"The', 'situation', 'is', 'therefore', 'now', 'more', 'combustible', 'than', 'ever.",', '"The', 'Russian', 'Federation', 'has', 'called', 'for', 'this', 'emergency', 'meeting', 'of', 'the', 'Security', 'Council', 'because', 'of', 'the', 'serious', 'dangerous', 'evolution', 'of', 'the', 'situation', 'in', 'south-eastern', 'Ukraine.",', '"In', 'Donbas', 'they', 'were', 'attacked', 'with', 'bullets', 'and', 'shells.",', '"The', 'Ukrainian', 'government', 'has', 'been', 'unable', 'to', 'control', 'the', 'region', 'since', '2014.",', '"This', 'is', 'why', 'we', 'are', 'calling', 'for', 'an', 'immediate', 'ceasefire."', ']', 'for', 'sentence', 'in', 'sentences:', 'print(tag_sentence(sentence))', '```', 'Note:', 'This', 'code', 'uses', 'regular', 'expressions', 'to', 'find', 'patterns', 'in', 'the', 'text.', "It's", 'not', 'perfect', 'and', 'may', 'not', 'work', 'for', 'all', 'cases,', 'but', 'it', 'should', 'give', 'you', 'a', 'good', 'starting', 'point.', 'You', 'can', 'adjust', 'the', 'regular', 'expressions', 'to', 'better', 'fit', 'your', 'needs.', 'Also,', 'keep', 'in', 'mind', 'that', 'this', 'is', 'a', 'simple', 'implementation', 'and', "doesn't", 'handle', 'edge', 'cases', 'like', 'punctuation', 'or', 'multiple', 'consecutive', 'tags.', 'For', 'a', 'more', 'robust', 'solution,', 'consider', 'using', 'a', 'natural', 'language', 'processing', 'library', 'like', 'spaCy.', ')```python', 'import', 're', 'def', 'tag_sentence(sentence):', '#', 'Define', 'regular', 'expressions', 'for', 'claims', 'and', 'premises', 'claim_pattern', '=', 'r"why|because|therefore"', 'premise_pattern', '=', 'r"reported|called|has', 'been"', '#', 'Tag', 'claims', 'and', 'premises', 'sentences', '=', '[sentence]', 'for', 'pattern', 'in', '[']
Tokens: ['b-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise', 'o']

In [640]:
labels = flatten(df['ner_tags'].tolist())
labels[:5]

['b-claim', 'i-claim', 'i-claim', 'i-claim', 'i-claim']

In [641]:
predictions = df.apply(lambda row: tokens_to_bio(split_on_pattern(row['response']), size=len(row['ner_tags'])),
                       axis=1).tolist()
predictions = flatten(predictions)
predictions[:5]

['b-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise']

In [642]:
round(f1_score(y_true=labels, y_pred=predictions, average="macro"), 3)

0.303

In [643]:
os.remove("/content/few_shot_sequence_labelling.csv")

## fine-tuning

In [644]:
df = pd.read_csv("/content/fine_tuning_sequence_labelling.csv")

In [645]:
df.head()

,text,label,prediction
0,The United Kingdom welcomed that agreement and...,<claim> The United Kingdom welcomed that agree...,<claim> The United Kingdom welcomed that agree...
1,Based on the United Nations principle of colle...,<premise> Based on the United Nations principl...,Based on the United Nations principle of colle...
2,"Nonetheless , the crisis in eastern Ukraine is...","<claim> Nonetheless , the crisis in eastern Uk...","Nonetheless, <claim> the crisis in eastern Ukr..."
3,It has been claimed that Ukraine is building u...,<premise> It has been claimed that Ukraine is ...,<claim> It has been claimed that Ukraine is bu...
4,We hae to let it work .,<claim> We hae to let it work . </claim>,<claim> We hae to let it work. </claim>

In [646]:
df['label_BIO'] = df.apply(lambda row: tokens_to_bio(row['label'].split(), size=None), axis=1)

In [647]:
labels = flatten(df['label_BIO'].tolist())
labels[:5]

['b-claim', 'i-claim', 'i-claim', 'i-claim', 'i-claim']

In [648]:
predictions = df.apply(lambda row: tokens_to_bio(split_on_pattern(row['prediction']), size=len(row['label_BIO'])),
                       axis=1).tolist()
predictions = flatten(predictions)
predictions[:5]

['b-claim', 'i-claim', 'i-claim', 'i-claim', 'i-claim']

In [649]:
print(predictions[100:140])
print(labels[100:140])

['i-claim', 'i-claim', 'i-claim', 'i-claim', 'i-claim', 'i-claim', 'i-claim', 'o', 'b-claim', 'i-claim', 'i-claim', 'i-claim', 'i-claim', 'i-claim', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'b-claim', 'i-claim', 'i-claim', 'i-claim', 'i-claim', 'i-claim', 'i-claim', 'i-claim', 'i-claim', 'i-claim', 'i-claim', 'i-claim', 'i-claim', 'i-claim', 'i-claim']
['i-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise', 'b-claim', 'i-claim', 'i-claim', 'i-claim', 'i-claim', 'i-claim', 'i-claim', 'b-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise', 'i-premise']

In [650]:
round(f1_score(y_true=labels, y_pred=predictions, average="macro"), 3)

0.396

In [651]:
os.remove("/content/fine_tuning_sequence_labelling.csv")

# NER

## zero-shot

In [49]:
import pandas as pd
from sklearn.metrics import f1_score
import os

In [50]:



def tokenize_with_punctuation(text):
    return re.findall(r"\w+|[^\w\s]", text)


def split_on_pattern(text):
    pattern = r"</?\w+>|[^\s<>]+"
    tokens = re.findall(pattern, text)
    return tokens

In [51]:
def tokens_to_bio(tokens, size: int = None):
    bio_tags = []

    for token in tokens:
        if token.startswith("<") and not token.startswith("</"):
            bio_tags.append(token[1:-1].lower())

    if size != None:
        bio_tags = bio_tags[:size]
        if len(bio_tags) < size:
            bio_tags += ["o"] * (size - len(bio_tags))

    return bio_tags

In [52]:
def flatten(xss):
    return [x for xs in xss for x in xs]

In [53]:
df = pd.read_csv("/content/zero_shot_ner.csv")
df['ner_tags'] = df['ner_tags'].apply(lambda s: ast.literal_eval(s))

In [54]:
df.head()

,text,ner_tags,response
0,Good_evening from the University of Miami Conv...,"[vbg, in, dt, nnp, in, nnp, nnp, nnp, in, nnp,...",Good_<JJ> evening <FW> from <NNP> the <NNP> U...
1,I 'm Jim Lehrer of The NewsHour on PBS .,"[prp, vbp, nnp, nnp, in, dt, nn, in, nnp, .]",I <PRP> ‘m <NNP> Jim <NNP> Lehrer <IN> of <NN...
2,And I welcome you to the first of the 2004 pre...,"[cc, prp, vbp, prp, to, dt, jj, in, dt, cd, jj...",<CC>And</CC> <PRP>I</PRP> <FW>welcome</FW> <F...
3,These debates are sponsored by the Commission ...,"[dt, nns, vbp, vbn, in, dt, nnp, in, nnp, nns, .]",<JJ>These</JJ> <DT>debates</DT> <RB>are</RB> ...
4,"Tonight 's will last 90 minutes , following de...","[nnp, pos, md, vb, cd, nns, ,, vbg, jj, nns, i...",Tonight <POS>'s <POS> will <VBP> last <CD> 90...

In [55]:
example = df.iloc[2]
print(example['response'])
print(tokens_to_bio(split_on_pattern(example['response'])))

 <CC>And</CC> <PRP>I</PRP> <FW>welcome</FW> <FW>you</FW> <FW>to</FW> <DT>the</DT> <LS>first</LS> <IN>of</IN> <DT>the</DT> <CD>2004</CD> <FW>presidential</FW> <FW>debates</FW> <IN>between</IN> <NNP>President</NNP> <NNP>George</NNP> <FW>W.</FW> <NNP>Bush</NNP> <FW>,</FW> <NNP>the</NNP> <NNS>Republican</NNS> <FW>nominee</FW> <FW>,</FW> <FW>and</FW> <NNP>Senator</NNP> <NNP>John</NNP> <NNP>Kerry</NNP> <FW>,</FW> <FW>the</FW> <NNS>Democratic</NNS> <FW>nominee</FW> <FW>.</FW>

['cc', 'prp', 'fw', 'fw', 'fw', 'dt', 'ls', 'in', 'dt', 'cd', 'fw', 'fw', 'in', 'nnp', 'nnp', 'fw', 'nnp', 'fw', 'nnp', 'nns', 'fw', 'fw', 'fw', 'nnp', 'nnp', 'nnp', 'fw', 'fw', 'nns', 'fw', 'fw']

In [56]:
labels = flatten(df['ner_tags'].tolist())
labels[:5]

['vbg', 'in', 'dt', 'nnp', 'in']

In [57]:
predictions = df.apply(lambda row: tokens_to_bio(split_on_pattern(row['response']), size=len(row['ner_tags'])),
                       axis=1).tolist()
predictions = flatten(predictions)
predictions[:5]

['jj', 'fw', 'nnp', 'nnp', 'nnp']

In [58]:
round(f1_score(y_true=labels, y_pred=predictions, average="macro"), 3)

0.005

In [59]:
os.remove("/content/zero_shot_ner.csv")

## few-shot

In [28]:
import re
import ast


def tokenize_with_punctuation(text):
    return re.findall(r"\w+|[^\w\s]", text)


def split_on_pattern(text):
    pattern = r"</?\w+>|[^\s<>]+"
    tokens = re.findall(pattern, text)
    return tokens

In [29]:
def tokens_to_bio(tokens, size: int = None):
    bio_tags = []

    for token in tokens:
        if token.startswith("<") and not token.startswith("</"):
            bio_tags.append(token[1:-1].lower())

    if size != None:
        bio_tags = bio_tags[:size]
        if len(bio_tags) < size:
            bio_tags += ["o"] * (size - len(bio_tags))

    return bio_tags

In [30]:
def flatten(xss):
    return [x for xs in xss for x in xs]

In [31]:
df = pd.read_csv("/content/few_shot_ner.csv")
df['ner_tags'] = df['ner_tags'].apply(lambda s: ast.literal_eval(s))

In [32]:
df.head()

,text,ner_tags,response
0,Good_evening from the University of Miami Conv...,"[vbg, in, dt, nnp, in, nnp, nnp, nnp, in, nnp,...",<UH>Good_evening</UH> <FROM>from</FROM> <NNP>...
1,I 'm Jim Lehrer of The NewsHour on PBS .,"[prp, vbp, nnp, nnp, in, dt, nn, in, nnp, .]",<PRP>I</PRP> <VBZ>'m</VBZ> <NNP>Jim</NNP> <NN...
2,And I welcome you to the first of the 2004 pre...,"[cc, prp, vbp, prp, to, dt, jj, in, dt, cd, jj...",<CC>And</CC> <PRP>I</PRP> <VBP>welcome</VBP> ...
3,These debates are sponsored by the Commission ...,"[dt, nns, vbp, vbn, in, dt, nnp, in, nnp, nns, .]",<DT>These</DT> <JJ>debates</JJ> <NN>are</NN> ...
4,"Tonight 's will last 90 minutes , following de...","[nnp, pos, md, vb, cd, nns, ,, vbg, jj, nns, i...",<DT>Tonight</DT>'s<TO>will</TO><VB>last</VB><...

In [33]:
example = df.iloc[2]
print(example['response'])
print(tokens_to_bio(split_on_pattern(example['response'])))

 <CC>And</CC> <PRP>I</PRP> <VBP>welcome</VBP> <PRP>you</PRP> <TO>to</TO> <DT>the</DT> <JJ>first</JJ> <NNS>of</NNS> <CD>the</CD> <NN>2004</NN> <NN>presidential</NN> <NNS>debates</NNS> <IN>between</IN> <NNP>President</NNP> <NN>George</NN> <NN>W.</NNP> <NN>Bush</NNP> <,>,</,> <NN>the</NN> <NNP>Republican</NNP> <NN>nominee</NNP> <,>,</,> <NNP>and</NNP> <,>,</,> <NNP>Senator</NNP> <NN>John</NNP> <NN>Kerry</NNP> <,>,</,> <NNP>the</NNP> <NN>Democratic</NNP> <NN>nominee</NNP><.>.</.>
['cc', 'prp', 'vbp', 'prp', 'to', 'dt', 'jj', 'nns', 'cd', 'nn', 'nn', 'nns', 'in', 'nnp', 'nn', 'nn', 'nn', 'nn', 'nnp', 'nn', 'nnp', 'nnp', 'nn', 'nn', 'nnp', 'nn', 'nn']

In [34]:
labels = flatten(df['ner_tags'].tolist())
labels[:5]

['vbg', 'in', 'dt', 'nnp', 'in']

In [35]:
predictions = df.apply(lambda row: tokens_to_bio(split_on_pattern(row['response']), size=len(row['ner_tags'])),
                       axis=1).tolist()
predictions = flatten(predictions)
predictions[:5]

['uh', 'from', 'nnp', 'of', 'nn']

In [36]:
round(f1_score(y_true=labels, y_pred=predictions, average="macro"), 3)

0.014

In [37]:
os.remove("/content/few_shot_ner.csv")

## fine-tuning

In [60]:
df = pd.read_csv("/content/fine_tuning_ner.csv")

In [61]:
df.head(5)

,text,label,prediction
0,Good_evening from the University of Miami Conv...,<VBG>Good_evening</VBG><IN>from</IN><DT>the</D...,<VB>Good_evening</VB><IN>from</IN><DT>the</DT>...
1,I 'm Jim Lehrer of The NewsHour on PBS .,<PRP>I</PRP><VBP>'m</VBP><NNP>Jim</NNP><NNP>Le...,<PRP>I</PRP><VBP>'m</VBP><NNP>Jim</NNP><NNP>Le...
2,And I welcome you to the first of the 2004 pre...,<CC>And</CC><PRP>I</PRP><VBP>welcome</VBP><PRP...,<CC>And</CC><PRP>I</PRP><VBP>welcome</VBP><PRP...
3,These debates are sponsored by the Commission ...,<DT>These</DT><NNS>debates</NNS><VBP>are</VBP>...,<DT>These</DT><NNS>debates</NNS><VBP>are</VBP>...
4,"Tonight 's will last 90 minutes , following de...",<NNP>Tonight</NNP><POS>'s</POS><MD>will</MD><V...,<NN>Tonight</NN><POS>'s</POS><NN>will</NN><VB>...

In [62]:
labels = df.apply(lambda row: tokens_to_bio(split_on_pattern(row['label']), size=len(row['text'].split())),
                  axis=1).tolist()
labels = flatten(labels)
labels[:5]

['vbg', 'in', 'dt', 'nnp', 'in']

In [63]:
predictions = df.apply(lambda row: tokens_to_bio(split_on_pattern(row['prediction']), size=len(row['text'].split())),
                       axis=1).tolist()
predictions = flatten(predictions)
predictions[:5]

['vb', 'in', 'dt', 'nnp', 'in']

In [64]:
round(f1_score(y_true=labels, y_pred=predictions, average="macro"), 3)

0.708

In [65]:
os.remove("/content/fine_tuning_ner.csv")